### ISSUE TITLE
https://ok.ru/

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardExtra#1]
@Alex-302 commented on [Wed Jun 19 2019](https://github.com/AdguardTeam/AdguardFilters/issues/35505)

Ads reinjection.

Screenshots:
<details>

![image](https://user-images.githubusercontent.com/8361299/59772815-2f313280-92b5-11e9-84f6-22e8bc57ea7e.png)

</details>

<details>

![image](https://user-images.githubusercontent.com/8361299/59772890-4a03a700-92b5-11e9-959f-c66556ce12f6.png)

</details>

Promoted post is also obfuscated.

**Comment by ameshkov** [comment]
Fixed in `pull-requests/15`

**Comment by Alex-302** [comment]
Advertising post with app and browser extension:
<details>

![image](https://user-images.githubusercontent.com/8361299/64619813-63674b80-d3eb-11e9-9928-70acc9bca133.png)

</details>

**Comment by ameshkov** [comment]
Cannot reproduce this in Chrome with AG+AGExtra

**Comment by Alex-302** [comment]
Strange. Not reproduced now.

**Comment by Alex-302** [comment]
![image](https://user-images.githubusercontent.com/8361299/66820960-47a31800-ef4a-11e9-8059-3ef7555fecef.png)
