### ISSUE TITLE
afisha.yandex.ru

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardExtra#10]
https://github.com/AdguardTeam/AdguardFilters/issues/37727

**Comment by Alex-302** [comment]
Ping
Added new rules.

**Comment by Alex-302** [comment]
@tvinzz https://github.com/AdguardTeam/AdguardFilters/issues/41732

**Comment by Alex-302** [comment]
https://realty.yandex.ru/?from=all

![image](https://user-images.githubusercontent.com/8361299/66504845-bf98ba80-ead2-11e9-91fe-a44ad3f63297.png)
