### ISSUE TITLE
gismeteo.ua

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardExtra#102]
https://github.com/AdguardTeam/AdguardFilters/issues/53678

**Comment by tvinzz** [comment]
ads gismeteo.ru and gismeteo.com successfully blocked by rules, can we do the same for gismeteo.ua?
or should we add all these websites to extra?

**Comment by ameshkov** [comment]
@tvinzz they use a different approach on UA version of the website, it's quite hard to handle it with rules

**Comment by Alex-302** [comment]
Use our Ukrainian VPN to check this issue.
