### ISSUE TITLE
yaplakal.com

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdGuardExtra#104]
Ads on the lenta main page `yaplakal.com`.
<details><summary>Screenshot:</summary>

![yap1](https://user-images.githubusercontent.com/33488229/91298355-8d568100-e7a8-11ea-9876-1bf72cc44420.png)

</details><br/>

**Comment by Alex-302** [comment]
they have a mirror - yap.ru

**Comment by zloyden** [comment]
Ok, added it.
