### ISSUE TITLE
rambler.ru

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardExtra#12]
https://github.com/AdguardTeam/AdguardFilters/issues/33047
and subdomains
https://doctor.rambler.ru/medscience/42631123-kak-zdorovaya-zhenschina-zarazila-polsotni-chelovek/
Browser extension only.

**Comment by Alex-302** [comment]
Another site with the same script: https://github.com/AdguardTeam/AdguardFilters/issues/42061

**Comment by zloyden** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/44280#issuecomment-564514148 прорвался директ

**Comment by Sergey-Lyapin** [comment]
Yandex Direct has appeared again.
![Screenshot 2020-01-13 at 14 06 04](https://user-images.githubusercontent.com/18536328/72251742-5fed0680-360f-11ea-946d-1b3df78f1eac.png)
![Screenshot 2020-01-13 at 14 00 06](https://user-images.githubusercontent.com/18536328/72251965-a17db180-360f-11ea-81c2-4fc03ab36b02.png)

**Comment by Alex-302** [comment]
Check with extension with disabled Annoyances filter: 
https://github.com/AdguardTeam/AdguardFilters/issues/45888
also please check another domains
