### ISSUE TITLE
pravda.com.ua

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardExtra#123]
https://github.com/AdguardTeam/AdguardFilters/issues/56518

**Comment by ameshkov** [comment]
https://forum.adguard.com/index.php?threads/%D0%9F%D1%80%D0%BE%D0%BF%D1%83%D1%81%D0%BA%D0%B0%D0%B5%D1%82-%D1%80%D0%B5%D0%BA%D0%BB%D0%B0%D0%BC%D1%83-%D0%BD%D0%B0-%D0%B2%D1%81%D0%B5%D1%85-%D1%81%D0%B0%D0%B9%D1%82%D0%B0%D1%85-%D0%B2-%D1%84%D0%BE%D0%BD%D0%BE%D0%B2%D1%8B%D1%85-%D0%B2%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B0%D1%85.38067/#post-204247
