### ISSUE TITLE
yandex.ru

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardExtra#135]
https://github.com/AdguardTeam/AdguardFilters/issues/66495#issuecomment-730193213

### Issue URL (Ads)
 [https://yandex.ru/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fyandex.ru%2F)
### Comment
> 
> --
> Информация ниже сгенерирована автоматически. Не удаляйте ее.
> 
> Referrer:
> 
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js
> https://userscripts.adtidy.org/release/adguard-wot/1.0/wot.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/5hWLhIr.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.5.2
Browser: | Opera
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, <br/>Send Do-Not-Track header, <br/>Remove X-Client-Data header from HTTP requests, <br/>Self-destructing third-party cookies (180), <br/>Block Push API, <br/>Block Location API
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> AdGuard Russian

**Comment by MaximusPanin** [comment]
https://tv.yandex.ru

Something Yandex changes periodically and advertising pops up. Cookies dropped, it does not help for long.

https://i.gyazo.com/c2499769339ec95f5c31bdf12f51c691.png
https://i.gyazo.com/23133e1db086650b3649f16b6c9ef214.png

**Comment by ameshkov** [comment]
@zloyden please check what's wrong there.

**Comment by zloyden** [comment]
Not reproduced on my end, those blocks are blocked fine.
<details><summary>Screenshot:</summary>

![ytv](https://user-images.githubusercontent.com/33488229/108969536-ca85c800-7692-11eb-8052-905a723221a8.png)

</details><br/>

**Comment by MaximusPanin** [comment]
This is a lottery. He works differently every day.

![257н45](https://user-images.githubusercontent.com/24373505/108988025-a5965280-769c-11eb-8ca1-05e09c446e5a.png)

**Comment by zloyden** [comment]
https://github.com/AdguardTeam/AdGuardExtra/issues/135#issuecomment-784979306
I understand you, Yandex sometimes make changes. This one (at the header) I had today morning, but it's not an ad. It's like a ~ promotion of their services (kinopoisk). So, it was solved via our filters. `AdGuard Annoyances` should be enabled in uBlock extension.

**Comment by MaximusPanin** [comment]
> [#135 (comment)](https://github.com/AdguardTeam/AdGuardExtra/issues/135#issuecomment-784979306)
> I understand you, Yandex sometimes make changes. This one (at the header) I had today morning, but it's not an ad. It's like a ~ promotion of their services (kinopoisk). So, it was solved via our filters. `AdGuard Annoyances` should be enabled in uBlock extension.

I showed with a screenshot that the blocking works today. A couple of days ago, no. See my previous screenshots.

**Comment by zloyden** [comment]
Ok, thanks for the explanation and your report. But for now it's not reproduced. Maybe they has been testing it on the small group of users.
Anyway, once we are able to reproduce it, we will solve this.
