### ISSUE TITLE
drive2.ru / drive2.com

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardExtra#14]
Desktop app only.

https://www.drive2.ru/l/8655075/
<details>
This banner is hidden by `drive2.ru,drive2.com##.dv-post-header`. But it seems not for long.

![image](https://user-images.githubusercontent.com/8361299/62929406-1b8cde80-bdc3-11e9-9c3c-cc984cd6fbdb.png)

</details>

<details>

![image](https://user-images.githubusercontent.com/8361299/62929450-2fd0db80-bdc3-11e9-8917-476604ffdc45.png)

</details>

<details>

![image](https://user-images.githubusercontent.com/8361299/62929494-45460580-bdc3-11e9-8716-3c1e17969dae.png)

</details>

https://www.drive2.ru/r/fiat/multipla/1560926/logbook/

<details>

![image](https://user-images.githubusercontent.com/8361299/62929587-71618680-bdc3-11e9-908b-62dae356b5d0.png)

</details>

I don't see ads on another pages.

---

Check with disabled JS/scriptlets.

**Comment by Alex-302** [comment]
Leftover: 
![image](https://user-images.githubusercontent.com/8361299/63798327-8d603e80-c912-11e9-8d02-9018d17f3fc7.png)

**Comment by Alex-302** [comment]
again...

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/42969#issuecomment-575885443

**Comment by zloyden** [comment]
And here https://github.com/AdguardTeam/AdguardFilters/issues/42969#issuecomment-570767954
