### ISSUE TITLE
weekend.rambler.ru

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardExtra#143]
@adguard-bot commented on [Tue Dec 01 2020](https://github.com/AdguardTeam/AdguardFilters/issues/68974)

### Issue URL (Ads)
 [https://weekend.rambler.ru/crazy-world/45249162-pricheski-kotorye-mozhno-nazvat-tolko-strashnym-snom-kazhdogo-parikmahera/?slides=1#h7](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fweekend.rambler.ru%2Fcrazy-world%2F45249162-pricheski-kotorye-mozhno-nazvat-tolko-strashnym-snom-kazhdogo-parikmahera%2F%3Fslides%3D1%23h7)
### Comment
Username: @spok1
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/mOBrZXb.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.23
Browser: | Chrome
Stealth mode options: | Hide your search queries, <br/>Send Do-Not-Track header, <br/>Remove X-Client-Data header from HTTP requests, <br/>Strip URLs from tracking parameters, <br/>Hide your Referrer from third-parties
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Other:</b><br/> AdGuard Experimental<br/><br/><b>Language-specific:</b><br/> AdGuard Russian

---

@adguard-bot commented on [Tue Dec 01 2020](https://github.com/AdguardTeam/AdguardFilters/issues/68974#issuecomment-736211718)

### Issue URL (Annoyance)
 [https://weekend.rambler.ru/crazy-world/45249162-pricheski-kotorye-mozhno-nazvat-tolko-strashnym-snom-kazhdogo-parikmahera/?slides=1#a9](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fweekend.rambler.ru%2Fcrazy-world%2F45249162-pricheski-kotorye-mozhno-nazvat-tolko-strashnym-snom-kazhdogo-parikmahera%2F%3Fslides%3D1%23a9)
### Comment
Username: @spok1
> После последнего слайда появляется пустое окно! Подозрение на рекламу!

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/qQrLiM1.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.23
Browser: | Chrome
Stealth mode options: | Hide your search queries, <br/>Send Do-Not-Track header, <br/>Remove X-Client-Data header from HTTP requests, <br/>Strip URLs from tracking parameters, <br/>Hide your Referrer from third-parties
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Other:</b><br/> AdGuard Experimental<br/><br/><b>Language-specific:</b><br/> AdGuard Russian

**Comment by Alex-302** [comment]
weekend.rambler.ru + subdomains

**Comment by Spok1** [comment]
@Alex-302, @zloyden, а что, исправлять не собираетесь? Вон бот уже позакрывать решил...😐

**Comment by zloyden** [comment]
В последней версии AdGuard Extra больше этого не наблюдаю.
