### ISSUE TITLE
mail.yandex.ru

### ISSUE THREAD

**Issue by Sergey-Lyapin** [AdguardTeam/AdGuardExtra#145]
![Безымянный](https://user-images.githubusercontent.com/18536328/102829931-3df02c80-43f9-11eb-8145-140649faa046.png)

**Comment by zloyden** [comment]
Not reproduced on my end. It is blocked by AdGuard Extra.

**Comment by ameshkov** [comment]
It seems that the issue is reproduced randomly.

@zloyden please try keeping Yandex Mail open in some tab in the background and check it periodically, at some point the ad may pop up.

**Comment by zloyden** [comment]
I have opened the `mail` tab in the morning in the background and still not reproduced for now.
I will check this periodically throughout the day.
