### ISSUE TITLE
zen.yandex.ru

### ISSUE THREAD

**Issue by Sergey-Lyapin** [AdguardTeam/AdGuardExtra#146]
https://zen.yandex.ru/media/travelone/5-oblastnyh-centrov-stremitelno-teriaiuscih-naselenie-5fd3472affa0ae77099351da

![Безымянный2](https://user-images.githubusercontent.com/18536328/102830382-4301ab80-43fa-11eb-9c3d-9a4971a124f3.png)

**Comment by ameshkov** [comment]
Can't repro it with AG Extra.

@zloyden please check this and close the issue if it's not reproduced.

**Comment by zloyden** [comment]
I also wasn't able to reproduce it.
