### ISSUE TITLE
Object.prototype.__proto__ Deprecated

### ISSUE THREAD

**Issue by RX-3200** [AdguardTeam/AdGuardExtra#147]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* Userscript https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js
```
...
        var contentWindowDescriptor = Object.getOwnPropertyDescriptor(iframe.__proto__, 'contentWindow');
...
        Object.defineProperty(iframe.__proto__, 'contentWindow', contentWindowDescriptor);
...
```
> `Object.prototype.__proto__` Deprecated
> This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes.
>  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto 

* and please use scheme:
```
// ==UserScript==
// @* ***
// ==/UserScript==

(function() {

    // Your code here...
})();
```

**Comment by stanislav-atr** [comment]
Using deprecated features is sometimes necessary to deal with ad scripts. As of now there is no such code in the repo.

Conversely, there is no need in [IIFE](https://developer.mozilla.org/en-US/docs/Glossary/IIFE) for Extra to work, so it is not used here.
