### ISSUE TITLE
mail.yandex.ru

### ISSUE THREAD

**Issue by Sergey-Lyapin** [AdguardTeam/AdGuardExtra#149]
Стабильно повторяется реклама в левой колонке и реклама после отправки письма (в хроме с расширением)
![Screenshot 2021-01-15 at 18 22 37](https://user-images.githubusercontent.com/18536328/104745304-fe4e0380-575e-11eb-8932-748749a6b5b5.png)
![Screenshot 2021-01-15 at 18 17 33](https://user-images.githubusercontent.com/18536328/104745321-03ab4e00-575f-11eb-943f-efc955e49b6c.png)

**Comment by maxuko** [comment]
![Untitled-2](https://user-images.githubusercontent.com/8029629/104843462-d506b200-58db-11eb-9423-4d1b39113eb9.jpg)

**Comment by ameshkov** [comment]
@maxuko попробуйте пожалуйста бета-версию вместо обычной - https://chrome.google.com/webstore/detail/adguard-extra-beta/mglpocjcjbekdckiahfhagndealpkpbj?hl=en&authuser=0
