### ISSUE TITLE
gazeta.ru [browser extension]

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardExtra#15]
gazeta.ru
<details>

![image](https://user-images.githubusercontent.com/8361299/63164133-21d3c280-c030-11e9-8749-952dc5a221d9.png)

</details>

https://www.gazeta.ru/politics/news/2019/08/16/n_13348663.shtml

<details>

![image](https://user-images.githubusercontent.com/8361299/63164152-3b750a00-c030-11e9-84d6-9b2e15942b0d.png)

</details>

<details>

![image](https://user-images.githubusercontent.com/8361299/63164169-4b8ce980-c030-11e9-936a-d351c00c58a4.png)

</details>

**Comment by ameshkov** [comment]
Cannot reproduce.

Make sure that inject mode is set to instant.

**Comment by Alex-302** [comment]
Strange. Not reproduced now.
