### ISSUE TITLE
YouTube support 

### ISSUE THREAD

**Issue by MaximusPanin** [AdguardTeam/AdGuardExtra#150]
Hello.
Increasingly, I see ad blockers failing YouTube and skipping banner ads. I've tried AdGuard, uBlockOrigin. But I see how well **AdGuard Extra** works with Yandex. Can you add YouTube support ?

**Comment by ameshkov** [comment]
Well, Youtube ads are blocked just okay by AdGuard (as well as by uBO).

It's possible that your problems with it are caused by the fact that you're using multiple blockers.
To narrow the issue down, try a clean browser profile, install AdGuard and AdGuard Extra and see how it goes with YT.
