### ISSUE TITLE
Yandex.News(UA)

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardExtra#156]
https://yandex.ua/news/story/Bajden_vvazha_Pvnchnij_potk_2_nevigdnim_dlya_vropi--0663b59f57bf8b340cb3f7acfcfa31bf
![image](https://user-images.githubusercontent.com/8361299/106019331-32b0b080-60cb-11eb-88a1-832649aaea30.png)

**Comment by zloyden** [comment]
Не повторяется, у меня эта реклама блокируется с AdGuard Extra, так же и под аккаунтом.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/106107771-64238d80-6158-11eb-98b8-9dd4ac48f352.png)

</details><br/>

**Comment by Alex-302** [comment]
В нашем чате ответил.
