### ISSUE TITLE
Блокировка Suggested posts в ленте Facebook

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardExtra#159]
@Chinaski1 commented on [Tue Jan 26 2021](https://github.com/AdguardTeam/AdguardFilters/issues/73287)

@jbionic2016 commented on [Mon Jan 18 2021](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1751)

Приветствую.

Проблема касается отображения ленты Facebook в Chrome-браузере с установленными расширениями Adguard AdBlocker 3.5.31 и Adguard Extra 1.0.204.

В ленте Facebook  достали уже Suggested posts от всяких фриков, спасающих собачек и снимающих себя на видео. Возможно ли сделать что-нибудь, чтоб заблокировать появление подобных постов в ленте?

Если есть иные проверенные решения на базе скриптов для Tampermonkey, то готов рассмотреть, только дайте ссылки.

Заранее благодарю.

Operating system: Windows 10 Home
Browser: Chrome Version  87.0.4280.141 (Official Build) (64-bit)
AdGuard version for Chrome: Version 3.5.31
Filters enabled: AdGuard Base filter, AdGuard Tracking Protection filter, EasyPrivacy, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter
Stealth mode options (Windows only) Enabled
 AdGuard Extra 1.0.204

---

@jbionic2016 commented on [Wed Jan 20 2021](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1751#issuecomment-763565213)

Кстати, вопрос актуален и для Android-версии приложения Facebook Lite. Я правда не уверен, что непремиальный Adguard сможет в этом случае что-то предложить, учитывая, что Suggested posts показываются в родном приложении Фейсбука, а не в стороннем браузере независимого производителя.

---

@Chinaski1 commented on [Wed Jan 20 2021](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1751#issuecomment-763634206)

Добрый день, @jbionic2016.

Вы не могли бы, пожалуйста, уточнить о каких именно Suggested posts идет речь (желательно со скриншотами)?
Также вам следует попробовать открыть браузер в режиме инкогнито и проверить, проложат ли данные посты появляться в вашей ленте.

---

@jbionic2016 commented on [Wed Jan 20 2021](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1751#issuecomment-763688680)

Да, пожалуйста, сколько угодно. 
https://i114.fastpic.ru/big/2021/0120/c8/7532ab48a12711b236a759eb96b35ac8.jpg
https://i114.fastpic.ru/big/2021/0120/49/ed694acc1e0f2d007a5c70adfef27d49.jpg
https://i114.fastpic.ru/big/2021/0120/f6/46a76f409664f6fe72069afbd76c9df6.jpg
https://i114.fastpic.ru/big/2021/0120/92/0604c40cac64cc2b662165af4b0f4892.jpg

Проверил в режиме инкогнито - проблема остаётся, последний из скриншотов выше как раз в режиме инкогнито был сделан.

---

@jbionic2016 commented on [Wed Jan 20 2021](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1751#issuecomment-763703438)

Кстати, аналогичная проблема есть и в ленте Quora 
https://thumbsnap.com/urfKMRed

Тоже какой-то идиот решил что мне может быть интересно..

---

@jbionic2016 commented on [Mon Feb 01 2021](https://github.com/AdguardTeam/AdguardFilters/issues/73287#issuecomment-770722225)

Даже классифицировать issue не стали? :) 
https://i114.fastpic.ru/big/2021/0201/78/450fbf1e7cb5730fbfa58907c2c3ea78.jpg

---

@Alex-302 commented on [Thu Feb 04 2021](https://github.com/AdguardTeam/AdguardFilters/issues/73287#issuecomment-773180261)

Метки ставит бот при отправке отчёта. При ручном создании они не цепляются.

**Comment by jbionic2016** [comment]
Спасибо, Алекс. Кстати, а мобильную версию AdguardExtra ещё не сделали для Андроидов?
Хотя конечно, даже если только для Windows проблему удастся решить, я буду рад.

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/74428

```
@jbionic2016 
 Приветствую.

Очень много пропущенной рекламы наблюдается в последние недели на facebook. Добавляется новая в новых местах. Прикрепляю сегодняшний замеченный пример
https://i114.fastpic.ru/big/2021/0209/72/a413a13f5f1382073c5977991cd18372.jpg

Это в дополнение к моему другому недавнему запросу про рекламу на Фейсбуке:
https://github.com/AdguardTeam/AdGuardExtra/issues/159

С уважением.

===========
Operating system: Windows 10 Home
Browser: Chrome Version  88.0.4324.150 (Official Build) (64-bit)
AdGuard version for Chrome: Version 3.5.31
Filters enabled: AdGuard Base filter, AdGuard Tracking Protection filter, EasyPrivacy, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter
Stealth mode options (Windows only) Enabled
AdGuard Extra 1.0.211
```

**Comment by jbionic2016** [comment]
Как прогресс в решении задачи за 1.5 месяца?

Проблема остаётся быть актуальной. Последний пример:
https://i114.fastpic.ru/big/2021/0315/f2/0ed18a8265830a072ee62279f4f5bcf2.jpg

**Comment by zloyden** [comment]
Здравствуйте! Прошу прощения за поздний ответ.

Добавьте это правило в пользовательские, поскольку выше упомянутые посты не являются рекламой.
```
facebook.com#%#AG_onLoad(function() {var g = new MutationObserver(function() {var feedPosts = document.querySelectorAll('div[role="feed"] > div[data-pagelet^="FeedUnit"] > div[class]:not([style*="height"])');for (var i = 0; i < feedPosts.length; i++) {var feedPost = feedPosts[i];var feedPostTitleELement = feedPost.querySelector('div[class] > div[class] > span[dir="auto"]:only-child');if (feedPost && feedPostTitleELement && feedPostTitleELement.innerText.length < 20 && feedPostTitleELement.childElementCount === 0) {feedPost.style.setProperty('display', 'none', 'important');}}});g.observe(document, {childList: !0,subtree: !0});setTimeout(function() {g.disconnect()}, 1E5)});
```

**Comment by jbionic2016** [comment]
Здравствуйте.

Вы напрасно поспешили закрыть тему после 1.5-месяцев молчания. 

Во-первых, приведенный выше код проблему не решил. Suggested-посты остались. Привожу ниже пример такого поста уже после добавления вашего правила и перезапуска браузера:
https://i114.fastpic.ru/big/2021/0316/42/dccb26af4158692006229ab20f1b1942.jpg

Во-вторых, я не согласен с Вашим тезисом, что на Фейсбуке нет рекламных постов. И если выше-приведенный Suggested-пост действительно к рекламным может и не относится (хотя, на мой взгляд, он рекламирует канал, который его протолкнул в ленту), относится скорее к назойливым и непрошенным от этого канала. То как насчёт следующего скриншота с моего Фейсбука в Хроме под Windows, на котором явная реклама:
https://i114.fastpic.ru/big/2021/0316/e7/681a05392e5b7a17f9b6a98a5ad118e7.jpg

Был бы признателен за оперативное решение проблемы. Я уже начал подозревать что Adguard намеренно закрывает на неё глаза на фоне попыток российских регуляторов ограничить работу иностранных сервисов типа Twitter (и в перспективе, судя по реакции Adguard, и Facebook)

**Comment by jbionic2016** [comment]
Suggested posts в лента Facebook исчезли почли чистки Хрома с помощью CCleaner и перезапуска. Во всяком случае ПОКА ЧТО исчезли.

 А вот реклама с правой стороны осталась...
