### ISSUE TITLE
livejournal.com [Mobile]

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdGuardExtra#16]
@adguard-bot commented on [Wed Aug 21 2019](https://github.com/AdguardTeam/AdguardFilters/issues/38952)

### Issue URL (Ads)
[https://shakko-kitsune.livejournal.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fshakko-kitsune.livejournal.com%2F)
### Comment
Username: @GrigoryRasputyn
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/cPstkDf.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 9
AdGuard version: | v3.2.135 (1.4.138cl)
Browser: | Chrome
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Self-destructing first-party cookies (4320), Self-destructing third-party cookies (180), Disable cache for third-party requests, Hide your IP address (209.141.53.254)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | AdGuard Russian,<br>EasyList,<br>AdGuard Mobile Ads,<br>Fanboy's Social Blocking List,<br>AdGuard Annoyances,<br>AdGuard Simplified domain names,<br>AdGuard Base,<br>BarbBlock,<br>AdGuard Tracking Protection,<br>AdGuard Social Media,<br>AdGuard Experimental,<br>AdGuard German
Other extensions used: | Не используются

---

@BlazDT commented on [Wed Aug 21 2019](https://github.com/AdguardTeam/AdguardFilters/issues/38952#issuecomment-523323101)

Banner not shown on my Android 10 beta 6. Please check @zloyden 

---

@GrigoryRasputyn commented on [Wed Aug 21 2019](https://github.com/AdguardTeam/AdguardFilters/issues/38952#issuecomment-523324551)

Ремарка: реклама на livejournal.com при установленном (коммерческая версия) AdGuard показывалась всегда. На двух телефонах разных производителей и разных версиях Android (6 и 9). Одно оставалось неизменным - я всегда использовал Google Chrome, никаких других браузеров.
P.S. Система взаимодействия с Вашей технической поддержкой ужасна - скажите, зачем мне нужно регистрироваться на GitHub для того, чтобы отправить запрос? В целом, отправка реквеста заняла у меня около часа времени! Позор и ужас!

---

@GrigoryRasputyn commented on [Wed Aug 21 2019](https://github.com/AdguardTeam/AdguardFilters/issues/38952#issuecomment-523325629)

> 
> 
> Banner not shown on my Android 10 beta 6. Please check @zloyden

Currently I use Android 9 on Xiaomi MI9. In Google Chrome on Android 9 filter don`t block banners at livejournal.com. When Android 10 will accessible for my device, i check it.

**Comment by tvinzz** [comment]
https://github.com/AdguardTeam/AdguardFilters/pull/39619
