### ISSUE TITLE
docviewer.yandex.ru

### ISSUE THREAD

**Issue by stanislav-atr** [AdguardTeam/AdGuardExtra#163]
@adguard-bot commented on [Fri Feb 12 2021](https://github.com/AdguardTeam/AdguardFilters/issues/74683)

### Issue URL (Ads)
 [https://docviewer.yandex.ru/view/1130000045084174/?*=R0aM6V2G%2F6zKfZD3OoJi9D%2BIPVJ7InVybCI6InlhLW1haWw6Ly8xNzUwNzc0MzU1MTQwMzA0NzYvMS40IiwidGl0bGUiOiJIUzUyMzIxNy02NS1JTlMtQ1JELTAwMDItMDAwMl8wLnBkZiIsIm5vaWZyYW1lIjpmYWxzZSwidWlkIjoiMTEzMDAwMDA0NTA4NDE3NCIsInRzIjoxNjEzMTA4Njc0MjUzLCJ5dSI6IjIwNTMxMTY3OTE2MTA0NDQyOTcifQ%3D%3D](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fdocviewer.yandex.ru%2Fview%2F1130000045084174%2F%3F*%3DR0aM6V2G%252F6zKfZD3OoJi9D%252BIPVJ7InVybCI6InlhLW1haWw6Ly8xNzUwNzc0MzU1MTQwMzA0NzYvMS40IiwidGl0bGUiOiJIUzUyMzIxNy02NS1JTlMtQ1JELTAwMDItMDAwMl8wLnBkZiIsIm5vaWZyYW1lIjpmYWxzZSwidWlkIjoiMTEzMDAwMDA0NTA4NDE3NCIsInRzIjoxNjEzMTA4Njc0MjUzLCJ5dSI6IjIwNTMxMTY3OTE2MTA0NDQyOTcifQ%253D%253D)
### Comment
> Даже после ручной блокировки реклама появляется снова на том же месте после перезагрузки страницы

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/pVdCGba.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.31
Browser: | Chrome
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Other:</b><br/> Filter unblocking search ads and self-promotion<br/><br/><b>Language-specific:</b><br/> AdGuard Turkish, <br/>AdGuard Russian, <br/>AdGuard Spanish/Portuguese, <br/>AdBlockID

**Comment by stanislav-atr** [comment]
У меня воспроизвелось в таком виде:

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/68852737/108088473-8d657880-7089-11eb-9e8a-90504284a26a.png)
</details><br/>

**Comment by zloyden** [comment]
Не воспроизводится с последней версией экстры. Оригинальную задачу нужно оставить открытой с метками `Problematic`, `Extra` и посоветовать пользователю использовать скрипт / расширение AdGuard Extra.
Также обязательно очистить данные браузера перед его использованием.
<details><summary>Screenshot:</summary>

![ydc1](https://user-images.githubusercontent.com/33488229/108191343-0fa27b00-7124-11eb-955f-074b219bc474.png)

</details><br/>
