### ISSUE TITLE
images.yandex.ru

### ISSUE THREAD

**Issue by stanislav-atr** [AdguardTeam/AdGuardExtra#164]
@adguard-bot commented on [Fri Feb 12 2021](https://github.com/AdguardTeam/AdguardFilters/issues/74720)

### Issue URL (Ads)
 [https://yandex.ru/images/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fyandex.ru%2Fimages%2F)
### Comment
Username: `@skdsa`
> При открытии любой картинки на яндекс картинках внизу картинки вылаит востоянно реклама.
> Расширение Adguard Extra для браузера включено и используется.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/EeI4wxp.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/ywyJ43Y.jpg)
</details>
<details>
  <summary>Screenshot 3</summary>

  ![Screenshot 3](https://reports-img.adguard.com/29tN3VT.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.31
Browser: | Sent Browser Версия 4.3.9.248 (Официальная сборка), (32 бит) (Chromium 86.0.4240.198)
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (), <br>Hide your Referrer from third-parties
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> AdGuard Russian
Other extensions used: | расширение adguard extra Версия 1.0.211

**Comment by stanislav-atr** [comment]
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/68852737/108088715-d6b5c800-7089-11eb-93e3-ca377873b6ef.png)
</details><br/>

**Comment by Alex-302** [comment]
убрал правилом
