### ISSUE TITLE
Kinopoisk

### ISSUE THREAD

**Issue by MaximusPanin** [AdguardTeam/AdGuardExtra#165]
Kinopoisk, a site about cinema from Yandex. Ads are not removed.

https://www.kinopoisk.ru/film/17481/

https://i.gyazo.com/d182c72e8dc4c486e197d1f008fed1ad.png

Operating system:                       | Windows 10
Browser:                                | Cent Browser
AdGuard version:                        | Extra

**Comment by zloyden** [comment]
It was fixed in AdGuard Annoyances, just clear browser data (cache / cookies) and enable it.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/108585712-ecaddc00-735a-11eb-9aac-04bb604b89ff.png)

</details><br/>

**Comment by MaximusPanin** [comment]
I am using **AdGuard Extra 1.0.214** and it doesn't help. Cookies cleaned them.

https://i.gyazo.com/479c7ffd29d7f3605121e3a3d6d33508.png

**Comment by ameshkov** [comment]
@zloyden can we address this in Extra as well? For those who don't use the AdGuard Annoyances filter.
