### ISSUE TITLE
Вновь реклама на Яндексе. реклама на Facebook

### ISSUE THREAD

**Issue by slonopotam-ura** [AdguardTeam/AdGuardExtra#168]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

На yandex.ru снова появилась реклама, а на Facebook она видно постоянно, никогда не исчезала

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screensho
![2021-03-06_12-41-43](https://user-images.githubusercontent.com/75627200/110202517-3843a800-7e7a-11eb-924d-5b4f20e97a5d.png)
![2021-03-06_12-42-58](https://user-images.githubusercontent.com/75627200/110202519-3e398900-7e7a-11eb-81e8-98b7cdcb3965.png)
![2021-03-06_12-45-00](https://user-images.githubusercontent.com/75627200/110202524-41347980-7e7a-11eb-970b-80a0d67e51a0.png)

t_url%)
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                             | Value
---                                     | ---
Operating system:                       | windows 7
Operating system version (Android/iOS)  | ?
Browser:                                | firefox
AdGuard version:                        | 7.42
![2021-03-06_12-41-43](https://user-images.githubusercontent.com/75627200/110202670-51008d80-7e7b-11eb-942a-c50c0059d0a9.png)
![2021-03-06_12-42-58](https://user-images.githubusercontent.com/75627200/110202682-607fd680-7e7b-11eb-9945-e57dc1d82faf.png)
![2021-03-06_12-45-00](https://user-images.githubusercontent.com/75627200/110202686-68d81180-7e7b-11eb-820d-b313b16d8ba9.png)

Filters enabled:                        | ?
Userscript host (AdGuard/Tampermonkey): | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by stanislav-atr** [comment]
@slonopotam-ura, добрый день! Уточните, пожалуйста, на каких именно страницах Яндекса появилась реклама?
