### ISSUE TITLE
Блокировка рекомендуемых постов на Quora.com

### ISSUE THREAD

**Issue by jbionic2016** [AdguardTeam/AdGuardExtra#172]
Добрый день.

На Facebook число рекомендуемых постов уменьшилось (правда изредка ещё мелькают), но  в ленте на Quora.com такое ощущение, что чистку никто ещё даже не начинал. Привожу примеры ниже: 
https://fastpic.ru/fullview/114/2021/0319/74e8a7d8bd1d036e26456b827a45cacd.jpg.html
https://fastpic.ru/fullview/114/2021/0319/79d26e527fafc8651ee63ff73b109e76.jpg.html

Был бы признателен за уборку "шума" из ленты.

Operating system: Windows 10 Home
Browser: Chrome Version 89.0.4389.90 (Official Build) (64-bit)
Version of AdGuard extension for Chrome browser: Version 3.5.31
Filters enabled: AdGuard Base filter, AdGuard Tracking Protection filter, EasyPrivacy, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter
Stealth mode options (Windows only) Enabled
AdGuard Extra 1.0.220

**Comment by zloyden** [comment]
Добрый вечер! Подобные посты и не должны убираться, поскольку не являются рекламой.
Добавление правила в пользовательские должно помочь.

```
quora.com#%#(function(){var observer = new MutationObserver(hide);observer.observe(document, {childList: !0,subtree: !0});function hide() {var e = document.querySelectorAll('div:not([class]):not([tabindex]) > div.q-box');e.forEach(function(e) {var i = e.innerText;if (i) {if (i !== void 0 && (!0 === i.includes('Recommended for you') || !0 === i.includes('you might like'))) {e.style = "display:none!important;"}}})}})();
```

**Comment by jbionic2016** [comment]
Спасибо. А в мобильное приложение Adguard, непремиальное, т.е. без модуля Extra, это правило можно добавить, чтоб оно фильтровало контент сайта Quora при открытии его в мобильном Хроме?

**Comment by zloyden** [comment]
Насколько я помню, у нас нет ограничений для фильтров. Вы можете добавить это правило в пользовательские и оно будет работать для браузеров.

**Comment by jbionic2016** [comment]
Ок. А в старой версии Adguard 2.12, последней которая работает на моем старом планшете на базе Андроид 4.2, это правило тоже сработает?

**Comment by jbionic2016** [comment]
Проверил уже сам. Не сработало :-)
