### ISSUE TITLE
www.kinopoisk.ru is broken

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardExtra#176]
@adguard-bot commented on [Wed Mar 24 2021](https://github.com/AdguardTeam/AdguardFilters/issues/77368#issuecomment-805366080)

### Issue URL (Incorrect Blocking)
 [https://www.kinopoisk.ru/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.kinopoisk.ru%2F)
### Comment
> Белый экран вместо сайта кинопоиск! Научным тыком выяснил что виновато расширение adguard extra в программе adguard. Если отключить adguard extra - сайт работает как надо. Но на других сайтах появляется реклама! Почините пожалуйста!
> --
> Информация ниже сгенерирована автоматически. Не удаляйте ее.
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/assistant/4.3/assistant.user.js
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js
> https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/fUYVJgk.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/fUYVJgk.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.5.3
Browser: | Chrome
AdGuard driver: | WFP
Stealth mode: | disabled
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Other:</b><br/> AdGuard Experimental<br/><br/><b>Language-specific:</b><br/> AdGuard Russian

**Comment by Alex-302** [comment]
Temporary fixed by https://github.com/AdguardTeam/AdguardFilters/commit/8bf9a7d477361930fb9ba6bc28308a38aa8d135d

**Comment by ameshkov** [comment]
Fixed in 1.0.224
