### ISSUE TITLE
https://kurs.com.ua/

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardExtra#2]
@Alex-302 commented on [Tue Jun 18 2019](https://github.com/AdguardTeam/AdguardFilters/issues/35445)

Ads reinsertation script(zmctrack.net). Or redirect to ad.
If ads not loaded, please try to block `zmctrack.net`

Screenshot:

<details>

![image](https://user-images.githubusercontent.com/8361299/59701774-f9317700-91fe-11e9-853c-939145a4ca0d.png)

</details>

and similar ads.

**Comment by Alex-302** [comment]
the same/similar script:
pravda.com.ua https://github.com/AdguardTeam/AdguardFilters/issues/37657
