### ISSUE TITLE
censor.net

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/AdGuardExtra#209]
При клике по значку Помощника он исчезает. После отключения AG Extra помощник начинает функционировать штатно.
https://github.com/AdguardTeam/AdguardFilters/issues/83789

**Comment by stanislav-atr** [comment]
@zubrRB, исправили в  версии Экстры 1.0.268

Сейчас доступна новая версия [Помощника](https://adguard.com/ru/adguard-assistant/overview.html).

**Comment by zloyden** [comment]
Новый помощник можно также установить через меню программы -> настройки -> браузерный помощник, старую версию рекомендуется выключить.

**Comment by zubrRB** [comment]
Да, я про него читал, когда он только появился. Поставил, работает.
