### ISSUE TITLE
auto.ru

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdGuardExtra#21]
https://github.com/AdguardTeam/AdguardFilters/issues/39138

https://auto.ru/moskva/cars/ford/all/
<details><summary>1:</summary>

![image](https://user-images.githubusercontent.com/33488229/63777034-1f545100-c8eb-11e9-86a4-02faac89a83b.png)
</details><br/>

https://auto.ru/cars/used/sale/ford/mondeo/1080196554-742c4dcc/?page_from=page_listing%2Cblock_listing%2Ctype_single
<details><summary>2:</summary>

![2](https://user-images.githubusercontent.com/33488229/63777194-5c204800-c8eb-11e9-95a4-8bd1bcb988ee.png)
</details><br/>

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/42846#issuecomment-549798447

**Comment by zloyden** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/42846#issuecomment-561654462
Есть директ по [этой ссылке](https://auto.ru/catalog/cars/mazda/cx_9/20800889/), рекламу мазды удалось убрать этим скриптлетом `auto.ru#%#//scriptlet('set-constant', 'window.AD2', 'undefined')`, но не отступ сверху.
@tvinzz посмотри у себя.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/70218122-74f29200-1753-11ea-9f80-a06ca75ff04a.png)
</details><br/>
