### ISSUE TITLE
yandex.zen

### ISSUE THREAD

**Issue by Sergey-Lyapin** [AdguardTeam/AdGuardExtra#216]
Реклама под статьёй, повторяется не всегда, попробуйте проверить несколько страниц.

![Screenshot 2021-06-18 at 14 27 39](https://user-images.githubusercontent.com/18536328/122554379-94a19080-d041-11eb-9782-4d469cc4347a.png)

**Comment by zloyden** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/85613#issuecomment-862040902
