### ISSUE TITLE
Scroll settings page down and find "Inject Mode" there - on Safari Tampermonkey port (M1 Mac) ?

### ISSUE THREAD

**Issue by enr00ted** [AdguardTeam/AdGuardExtra#221]
I tried to install this on Safari with the official Tampermonkey for M1 Macs, but not sure it really works or does anything. I can't find the inject mode on this build.

https://www.tampermonkey.net

**Comment by Sergey-Lyapin** [comment]
Hello, @enr00ted
Did you changed config mode to advanced?

For example the script must remove ads (sticky ad at the right and above the comments) here:
https://zen.yandex.ru/media/muph/projil-2-dnia-na-zapovednom-kordone-v-kalmyckoi-stepi-i-sbejal-a-liudi-tam-jivut-i-rabotaiut-pokazyvaiu-kak-60b61d8f5705305531cc0fe7

**Comment by enr00ted** [comment]
There is no such option for this last build of Tampermonkey for Safari. And no it does not work, those ads are still present.

![Captura de pantalla 2021-07-16 a las 20 18 39](https://user-images.githubusercontent.com/3756926/125991817-500c1a1d-a576-4019-99fb-ffab2309a787.png)
![Captura de pantalla 2021-07-16 a las 20 18 29](https://user-images.githubusercontent.com/3756926/125991820-984fb9a6-4a00-4dd4-aa65-b496bf785572.png)
![Captura de pantalla 2021-07-16 a las 20 18 14](https://user-images.githubusercontent.com/3756926/125991822-b760d597-2320-4b3e-a6f0-0a82e65b6339.png)
![Captura de pantalla 2021-07-16 a las 20 17 53](https://user-images.githubusercontent.com/3756926/125991825-325ba9f0-9c3e-44c1-9bb4-5f83901d7e75.png)

![Captura de pantalla 2021-07-16 a las 19 56 56](https://user-images.githubusercontent.com/3756926/125991833-68a38637-549a-4ad1-9d25-99340ca4b793.png)

**Comment by ameshkov** [comment]
I doubt Tampermonkey for Safari is technically capable to provide this, the userscript will run too late and there's no way around.
