### ISSUE TITLE
Yandex.news content blocking

### ISSUE THREAD

**Issue by stanislav-atr** [AdguardTeam/AdGuardExtra#224]
On rare occasions multiple clicking on "Новости" button breaks the website. There is newly added to many element stying of `[class="root123"]` with `[style="display: none !important"]` wich has the source of, most probably, page's script, as it is absent from stylesheets.
https://yandex.ru/news?from=tabbar
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/68852737/125995991-6d0789f0-fae1-41da-9a97-04a281caea6e.png)</details><br/>

P.S. i have some problems reproducing the issue, @zloyden, @Sergey-Lyapin, @Alex-302, could you please try reproducing it with AG Extra `Release: 1.0.285`?

**Comment by zloyden** [comment]
I've seen this once with `AdGuard Extra 1.0.285`, but It's hard to reproduce this now
