### ISSUE TITLE
Блокировка личных сообщений на Yula

### ISSUE THREAD

**Issue by MaximusPanin** [AdguardTeam/AdGuardExtra#231]
Блокировка личных сообщений на сайте объявлений Yula. Идет вечная загрузка.

https://i.gyazo.com/400d7db6c6a498697070164ec2273ab7.png

**Operating system:**                       | Windows 10 64
**Browser:**                                | Cent Browser 4.3.9.248 (Chromium 86.0.4240.198)
**AdGuard version:**                        | AdGuard Extra 1.0.286
**Userscript host (AdGuard/Tampermonkey): |** Off

**Comment by stanislav-atr** [comment]
@ MaximusPanin, добрый день! На данный момент AdGuard Extra не применяется на youla.ru. 

<details><summary>Screenshot:</summary>

![screen](https://user-images.githubusercontent.com/68852737/128728583-94849ab0-0258-498f-8fb7-203ec9fed1a8.jpg)
</details><br/>


Предоставьте, пожалуйста, свои настройки фильтров и пользовательские правила (если имеются).

**Comment by MaximusPanin** [comment]
Здравствуйте.
Буду копать в uBO. Просто первоначально, я отключил только AdGuard Extra, перезагрузил страницу и переписка появилась. Возможно сбой. Так же было и на Ozon. В поддержке uBO посоветовали обновить принудительно фильтр EasyPrivacy. Обновил, пока работает нормально.
