### ISSUE TITLE
drive2.ru

### ISSUE THREAD

**Issue by Sergey-Lyapin** [AdguardTeam/AdGuardExtra#234]
https://www.drive2.ru/market/offers/1100736?yrwinfo=1628589616533952-63476562548662825500489-prestable-app-host-sas-web-yp-196
![drive2](https://user-images.githubusercontent.com/18536328/128849904-b097f1de-5bce-4117-9c8c-2e06e15b2299.png)

**Comment by stanislav-atr** [comment]
Эти рекламные вставки можно убрать только вместе со всем блоком, остались еще с прошлых разов. @zloyden

**Comment by zloyden** [comment]
Весь блок убирать это не вариант, там есть полезные элементы.
