### ISSUE TITLE
Ads: ppss.kr [ Ad-Shield ]

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/AdGuardExtra#237]
### URLs
https://ppss.kr/archives/243458
https://ppss.kr/

### Screenshots
![scer33](https://user-images.githubusercontent.com/37463155/129228920-4760af2b-02f8-46e9-8095-3a74316f97a6.png)
![scre22](https://user-images.githubusercontent.com/37463155/129228940-01e4f367-5f14-443b-8f3d-4d3945632471.png)

### Related Issues
https://github.com/AdguardTeam/AdGuardExtra/issues/236
https://github.com/AdguardTeam/AdguardFilters/issues/87725

### Related Source
https://docs.ad-shield.io/f471f497-e0c1-4659-8341-6a44bb2e448d ([Google Translate](https://translate.google.com/translate?hl=&sl=ko&tl=en&u=https%3A%2F%2Fdocs.ad-shield.io%2Ff471f497-e0c1-4659-8341-6a44bb2e448d))

### Environment
Mozilla Firefox Developers Edition 92.0b2

**Comment by JobcenterTycoon** [comment]
They also take a fingerprint of the browser (audio, canvas, domRect and a lot of navigator stuff like browser/version, useragent, cpu, screen etc.) and sending a hash to the host via random xhr requests. They also detect some Adblock filter lists (include old one like adBlockWarningRemoval and geobased filter lists). The tracking script is on top of the page and not base64 encoded

<img width="232" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/129231524-601e7c71-295d-4b54-8d62-6622802c245e.PNG">

this need to be blocked too

**Comment by Alex-302** [comment]
@stanislav-atr Ping.

+

https://github.com/AdguardTeam/AdguardFilters/issues/87725#issuecomment-903277521
