### ISSUE TITLE
yandex turbo

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardExtra#25]
https://yandex.ru/turbo?d=1&text=https%3A%2F%2Fwww.sport-express.ru%2Ffootball%2Fchampions-league%2Fnews%2Fstalo-izvestno-raspisanie-matchey-zenita-v-lige-chempionov-1580616%2F

![](https://uploads.adguard.com/up04_pnlf8_Stalo_izvestno_raspisanie_matchei_Zenita_vLige_chempionov.png)

**Comment by ameshkov** [comment]
@tvinzz before doing anything else, try this rule: `yandex.ru##.page__content [id^="R-A-"]`

Also, here's a rule for the tracking protection filiter list:
`||yastatic.net/s3/distribution/yanalytics/yanalytics.js`

**Comment by tvinzz** [comment]
https://github.com/AdguardTeam/AdguardFilters/pull/39636
