### ISSUE TITLE
pussyspace.net [NSFW]

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdGuardExtra#255]
Реклама на скриншотах ниже и также нужно убрать кликандер. Чтобы его повторить открой ссылку ниже и перейди по видео из колонки `Related`.
У сайта есть зеркало, так что скрипт должен включать `pussyspace.net` и `pussyspace.com`.

https://www.pussyspace.net/vid-3752799-indian-cutie-playing-with-toy-call-8820674990-for-sex-toy-loveteaser-in/
<details><summary>Screenshots [NSFW]:</summary>

https://user-images.githubusercontent.com/33488229/135772222-5c5056da-6e80-4682-bc40-e7a175fc5380.png
https://user-images.githubusercontent.com/33488229/135772245-cdd09940-cb49-4989-bb48-54513b8488c6.png
https://user-images.githubusercontent.com/33488229/135772316-8a6e0bc3-a64a-40cd-8e27-251b96be8a86.png

</details><br/>

**Comment by Yuki2718** [comment]
Needs update.
