### ISSUE TITLE
Incorrect Blocking: Ad-Shield

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/AdGuardExtra#258]
## Summary
On AdGuard Extra 1.0.317 (Tampermonkey), the content of websites are blocked incorrectly because AdGuard Extra is detected.

<details>
<summary>Click to show console log</summary>

![psskr_oncon](https://user-images.githubusercontent.com/37463155/137094532-874b2714-1fe4-44de-935b-2cd85d95a9d5.png)
![ygosu_oncon](https://user-images.githubusercontent.com/37463155/137094558-c1f86f8a-bbdd-4198-8bb3-594d06a33f1d.png)

</details>

### URLs
https://ygosu.com/
https://ygosu.com/community/real_article/yeobgi/1863184/?frombest=Y

### Screenshots (When enabled)
<details>
<summary>Click to show screenshots</summary>

![ygosupost_on](https://user-images.githubusercontent.com/37463155/137097013-3fee64fd-f42e-4fce-8607-31646d4467a4.png)

</details>

### Screenshots (When disabled)
<details>
<summary>Click to show screenshots</summary>

![ygosumain_off](https://user-images.githubusercontent.com/37463155/137097055-e2b4cb8a-0d82-46a8-a907-c5714d05a3e2.png)
![ygosupost_off](https://user-images.githubusercontent.com/37463155/137097083-a8637367-1bc7-48a8-9e47-05638a45264e.png)

</details>

### URLs
https://ppss.kr/
https://ppss.kr/archives/240740

### Screenshots (When enabled)
<details>
<summary>Click to show screenshots</summary>

![ppsskrarticle_on](https://user-images.githubusercontent.com/37463155/137096057-06f6b19d-ccc2-4ca1-a2c4-eb8fa14ce830.png)
![ppsskrmain_on](https://user-images.githubusercontent.com/37463155/137096067-5172a20e-b194-40c1-b5a7-40bc350cbe13.png)

</details>

### Screenshots (When disabled)
<details>
<summary>Click to show screenshots</summary>

![ppsskrarticle_off](https://user-images.githubusercontent.com/37463155/137095997-016f0f4a-05f9-4dac-9b9d-71296f2d5403.png)
![ppsskrmain_off](https://user-images.githubusercontent.com/37463155/137096041-1b5dcc23-3517-473e-a7ce-0d8077dd365f.png)

</details>

---
https://github.com/AdguardTeam/AdguardFilters/issues/87725
https://github.com/AdguardTeam/AdguardFilters/issues/90634
https://github.com/List-KR/List-KR/issues/202#issuecomment-941979543

**Comment by ameshkov** [comment]
@zloyden same issue with AG for Win/Mac.

**Comment by zloyden** [comment]
Hi! We solved the incorrect blocking in the `AdGuard Extra 1.0.320`, but you'll see ads for now. We'll fix them later.
