### ISSUE TITLE
docviewer.yandex.com.tr Broken

### ISSUE THREAD

**Issue by muhasturk** [AdguardTeam/AdGuardExtra#259]
[Link](https://docviewer.yandex.com.tr/view/0/?*=9iWTz%2FpFaKeHqfaLEiY2vgnABAh7InVybCI6InlhLWRpc2stcHVibGljOi8vc0NRTXJTYkptdUFjZktXMGptbTA5RnVzL1J6MWpEQzBvQzFtUWJxWlZIcVcrVENjTk9tUjFjK0VMdEVLTVAxZXEvSjZicG1SeU9Kb25UM1ZvWG5EYWc9PSIsInRpdGxlIjoiMjAyMTcyNzkzMDM3OTA2X0NVUFJBX0ZPUk1FTlRPUl8wNl8yMV9UUi5wZGYiLCJub2lmcmFtZSI6ZmFsc2UsInVpZCI6IjAiLCJ0cyI6MTYzNDQyMTU2NTk3OSwieXUiOiI1MzczNzcwNTE2MzQ0MjE1NjAifQ%3D%3D)

# Direct ad showing
![image](https://user-images.githubusercontent.com/4077401/137603125-11d43dd8-2ce1-493f-8926-97daadd537b5.png)

Information                             | Value
---                                     | ---
Operating system:                       | Windows 10 
Browser:                                | Microsoft Edge Version 94.0.992.50 (Official build) (64-bit)
Extension | Version: 1 . 0 . 3 1 7

**Comment by stanislav-atr** [comment]
@ muhasturk, Hi! Sorry for the delay but is the problem is still there for you? Not reproduced with Edge and 3.0.322 Extra on my side.
