### ISSUE TITLE
u-news.com.ua

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardExtra#260]
https://u-news.com.ua/
ads

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/137984359-484e30f1-ecf9-46e3-9e40-65940c6389af.png)

</details>

Chrome 94.0.4606.81, Extra Ext. 1.0.320

**Comment by stanislav-atr** [comment]
Fixed in filters.
