### ISSUE TITLE
kurs.com.ua [Ads]

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardExtra#268]
### Issue URL (Ads)
 [https://kurs.com.ua/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fkurs.com.ua%2F)
### Comment
> Версия Chrome Linux 95.0.4638.69 (Официальная сборка), (64 бит)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/TAWH2ST.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.6.14
Browser: | Chrome
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Block WebRTC, <br>Hide your Referrer from third-parties
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Other:</b><br/>Filter unblocking search ads and self-promotion<br/><br/><b>Language-specific:</b><br/>AdGuard Russian
Other extensions used: | Всё отключил!

**Comment by stanislav-atr** [comment]
Blockerd by Russian filters atm.
