### ISSUE TITLE
mail.ukr.net [Ads]

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardExtra#272]
@adguard-bot commented on [Sat Nov 13 2021](https://github.com/AdguardTeam/AdguardFilters/issues/99952)

### Issue URL (Ads)
 [https://mail.ukr.net/desktop#msglist/funread/p0](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fmail.ukr.net%2Fdesktop%23msglist%2Ffunread%2Fp0)
### Comment
Username: @VolodymyrMaestro
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/5fLYGqT.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.6.14
Browser: | Opera
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Self-destructing third-party cookies (2880), <br>Block WebRTC, <br>Hide your Referrer from third-parties
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads, <br/>EasyList, <br/>Peter Lowe's Blocklist<br/><br/><b>Privacy:</b><br/>AdGuard URL Tracking, <br/>AdGuard Tracking Protection, <br/>EasyPrivacy, <br/>Legitimate URL Shortener, <br/>Fanboy's Enhanced Tracking List, <br/>Fanboy's Anti-Facebook List, <br/>Fanboy's Anti-thirdparty Fonts<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media, <br/>Fanboy's Social Blocking List<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances, <br/>Fanboy's Annoyances, <br/>Web Annoyances Ultralist, <br/>Adblock Warning Removal List, <br/>I don't care about cookies, <br/>EasyList Cookie List, <br/>Dandelion Sprout's Annoyances List<br/><br/><b>Security:</b><br/>Online Malicious URL Blocklist, <br/>Spam404, <br/>NoCoin Filter List<br/><br/><b>Other:</b><br/>AdGuard DNS, <br/>BarbBlock<br/><br/><b>Language-specific:</b><br/>AdGuard Russian, <br/>RU AdList: Counters, <br/>CJX's Annoyances List, <br/>KAD - Anti-Scam

**Comment by stanislav-atr** [comment]
Triggered by DNS filter.
