### ISSUE TITLE
m.ygosu.com

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardExtra#273]
@adguard-bot commented on [Thu Nov 18 2021](https://github.com/AdguardTeam/AdguardFilters/issues/100491)

### Issue URL (Ads)
 [https://m.ygosu.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fm.ygosu.com%2F)
### Comment
> ad banner in mobile page
Ad-Shield

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/Fq84XXs.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.7.2
Browser: | Firefox
AdGuard driver: | WFP
Stealth mode: | disabled
DNS filtering: | server: `quic://dns.adguard.com`<br>filters: `User rules`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>Fanboy's Enhanced Tracking List, <br/>AdGuard Tracking Protection<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>EasyList China, <br/>List-KR, <br/>YousList, <br/>AdGuard Japanese
Userscripts: | disabled

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/AdGuardExtra/issues/258
