### ISSUE TITLE
auto.ru [Incorrect Blocking]

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardExtra#274]
@adguard-bot commented on [Sat Nov 27 2021](https://github.com/AdguardTeam/AdguardFilters/issues/101409)

### Issue URL (Incorrect Blocking)
 [https://auto.ru/bus/all/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fauto.ru%2Fbus%2Fall%2F)
### Comment
Username: @lolafur
> Загрузка сайта очень сильно тормозит, не прогружаются изображения, иногда дело доходит до подвисания самой страницы. Проблему сам Adguard не может решить уже долго время по не понятным причинам.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/MCQfseF.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/ewGCf7h.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.6.16
Browser: | Vivaldi
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (), <br>Hide your Referrer from third-parties
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection, <br/>AdGuard URL Tracking, <br/>EasyPrivacy<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Security:</b><br/>Online Malicious URL Blocklist<br/><br/><b>Language-specific:</b><br/>AdGuard Russian, <br/>RU AdList: Counters

---

@lolafur commented on [Sat Nov 27 2021](https://github.com/AdguardTeam/AdguardFilters/issues/101409#issuecomment-980776068)

На сколько я понял, данная проблема наблюдается из-за Adguard Extra, потому как отключивши его, у меня все стало нормально грузиться, без подвисаний. А теперь вопрос: стоит ли разработчикам дальше делать Adguard Extra, если он приносит столько проблем? Думаю, что не стоит, так как именно Adguard Extra ломает загрузку страниц через колено. Скорее всего, расширение было сделано как костыль к основному, но костыль вышел неудачным, поэтому пора задуматься.

**Comment by Alex-302** [comment]
У меня начинает тормозить загрузка изображений после нескольких переходов.

**Comment by stanislav-atr** [comment]
@Alex-302, @lolafur, на моем устройстве в Chrome и Vivaldi не воспроизводятся лаги на странице, попробуйте отключить сторонние (не-AG) фильтры. Какие расширения установлены, помимо AdGuard и Экстры?

**Comment by Alex-302** [comment]
Всё повторяется, с нашими фильтрами и экстрой.
