### ISSUE TITLE
Ломается поиск на yandex.ru/pogoda

### ISSUE THREAD

**Issue by DridgerVE** [AdguardTeam/AdGuardExtra#279]
***Description***:
* **Current behaviour**: 
<details><summary>Screenshot:</summary>

![image](https://i.postimg.cc/pXtL8xDZ/2021-12-20-14-19-28.png)
</details><br/>

* **Expected behaviour**: 

<details><summary>Screenshot:</summary>

![image](https://i.postimg.cc/RZSCsRpJ/2021-12-20-14-18-17.png)
</details><br/>

***Steps to reproduce the problem***:
Необходимо зайти на yandex.ru/pogoda c включенным AdGuard и начать набирать название населенного пункта в поиске

Вероятно, дело в следующем правиле
<details><summary>Screenshot:</summary>

![image](https://i.postimg.cc/MTYT9F04/2021-12-20-14-59-55.png)
</details><br/>

***System configuration***

**Filters:**
Базовый фильтр AdGuard, Фильтр полезной рекламы, Русский фильтр 

Information                             | Value
---                                     | ---
Operating system:                       | macOs 
Operating system version (Android/iOS)  | Mojave 10.14.6
Browser:                                | Google Chrome Версия 96.0.4664.110
AdGuard version:                        | 3.6.16
Filters enabled:                        | Базовый фильтр AdGuard, Фильтр полезной рекламы, Русский фильтр  
Userscript host (AdGuard/Tampermonkey): | -

**Comment by zloyden** [comment]
@DridgerVE в фильтрах была данная проблема, уже поправили - нужно через пару часов проверить обновление фильтров в программе.
