### ISSUE TITLE
yandex.ru

### ISSUE THREAD

**Issue by tvinzz** [AdguardTeam/AdGuardExtra#28]
The element with banner under the search form has `background-image` url starts from `https://yastatic.net/www/_/`

<details>
  <summary>Screenshot</summary>
  
 ![image](https://user-images.githubusercontent.com/15062885/65003465-435eed00-d901-11e9-8f5a-540261edc499.png)
</details>

**Comment by Alex-302** [comment]
Ad in Zen block 
![image](https://user-images.githubusercontent.com/8361299/66235028-d36da680-e6f7-11e9-8b7e-b8dfcb624ce8.png)
