### ISSUE TITLE
www.drive2.ru [Ads]

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardExtra#284]
@adguard-bot commented on [Sun Dec 26 2021](https://github.com/AdguardTeam/AdguardFilters/issues/104583)

### Issue URL (Ads)
 [https://www.drive2.ru/l/526486025749401392/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.drive2.ru%2Fl%2F526486025749401392%2F)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/X2XyMOB.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.6.17
Browser: | Chrome
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Hide your Referrer from third-parties
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads, <br/>Peter Lowe's Blocklist<br/><br/><b>Privacy:</b><br/>AdGuard URL Tracking, <br/>AdGuard Tracking Protection, <br/>EasyPrivacy, <br/>Legitimate URL Shortener<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances, <br/>Web Annoyances Ultralist, <br/>Adblock Warning Removal List<br/><br/><b>Security:</b><br/>Online Malicious URL Blocklist, <br/>NoCoin Filter List<br/><br/><b>Other:</b><br/>Filter unblocking search ads and self-promotion<br/><br/><b>Language-specific:</b><br/>AdGuard Russian

---

@adguard-bot commented on [Thu Dec 30 2021](https://github.com/AdguardTeam/AdguardFilters/issues/104583#issuecomment-1002862805)

### Issue URL (Incorrect Blocking)
 [https://www.drive2.ru/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.drive2.ru%2F)
### Comment
> Без блокировки рекламы в нижней части появляются банеры. С блокировщиком их нет, но при нажатии на выделенном блоке переходит по рекламным баннерам!! 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/mDXb2cg.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/yBa36y4.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.8
Browser: | Yandex
AdGuard driver: | WFP
Stealth mode: | disabled
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Russian
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js,<br>https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js

---

@adguard-bot commented on [Thu Dec 30 2021](https://github.com/AdguardTeam/AdguardFilters/issues/104583#issuecomment-1002881390)

### Issue URL (Ads)
 [https://www.drive2.ru/b/1158262/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.drive2.ru%2Fb%2F1158262%2F)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/tzZ4OZb.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.6.17
Browser: | Firefox
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Self-destructing third-party cookies (2880), <br>Hide your Referrer from third-parties
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard URL Tracking, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances, <br/>Web Annoyances Ultralist, <br/>Adblock Warning Removal List, <br/>I don't care about cookies<br/><br/><b>Language-specific:</b><br/>AdGuard Russian, <br/>AdGuard Japanese, <br/>Bulgarian list, <br/>AdBlockID, <br/>Dandelion Sprout's Nordic Filters

---

@adguard-bot commented on [Thu Dec 30 2021](https://github.com/AdguardTeam/AdguardFilters/issues/104583#issuecomment-1003151734)

### Issue URL (Ads)
 [https://www.drive2.ru/l/606989243478204339/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.drive2.ru%2Fl%2F606989243478204339%2F)
### Comment
> Пропускает рекламу Яндекса, не обновляются после обновления на 4.3.0 и 4.3.1. Исправьте пожалуйста!

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/0KMaNcX.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/V1jSest.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard/AdGuard Pro for iOS v4.3.1
Browser: | Safari
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Language-specific:</b><br/>AdGuard Russian

---

@adguard-bot commented on [Fri Dec 31 2021](https://github.com/AdguardTeam/AdguardFilters/issues/104583#issuecomment-1003267968)

### Issue URL (Ads)
 [https://www.drive2.ru/l/3912725/?page=0#comments](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.drive2.ru%2Fl%2F3912725%2F%3Fpage%3D0%23comments)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/k99D5Bv.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.6.17
Browser: | Firefox
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Self-destructing third-party cookies (2880), <br>Hide your Referrer from third-parties
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard URL Tracking, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances, <br/>Web Annoyances Ultralist, <br/>Adblock Warning Removal List, <br/>I don't care about cookies<br/><br/><b>Language-specific:</b><br/>AdGuard Russian, <br/>AdGuard Japanese, <br/>Bulgarian list, <br/>AdBlockID, <br/>Dandelion Sprout's Nordic Filters

**Comment by Alex-302** [comment]
Reproduced with app only.

**Comment by stanislav-atr** [comment]
Not reproduced with userconfig for desktop AG issue.
