### ISSUE TITLE
e.mail.ru [Incorrect blocking]

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdGuardExtra#290]
https://github.com/AdguardTeam/AdguardFilters/issues/102917#issuecomment-1014829288
https://github.com/AdguardTeam/AdguardFilters/issues/102917#issuecomment-1014913752
I can't reproduce it on my end, but @First-j has had it with AdGuard Extra enabled.
@stanislav-atr please take a look.

**Comment by First-j** [comment]
Почему закрыли, если проблема не решена?

**Comment by stanislav-atr** [comment]
Было исправлено в AdGuard Extra 1.0.357 - проверьте обновление фильтров в программе.
