### ISSUE TITLE
finance.rambler.ru [Incorrect Blocking]

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardExtra#292]
@adguard-bot commented on [Sun Jan 16 2022](https://github.com/AdguardTeam/AdguardFilters/issues/106997)

### Issue URL (Incorrect Blocking)
 [https://finance.rambler.ru/economics/47947060-kovarnyy-plan-raskryt-rossiya-i-ssha-byli-v-sgovore-po-severnomu-potoku-2/?utm_source=head&utm_campaign=self_promo&utm_medium=news&utm_content=news](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Ffinance.rambler.ru%2Feconomics%2F47947060-kovarnyy-plan-raskryt-rossiya-i-ssha-byli-v-sgovore-po-severnomu-potoku-2%2F%3Futm_source%3Dhead%26utm_campaign%3Dself_promo%26utm_medium%3Dnews%26utm_content%3Dnews)
### Comment
> Новости на главной странице в Рамблере не открываются в 70% случаях, но если выключить адгуард, то открываются все новости. Это уже 3 неделю продолжается. Как это исправить?

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/k6vnS4i.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/vAFrScD.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 11
AdGuard product: | AdGuard for Android v3.6.6 (38)
Browser: | Chrome
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode options: | Self-destructing third-party cookies (0)
DNS filtering: | server: `System`<br>filters: `https://filters.adtidy.org/android/filters/15_optimized.txt`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Russian
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js
Other extensions used: | Касперский интернет секьюрити

**Comment by stanislav-atr** [comment]
Breakage due to mobile fitlers on android tablet with desktop website layout, fixed in filters.
