### ISSUE TITLE
otvet.mail.ru [Ads]

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardExtra#296]
@adguard-bot commented on [Wed Jan 26 2022](https://github.com/AdguardTeam/AdguardFilters/issues/105098#issuecomment-1021915542)

### Issue URL (Ads)
 [https://otvet.mail.ru/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fotvet.mail.ru%2F)
### Comment
> Чистил кеш, отключал защиту фаерфокс.Толку нет. На роутере используются ваши днс, в браузере ваши расширения ( обычное и экстра).Толку нет, реклама лезет..

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/XltYBHz.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.6.17
Browser: | Firefox
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Self-destructing third-party cookies (2880), <br>Block WebRTC, <br>Hide your Referrer from third-parties
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard URL Tracking, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Russian, <br/>RU AdList: Counters
Other extensions used: | AdGuard Extra. Стандартная защита фаерфокса от слежения.

---

@Alex-302 commented on [Wed Jan 26 2022](https://github.com/AdguardTeam/AdguardFilters/issues/105098#issuecomment-1022244673)

Повторил.

**Comment by Alex-302** [comment]
@stanislav-atr  В Фоксе повторяется.

**Comment by stanislav-atr** [comment]
This particular issue is related to Firefox not updating Extra, temporary solution would be to use beta version.
