### ISSUE TITLE
Rules of 3 seconds timer for ad video.

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardExtra#3]
@lancelot-moon commented on [Tue Apr 02 2019](https://github.com/AdguardTeam/AdguardFilters/issues/31966)

@AdamWr 
@Alex-302 

https://jspenguin2017.github.io/uBlockProtector/

Nano Defender + Nano Adblocker have rules of 3 seconds timer for ad video.
Ex: The original ad video takes 30 seconds.
But it will only take 3 seconds with Nano.

https://chrome.google.com/webstore/detail/nano-defender/ggolfgbegefeeoocgjbmkembbncoadlb

https://chrome.google.com/webstore/detail/nano-adblocker/gabbbocakeomblphkmmnoamkioajlkfo

https://github.com/AdguardTeam/AdguardFilters/issues/18815#issuecomment-468868509

It seems that AG filter devs can't make rules for skipping its ad videos.
https://ani.gamer.com.tw/

With AG, need to wait for 30 sec until the countdown of ad video ends.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/IGr6MVD.png)
</details><br/>

With Nano, only take 3 sec.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/8T6iI6K.png)
</details><br/>

At least, may you make rules/scripts of 3 seconds timer for ad video such like Nano?
Thanks.

---

@lancelot-moon commented on [Sun Apr 07 2019](https://github.com/AdguardTeam/AdguardFilters/issues/31966#issuecomment-480551414)

I found this though it can't skip ad video on https://ani.gamer.com.tw/.
https://adsbypasser.github.io/

**Comment by lancelot-moon** [comment]
On PC, nano's 3 sec timer can work.

When Nano in mobile browsers, Nano's 3 sec timer will cause video can't be loaded.
Black screen.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/6VWCLGH.png)
</details><br/>

Desktop mode in mobile browser.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/FOieu4w.png)
</details><br/>

**Comment by AdamWr** [comment]
Users are reporting that AdGuard Extra breaks video player on [https://ani.gamer.com.tw/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fani.gamer.com.tw%2F)

https://github.com/AdguardTeam/AdguardFilters/issues/30059#issuecomment-633970434

**Comment by lancelot-moon** [comment]
Other users reported that the zone of comments is incorrectly blocked.
But I don't have the above issue.
What I meet is failed loading of video.
You need a Taiwan IP for testing the anime website.

**Comment by lancelot-moon** [comment]
3-sec timer had been invalid for the anime website, and it caused the web video can't load anime.
https://github.com/NanoAdblocker/NanoFilters/issues/280

Nano removed 3-sec timer script one year ago.
Do you know?

Older version of AdGuard Extra didn't break video player on https://ani.gamer.com.tw/.

**Comment by ameshkov** [comment]
@tvinzz is the change that fixes this already deployed to beta?

**Comment by lancelot-moon** [comment]
Hi,
I just try AG Extra v1.0.121 and successfully play anime.
Thanks.

**Comment by lancelot-moon** [comment]
Sorry, failed again.
https://ani.gamer.com.tw/animeVideo.php?sn=15564
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/xjHBfi4.png)
</details><br/>

**Comment by lancelot-moon** [comment]
Try this with Taiwan ip.
https://ani.gamer.com.tw/animeVideo.php?sn=15762

Failed loading after 5-sec video ads.

**Comment by lancelot-moon** [comment]
Maybe need to also unblock them at least.
@@||securepubads.g.doubleclick.net/gpt/*$domain=ani.gamer.com.tw
@@||googletagservices.com/tag/js/gpt.js$domain=ani.gamer.com.tw
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$domain=ani.gamer.com.tw

Full path:
https://securepubads.g.doubleclick.net/gpt/pubads_impl_2020070801.js

**Comment by tvinzz** [comment]
@lancelot-moon , does it work with the rule for the moment?

**Comment by lancelot-moon** [comment]
@tvinzz 

The new rule is for solving incorrect blocking without AG Extra.
With AG Extra, I had said AG Extra must be disabled for normally playing videos anyway.

**Comment by lancelot-moon** [comment]
@ameshkov 
This isn't solved.
5-sec timer causes failed loading of video.
Need to disable AG Extra.

**Comment by lancelot-moon** [comment]
@ameshkov 
This is never solved.
Why was it closed?

**Comment by ameshkov** [comment]
Moved to https://github.com/AdguardTeam/AdGuardExtra/issues/166
