### ISSUE TITLE
Extra Support for Twitch.tv

### ISSUE THREAD

**Issue by oliverthedeveloper** [AdguardTeam/AdGuardExtra#305]
Everyone need Extra to block those minutes long ads on Twitch.

Had 3+ today.

If need be, I'll add link for the site of the streamer, where I experienced it.
Just let me know.

**Comment by alturic** [comment]
Using Chrome extension there are still ads on Twitch.

**Comment by oliverthedeveloper** [comment]
> Using Chrome extension there are still ads on Twitch.
> 
> Trying the Tampermonkey script now, will report back.
> 
> Edit: Seems like when an ad is supposed to play it pauses the stream. If you hit play, it plays the stream again.

Still an issue?

**Comment by oliverthedeveloper** [comment]
> @oliverthedeveloper, hi! Extra is already covering Twitch ads. Could you please specify they way you use Extra (tampermonkey script, Extra extension, desktop AG)?

Like this
![image](https://user-images.githubusercontent.com/40898841/176043970-133c4df3-356b-4b34-ae48-389f2a5b1391.png)
![image](https://user-images.githubusercontent.com/40898841/176044061-5e3c6ffc-55b5-4881-b9fa-aa406c83a955.png)

Hope it helps, or be sure to ask again! :=)

**Comment by oliverthedeveloper** [comment]
> Hi! Can you provide a link where you get this? What browser and AdGuard Extra (extension or script) have you used? Now I can not reproduce it, but @stanislav-atr will also take a look at this.

I feel bad, for not seeing this. Can't bloody remember. Sorry 🥵

**Comment by stanislav-atr** [comment]
@oliverthedeveloper, hi! Is the problem still reproducible? If so, make sure you use TamperMonkey with injecting mode `instant` at Settings > Advanced > Experimental
