### ISSUE TITLE
yandex.ru/maps - ads

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardExtra#306]
### Issue URL (Ads)
 [https://yandex.ru/maps/2/saint-petersburg/?ll=30.315635%2C59.938951&z=11](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fyandex.ru%2Fmaps%2F2%2Fsaint-petersburg%2F%3Fll%3D30.315635%252C59.938951%26z%3D11)
### Comment
Username: `@rakleed`
> Реклама появляется при первой загрузке; при перезагрузке страницы уде не отображается реклама

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/4vXI1MA.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Mac v2.7.0.1094 release
Browser: | Chrome
Stealth mode options: | Hide your search queries, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Block third-party Authorization header, <br>Disable cache for third-party requests, <br>Hide your Referrer from third-parties (), <br>Hide your User-Agent ()
DNS filtering: | server: `https://dns-unfiltered.adguard.com/dns-query`<br>
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection, <br/>AdGuard URL Tracking<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Russian
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js

_Originally posted by @adguard-bot in https://github.com/AdguardTeam/AdguardFilters/issues/106172#issuecomment-1023208938_

**Comment by rakleed** [comment]
Сохранённую страницу отправил на devteam@adguard.com, так как похоже сохранились личные данные

**Comment by rakleed** [comment]
@stanislav-atr

**Comment by rakleed** [comment]
@adguard-bot @ameshkov

**Comment by stanislav-atr** [comment]
@rakleed, добрый день! Проблема еще актуальна? Extra 1.0.373 + AdGuard for Mac nigtly 2.7.1.1113 баннеров нет и верстка страницы сильно отличается от сохраненной. С какими IP осуществлялся вход на страницу?

**Comment by rakleed** [comment]
Очистил кэш. Но как я и ранее сообщал...

> Реклама появляется при первой загрузке; при перезагрузке страницы уже не отображается реклама

И при первой загрузке страницы раз в 2-3 дня появляется реклама. Если получится через 2-3 дня воспроизвести, то мне опять прислать вам сохранённую страницу?

**Comment by stanislav-atr** [comment]
@rakleed, какая версия экстры установлена в AdGuard for Mac? Попробуйте обновить его, нажав "Переустановить"
![image](https://user-images.githubusercontent.com/68852737/158419176-a4576d62-9661-426b-a428-98fa6cec20b2.png)

**Comment by rakleed** [comment]
После очистки кэша и переустановки Extra, проблема больше не воспроизводится. Если всё же смогу воспроизвести, то напишу.

**Comment by rakleed** [comment]
@stanislav-atr опять смог воспроизвести проблему. Сохранённую страницу отправил на devteam@adguard.com с указанием этой issue.

На данный момент установлен Extra v. 1.0.376.

**Comment by stanislav-atr** [comment]
@rakleed, получилось один раз воспроизвести, попробуйте эту версию экстры(файл из архива добавить в программе):
[adguard-extra.user.js.zip](https://github.com/AdguardTeam/AdGuardExtra/files/8380494/adguard-extra.user.js.zip)
 
Если работает, то добавим в релиз.

**Comment by rakleed** [comment]
@stanislav-atr установил вчера вашу Dev версию, и реклама не появлялась. Но сегодня при построении маршрута реклама опять появилась. На devteam@adguard.com отправил сохранённую копию страницы, а ниже скриншот с кодом элемента.

<details><summary>Скриншот</summary>

![image](https://user-images.githubusercontent.com/19418601/161073302-9fa87993-3877-4577-85c0-620104b6632b.png)

</details>

**Comment by stanislav-atr** [comment]
@rakleed, добавил этот вариант верстки:
[adguard-extra.user.js.zip](https://github.com/AdguardTeam/AdGuardExtra/files/8396685/adguard-extra.user.js.zip)

**Comment by rakleed** [comment]
Похоже ещё один вариант вёрстки нашёл — при построении маршрута на общественном транспорте нажал на интересующий маршрут, а затем на «Посмотреть подробнее». Также отправил сохранённую страницу на devteam@adguard.com

<details><summary>Скриншот</summary>

![image](https://user-images.githubusercontent.com/19418601/161313957-49fced2f-07e4-4aba-847a-3a353f51882a.png)

</details>

**Comment by rakleed** [comment]
@stanislav-atr а также теперь на главной https://yandex.ru/maps/213/moscow/?ll=37.670809%2C55.728419&z=11 блок с категориями ошибочно блокируется.

<details>
<summary>С AdGuard</summary>

![image](https://user-images.githubusercontent.com/19418601/161314950-4d07e7e9-9dbd-4fa2-9ad2-26f29d883f7e.png)

</details>

<details>
<summary>Без AdGuard</summary>

![image](https://user-images.githubusercontent.com/19418601/161314893-03aebb6c-0a53-41bf-9cc5-835477476ec1.png)

</details>

**Comment by rakleed** [comment]
@stanislav-atr

**Comment by stanislav-atr** [comment]
@rakleed 
> @stanislav-atr а также теперь на главной https://yandex.ru/maps/213/moscow/?ll=37.670809%2C55.728419&z=11 блок с категориями ошибочно блокируется.
[adguard-extra.user.js.zip](https://github.com/AdguardTeam/AdGuardExtra/files/8426079/adguard-extra.user.js.zip)

> И ещё заметил, что при построении маршрута на общественном транспорте, после того, как поменял местами «Откуда» и «Куда», все варианты маршрутов просто пропали.
Маловероятно, что Экстра блокирует маршруты. Какие сторонние расширения установлены? Версия браузера свежая?

**Comment by rakleed** [comment]
@stanislav-atr с последней версией Extra от вас теперь из сообщения https://github.com/AdguardTeam/AdGuardExtra/issues/306#issuecomment-1086174658 проблему с пропадающими маршрутами при изменении направления не могу воспроизвести, но проблема с ошибочной блокировкой категорий на главной всё ещё воспроизводится. А также заметил, что после построения маршрута и выбора вкладки «Такси» там ничего не отображается, хотя в обычной Extra этот элемент не блокируется.

<details><summary>Скриншот с такси</summary>

![image](https://user-images.githubusercontent.com/19418601/161966592-a9090038-c64e-4b2a-a496-acbe0b9d1a42.png)

</details>

Насчёт рекламы: иногда (раз в 5–10 открытий страницы) на главной и при построении маршрута появляются остатки от соцрекламы. Ну и реклама из https://github.com/AdguardTeam/AdGuardExtra/issues/306#issuecomment-1086171429 всё ещё появляется. Также на devteam@adguard.com отправил сохарнённую страницу.

<details><summary>Скриншоты с кодом элемента</summary>

![image](https://user-images.githubusercontent.com/19418601/161965494-31f35617-c9b8-4d57-98b5-5e9f370f7909.png)

![image](https://user-images.githubusercontent.com/19418601/161966032-d8592b21-2c06-4434-b9dc-f154155ed490.png)

</details>

**Comment by stanislav-atr** [comment]
Какие сторонние расширения установлены? Версия браузера?

**Comment by rakleed** [comment]
Google Chrome 100.0.4896.75. Попробовал отключить все расширения, но проблема всё ещё актуальна. Также воспроизводится в режиме инкогнито. И при включении обычной версии Extra или беты проблема не воспроизводится, поэтому я решил, что проблема именно в вашей Dev-версии Extra.

**Comment by stanislav-atr** [comment]
@rakleed, если есть возможность передать доступ (AnyDesk), то можно попробовать так.

**Comment by rakleed** [comment]
@stanislav-atr написали на devteam@adguard.com
