### ISSUE TITLE
yandex.ru

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardExtra#308]
### Issue URL (Ads)
 [https://yandex.ru/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fyandex.ru%2F)
### Comment
> Плашка рекламы заменяется на плашку промо, хотя это таже самая реклама.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/8Gvl9d4.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.9
Browser: | Edge
AdGuard driver: | WFP
Stealth mode: | disabled
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Russian
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js,<br>https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js

**Comment by stanislav-atr** [comment]
@Alex-302, совсем другие блоки, как воспроизвести?

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/68852737/158780378-bf1e248c-5e0c-468b-966d-405e93e3c0d5.png)
</details><br/>

**Comment by Alex-302** [comment]
Поменяли что ли. Попробуй подписаться на что-нибудь.
