### ISSUE TITLE
https://tv.mail.ru/online/ [Ads]

### ISSUE THREAD

**Issue by Lostfanman** [AdguardTeam/AdGuardExtra#309]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 
> ### Issue URL (Ads)
> [https://tv.mail.ru/online/]

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
![tv mail ru](https://user-images.githubusercontent.com/101786994/158745912-2722a24d-60e0-4d67-9168-697f49d5a657.png)

<details><summary>System configuration</summary>

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                             | Value
---                                     | ---
Operating system:                       | Windows 10 Pro 21H2 19044.1586
Browser:                                | Chrome 99.0.4844.51
AdGuard Extra version:                        | 1.0.373 Beta

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by stanislav-atr** [comment]
@Lostfanman, hi! Solved in [filters](https://github.com/AdguardTeam/AdguardFilters/commit/ab0edd667b78b0bac9f2c6763e79d61def25f675)  for now.

**Comment by Alex-302** [comment]
@zloyden Removed your rule. It breaks the site https://github.com/AdguardTeam/AdguardFilters/issues/112078#issuecomment-1073218185

**Comment by zloyden** [comment]
It was a temporary rule, but it looks like we have to handle it via AdGuard Extra.
