### ISSUE TITLE
Submit your Firefox extension to addons.mozilla.org (AMO)

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardExtra#310]
It would be nice if you submit AdGuard Extra as a standalone extension for Firefox at addons.mozilla.org (AMO) to make it easier to install.

**Comment by stanislav-atr** [comment]
@rakleed, hi! Our FF extension for Extra is on pending review by AMO atm.

**Comment by rakleed** [comment]
@stanislav-atr it's been a month now and your extension is still not available on AMO. Why?

**Comment by stanislav-atr** [comment]
@rakleed, Extra extension is still not being reviewed by AMO.
