### ISSUE TITLE
Submit your Safari extension to the App Store

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardExtra#311]
It would be nice if you submit AdGuard Extra as a standalone Safari extension in the App Store to make it easier to install. Since installing Tampermonkey or Userscripts only for your script is inconvenient.

**Comment by stanislav-atr** [comment]
Hi! Thank you for your feedback, this might be possible in the future.

**Comment by ameshkov** [comment]
We should instead make Extra a part of AdGuard for Safari which means adding userscripts support.
