### ISSUE TITLE
drive2.ru [Ads]

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardExtra#319]
Mobile and desktop. Apps and extensions.
https://github.com/AdguardTeam/AdguardFilters/issues/104583#issuecomment-1124660028
https://github.com/AdguardTeam/AdguardFilters/issues/104583#issuecomment-1120817827
https://github.com/AdguardTeam/AdguardFilters/issues/104583#issuecomment-1120203404

**Comment by MikhailShishkinMgn** [comment]
it doesn't work with drive2.ru
