### ISSUE TITLE
Is it possible to install this as source inside of an extension ZIP download?

### ISSUE THREAD

**Issue by palewire** [AdguardTeam/AdGuardExtra#329]
I'm using AdGuard as an extension in an automated browser task via Playwright. I'm wonder if it's possible to somehow download the source for this extra extension and plop it into the main extension's source, which I downloaded from GitHub.

**Comment by maximtop** [comment]
Hi! 
There is no possibility to use the AdGuard Extra extension inside the AdGuard AdBlocker extension. But you can take the zipped build of the AdGuard Extra extension here: https://static.adguard.com/extensions/adguardextra/release/chrome.zip and use it in playwright.

**Comment by palewire** [comment]
Thank you. I now that have that running [here](https://github.com/palewire/news-homepages/blob/main/newshomepages/screenshot.py#L62)
