### ISSUE TITLE
AdGuard Extra does not work on mail.ru, yandex.ru

### ISSUE THREAD

**Issue by DimZ2** [AdguardTeam/AdGuardExtra#338]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/33488229/178294821-fb1beb6e-a2b5-417f-b1fe-55a91d8664a8.png)
![image](https://user-images.githubusercontent.com/33488229/178294848-d2982f73-10c8-4eaa-a338-108ab6000ddd.png)

</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                             | Value
---                                     | ---
Operating system:                       | Windows 10
Browser:                                | Microsoft Edge
AdGuard version:                        | 4.0.181
Filters enabled:                        | Ad Blocker, Stealth Mode, Stimuli, Security. DNS Filter. Language
Userscript host (AdGuard/Tampermonkey): | Tampermonkey

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by stanislav-atr** [comment]
@DimZ2, hi! Could you please specify, what's wrong?
