### ISSUE TITLE
gazeta.ru

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdGuardExtra#34]
@adguard-bot commented on [Thu Oct 10 2019](https://github.com/AdguardTeam/AdguardFilters/issues/42082)

### Issue URL (Ads)
[https://www.gazeta.ru/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.gazeta.ru%2F)
### Comment
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/Obiav09.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Ext
AdGuard version: | 1.5.4
Browser: | Safari
Filters: | AdGuard Russian,<br>AdGuard Annoyances,<br>AdGuard Base,<br>AdGuard Tracking Protection,<br>AdGuard Social Media

**Comment by zloyden** [comment]
Директ повторяется без Extra в остальных браузерах. В сафари с этим скриптлетом вроде ок. @tvinzz проверь у себя `gazeta.ru#%#//scriptlet('abort-on-property-read', 'Object.prototype.forceRender.banner')`.

**Comment by Alex-302** [comment]
Extension, AG Annoyances is disabled.
