### ISSUE TITLE
Does this addon block Facebook sponsors?

### ISSUE THREAD

**Issue by trmdi** [AdguardTeam/AdGuardExtra#351]
I don't see any difference before vs after installing this addon/script. Facebook sponsors posts still appear. Or am I misunderstanding it?

**Comment by ameshkov** [comment]
It should support it. @stanislav-atr could you please verify that the current code handles FB well? You'll need to disable AdGuard since FB is also handled by the ordinary rules there.

**Comment by trmdi** [comment]
Hmm... Does the bot operate properly?

**Comment by slavaleleka** [comment]
@trmdi is the issue not fixed? could you please check it with Extra v1.0.417?

**Comment by zloyden** [comment]
Should be fixed with `AdGuard Extra 1.0.417` (the same beta version), but if it's not, let us know.

**Comment by trmdi** [comment]
Sponsor posts appear again:

![image](https://user-images.githubusercontent.com/11857205/193437103-250d9f71-c861-425c-b4d8-d61115226dfa.png)

**Comment by trmdi** [comment]
Sponsored posts reappear.
