### ISSUE TITLE
yandex to dzen - updates

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdGuardExtra#362]
Most of the issues with transition `yandex to dzen` were fixed, but if you find some new ones, report here as a comment below.

---

https://dzen.ru/news?issue_tld=ru
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/190136940-577dcc3a-db2a-46e2-9c2e-d053b88b6eb3.png)

</details><br/>

---

https://dzen.ru/
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/190144871-f1fce9d8-7c6b-41a8-9759-0b5622bde1e8.png)

</details><br/>

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdGuardExtra/issues/361#issuecomment-1246976830

**Comment by zloyden** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/129287#issuecomment-1249115894
https://github.com/AdguardTeam/AdguardFilters/issues/129287#issuecomment-1249135873

**Comment by NUser2018** [comment]
@zloyden Некоторые элементы\посты в ленте Дзена местами не загружаются. И таких не один в ленте. Скриншот прилагается.
![yandex ru-dzen ru-4](https://user-images.githubusercontent.com/43743908/190613077-9712b2cc-00a4-4ee8-8a20-398ba62c979d.jpg)

**Comment by Alex-302** [comment]
Там же написано, что это реклама.

**Comment by NUser2018** [comment]
> Там же написано, что это реклама.

Опа, не заметил, извините. Но значит она плохо\не до конца вырезается\скрывается. Почему эти блоки-остатки на месте рекламы остаются тогда видны а не полностью вырезаются\скрываются?

**Comment by zloyden** [comment]
https://github.com/AdguardTeam/AdGuardExtra/issues/362#issuecomment-1249170448 здесь нужно обращаться к @stanislav-atr, все комментарии рассматриваются:)
Конкретно этот остаток был убран в фильтрах, проверьте обновление фильтров - новое правило должно быть доступно.
Если же он есть после обновления, отпишитесь здесь и вероятно нужно будет решение в экстре.

**Comment by stanislav-atr** [comment]
@NUser2018, добрый день, спасибо за обратную связь! На данный момент zen.yandex переезжает на dzen.ru, поэтому реклама и остатки от нее могут появляться чаще обычного.

**Comment by NUser2018** [comment]
> Конкретно этот остаток был убран в фильтрах, проверьте обновление фильтров - новое правило должно быть доступно.
> Если же он есть после обновления, отпишитесь здесь и вероятно нужно будет решение в экстре.

Регулярно обновляется автоматом, но дополнительно обновил принудительно вручную, к сожалению проблема с остатками от рекламы сохраняется.

**Comment by NUser2018** [comment]
> @NUser2018, добрый день, спасибо за обратную связь! На данный момент zen.yandex переезжает на dzen.ru, поэтому реклама и остатки от нее могут появляться чаще обычного.

@stanislav-atr Так вроде уже переехал... Ну будем надеятся тогда что все необходимые процессы завершатся как можно скорее, но в том числе и на стороне Adguard выпуском соответствующих нужных обновлений. Спасибо за Ваш комментарий.

**Comment by zloyden** [comment]
https://dzen.ru/video/watch/62c935b2354a1f4bd2b815f3#video.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/191252892-0d33bad0-250e-4e95-84a9-abe800d6ed9f.png)

</details><br/>

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/130398
+ на десктопе баннер браузера в углу

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/129287#issuecomment-1257215507

**Comment by Alex-302** [comment]
* broken page
https://github.com/AdguardTeam/AdguardFilters/issues/129287#issuecomment-1259154131

* ad leftovers
https://dzen.ru/news/story/Mobilizacionnyj_punkt_voenkomata_razvernut_naKPP_vSevernoj_Osetii_nagranice_sGruziej--b7dfdd538964c8969e205bfd0bf619c6?lang=ru&rubric=index&fan=1&stid=pA1bWIhVyOkD1EdONGNq&t=1664271239&tt=true&persistent_id=229802622&story=74a8a8b7-3069-566c-9c94-cefac89105b9&issue_tld=ru

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/129287#issuecomment-1260374174
> При прокрутке вниз не подгружаются новости. Это происходит во всех категориях

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/129287#issuecomment-1261905863

**Comment by stanislav-atr** [comment]
https://dzen.ru/video/watch/631ae170aaed1502a5a67cdf#video
![image](https://user-images.githubusercontent.com/68852737/193610590-c0cff4a7-1b0a-4ce5-a4e5-d835a3e82ea2.png)

**Comment by zloyden** [comment]
https://dzen.ru/
https://uploads.adguard.org/aavp2.png

**Comment by Alex-302** [comment]
@stanislav-atr https://github.com/AdguardTeam/AdguardFilters/issues/129287#issuecomment-1292942761

**Comment by zloyden** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/129287#issuecomment-1308785328

**Comment by zloyden** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/134640#issuecomment-1326263157

**Comment by zloyden** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/134640#issuecomment-1332304655
