### ISSUE TITLE
FileCR

### ISSUE THREAD

**Issue by dnihil** [AdguardTeam/AdGuardExtra#363]
Screenshot:
![image](https://user-images.githubusercontent.com/112921338/190555321-f6332f34-fe47-4875-ab72-35ac432e1e71.png)

**Comment by stanislav-atr** [comment]
@dnihil, hi! Thank you for feedback, could you please also specify on how to reproduce this?
I was able to navigate the page and download something without triggering this, what filters and/or other extensions do you use?

**Comment by dnihil** [comment]
> @dnihil, turn UBlock off and check the website, if the issue persists, try disabling filters in AdGuard extension one by one to pinponit the problematic one.

it was UBlock that's making it popup

**Comment by stanislav-atr** [comment]
@dnihil glad i could help!
