### ISSUE TITLE
duplichecker.com

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/AdGuardExtra#364]
https://github.com/AdguardTeam/AdguardFilters/issues/129065

After I block their picture url they change path/file name after about 1-2 days (going on for a few weeks now) - current url block rule causes one picture to be falsely blocked due to .jpg extension in its path.

Due to site author's behaviour I only updated url block rule and not element hiding rules.

**Comment by BlazDT** [comment]
Please check again, just installed Extra stable version ads are visible.

**Comment by JobcenterTycoon** [comment]
The blocked image `delivery.adrecover.com/allow.jpg` triggers the ad reinsertion. Redirecting a 1x1 works fine for me

**Comment by BlazDT** [comment]
Added rules for it, thanks. Still needs to be addressed by Extra.
