### ISSUE TITLE
Discovery + / TLG GO not working with Adguard enabled. 

### ISSUE THREAD

**Issue by MasterTro11** [AdguardTeam/AdGuardExtra#368]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: This is what the error message says on Discovery plus"Please try again later. For additional help and troubleshooting, please visit https://help.discoveryplus.com/hc/en-us/. ERROR CODE: UNKNOWN ERROR"

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                             | Value
---                                     | ---
Operating system:                       | ?
Operating system version (Android/iOS)  | ?
Browser:                                | ?
AdGuard version:                        | ?
Filters enabled:                        | ?
Userscript host (AdGuard/Tampermonkey): | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Which AdGuard Extra version?

**Comment by zzebrum** [comment]
@MasterTro11 we need more information about reproducing this issue. reopen if needed

**Comment by MasterTro11** [comment]
Alex, I wanted to report history channel isn't working with adguardOn Tue, Nov 15, 2022 at 9:35 AM z f ***@***.***> wrote:
        What info?? 
        
        
            
                
                
                    On Tuesday, November 15, 2022 at 03:25:36 AM CST, zzebrum ***@***.***> wrote:
                
                
                
                
@MasterTro11 we need more information about reproducing this issue. reopen if needed

**Comment by Alex-302** [comment]
@MasterTro11 Hi.Is the site broken by AdGuard Extra extension (userscript)?
