### ISSUE TITLE
Extension stop works at every update until you allow permissions to specific pages.

### ISSUE THREAD

**Issue by Mlocik97** [AdguardTeam/AdGuardExtra#376]
***Description***:
* **Current behaviour**: 

extension stop works at every update until you allow permissions to specific pages. So if old version needed access to websites A, B, C and new need access to A, B, C, D... it will stop for any, until you allow permissions for D. As extensions continues to add filter for more websites, we should maybe use different approach of handling permissions (maybe allow it on all websites), so in future, it doesn't require user's interaction of allowing permissions when list of websites where extensions is applied change.

Information                             | Value
---                                     | ---
Operating system:                       | Linux
Operating system version (Android/iOS)  | Ubuntu 20.04
Browser:                                | Chrome 107.0.5304.110
AdGuard version:                        | 4.1.39
AdGuard Extra version: | 1.0.474

**Comment by Mlocik97** [comment]
I understand, but on other side, this way user needs to allow permissions after every update, and it's annoying.

**Comment by Mlocik97** [comment]
as in my case (and case of a lot of people) I wouldn't actually see ads, bcs I never visit one of those added websites. While I actually see ads until I re-enable extensions with new permissions. So 5 days waiting is in my opinion better. Like there is 100 different websites that this extensions handle, and after update it's 101, but even those existing 100 shows ads until you reenable extension after update, but do you ever visit that one specific new website added to extension list? And if, you had ad until it was added to extension anyway. When I think about it, answer is clear.

**Comment by maximtop** [comment]
We discussed this issue and decided to try vaster permissions. Thank you.

**Comment by maximtop** [comment]
One more time extension would be disabled.

**Comment by Mlocik97** [comment]
I just got update... I think this issue can be closed.

**Comment by jbionic2016** [comment]
> One more time extension would be disabled.

Absolutely. I've disabled it too as soon as the notification update has been delivered.

Where can I find the complete up-to-date list of websites that AdguardExtra applies its ruleset?    
Can I see specific rules applied to each particular site?

**Comment by Mlocik97** [comment]
@jbionic2016 I don't see any reason to disable/delete extension just because it has access to all websites instead few hundreds. You used that extension because of those websites that it handle, and you gave permissions to those websites anyway... if extension would be harmful, for example would steal your password, it would have done it before update too anyway. So what's the point?

You can restrict extension in settings by yourself anyway.

But I agree one list of websites it applies to would be nice. Some `.md` or `.txt` file here in repo or wiki for example.

**Comment by Mlocik97** [comment]
For now, I give url list here:

```
"*://*.4pda.ru/*",
"*://*.4pda.to/*",
"*://*.adguard.com/*",
"*://*.adguard.app/*",
"*://*.auto.ru/*",
"*://*.media.auto.ru/*",
"*://*.yandex.ru/*",
"*://*.yandex.kz/*",
"*://*.yandex.by/*",
"*://*.yandex.ua/*",
"*://*.yandex.md/*",
"*://*.yandex.fr/*",
"*://*.yandex.lv/*",
"*://*.yandex.ee/*",
"*://*.yandex.com.tr/*",
"*://*.yandex.com/*",
"*://*.yandex.uz/*",
"*://*.afisha.yandex.ru/*",
"*://*.afisha.yandex.kz/*",
"*://*.afisha.yandex.by/*",
"*://*.afisha.yandex.ua/*",
"*://*.afisha.yandex.md/*",
"*://*.mail.yandex.ru/*",
"*://*.mail.yandex.kz/*",
"*://*.mail.yandex.by/*",
"*://*.mail.yandex.ua/*",
"*://*.mail.yandex.md/*",
"*://*.mail.yandex.com.tr/*",
"*://*.mail.yandex.com/*",
"*://*.mail.yandex.fr/*",
"*://*.mail.yandex.ee/*",
"*://*.mail.yandex.kg/*",
"*://*.mail.yandex.lv/*",
"*://*.mail.yandex.lt/*",
"*://*.music.yandex.ru/*",
"*://*.music.yandex.kz/*",
"*://*.music.yandex.by/*",
"*://*.music.yandex.ua/*",
"*://*.music.yandex.md/*",
"*://*.tv.yandex.ru/*",
"*://*.tv.yandex.kz/*",
"*://*.tv.yandex.by/*",
"*://*.tv.yandex.ua/*",
"*://*.tv.yandex.md/*",
"*://*.dzen.ru/*",
"*://*.realty.yandex.ru/*",
"*://*.docviewer.yandex.ru/*",
"*://*.docviewer.yandex.kz/*",
"*://*.docviewer.yandex.by/*",
"*://*.docviewer.yandex.ua/*",
"*://*.docviewer.yandex.md/*",
"*://*.docviewer.yandex.com.tr/*",
"*://*.docviewer.yandex.com.am/*",
"*://*.drive2.ru/*",
"*://*.drive2.com/*",
"*://*.kinopoisk.ru/*",
"*://*.eda.ru/*",
"*://*.facebook.com/*",
"*://*.facebookcorewwwi.onion/*",
"*://*.go.mail.ru/*",
"*://*.e.mail.ru/*",
"*://*.octavius.mail.ru/*",
"*://*.mail.ru/*",
"*://*.news.mail.ru/*",
"*://*.auto.mail.ru/*",
"*://*.sportmail.ru/*",
"*://*.horo.mail.ru/*",
"*://*.deti.mail.ru/*",
"*://*.lady.mail.ru/*",
"*://*.hi-tech.mail.ru/*",
"*://*.minigames.mail.ru/*",
"*://*.otvet.mail.ru/*",
"*://*.tv.mail.ru/*",
"*://*.ok.ru/*",
"*://*.rambler.ru/*",
"*://*.championat.com/*",
"*://*.gazeta.ru/*",
"*://*.lenta.ru/*",
"*://*.quto.ru/*",
"*://*.rns.online/*",
"*://*.passion.ru/*",
"*://*.wmj.ru/*",
"*://*.wp.pl/*",
"*://*.vidstream.online/*",
"*://*.livejournal.com/*",
"*://*.varlamov.ru/*",
"*://*.lena-miro.ru/*",
"*://*.olegmakarenko.ru/*",
"*://*.periskop.su/*",
"*://*.levik.blog/*",
"*://*.vadimrazumov.ru/*",
"*://*.otzovik.com/*",
"*://*.sinoptik.ua/*",
"*://*.multiup.org/*",
"*://*.yaplakal.com/*",
"*://*.yap.ru/*",
"*://*.pravda.com.ua/*",
"*://*.epravda.com.ua/*",
"*://*.glianec.com/*",
"*://*.ostro.org/*",
"*://*.nashamama.com/*",
"*://*.bilshe.com/*",
"*://*.zdorovia.com.ua/*",
"*://*.i.factor.ua/*",
"*://*.gismeteo.ua/*",
"*://*.1777.ru/*",
"*://*.cn.ru/*",
"*://*.finance.i.ua/*",
"*://*.glavcom.ua/*",
"*://*.hvylya.net/*",
"*://*.kp.ua/*",
"*://*.love.i.ua/*",
"*://*.newsone.ua/*",
"*://*.peers.tv/*",
"*://*.radio.i.ua/*",
"*://*.real-vin.com/*",
"*://*.viks.bz/*",
"*://*.vsetv.com/*",
"*://*.tv.ua/*",
"*://*.isport.ua/*",
"*://*.eurointegration.com.ua/*",
"*://*.u-news.com.ua/*",
"*://*.strana.ua/*",
"*://*.4mama.ua/*",
"*://*.bigmir.net/*",
"*://*.dengi.ua/*",
"*://*.enovosty.com/*",
"*://*.facenews.ua/*",
"*://*.football24.ua/*",
"*://*.gorod.dp.ua/*",
"*://*.inforesist.org/*",
"*://*.kolobok.ua/*",
"*://*.liga.net/*",
"*://*.nnovosti.info/*",
"*://*.smak.ua/*",
"*://*.tochka.net/*",
"*://*.ukr.net/*",
"*://*.nv.ua/*",
"*://*.meteo.ua/*",
"*://*.besplatka.ua/*",
"*://*.lifedon.com.ua/*",
"*://*.sheee.co.il/*",
"*://*.walla.co.il/*",
"*://*.kakprosto.ru/*",
"*://*.24smi.org/*",
"*://*.youtube.com/*",
"*://*.echo.msk.ru/*",
"*://*.twitch.tv/*",
"*://*.pussyspace.net/*",
"*://*.pussyspace.com/*",
"*://*.letidor.ru/*",
"*://*.motor.ru/*",
"*://*.zv.zp.ua/*",
"*://*.liveinternet.ru/*",
"*://*.go.discovery.com/*",
"*://*.discoveryplus.com/*",
"*://*.go.tlc.com/*",
"*://*.watch.hgtv.com/*",
"*://*.investigationdiscovery.com/*",
"*://*.sciencechannel.com/*",
"*://*.spletnik.ru/*",
"*://*.tidal.com/*",
"*://*.msn.com/*",
"*://*.duplichecker.com/*",
"*://*.smallseotools.com/*",
"*://*.amedia.online/*",
"*://*.sm.news/*"
```

**Comment by jbionic2016** [comment]
Thanks. I barely visit any websites from your list )))
I don't understand why I have this extension installed, no wonder it has only 10,000 users ...

> For now, I give url list here (from manifest):
> 
> ```
> "*://*.4pda.ru/*",
> "*://*.4pda.to/*",
....
> "*://*.msn.com/*",
> "*://*.duplichecker.com/*",
> "*://*.smallseotools.com/*",
> "*://*.amedia.online/*",
> "*://*.sm.news/*"
> ```

**Comment by HanabishiRecca** [comment]
I have an opposite opinion. It was fairly useful to know which websites this extention actually work for. Now you can't just tell. And extension transparency was good by itself.
Also now the script actually runs on **every** website you visit, and as the code is poorly written (checks every target url for every know website with O(n) complexity instead of map lookup with O(1) complexity), the extension became noticable performance downside.

**Comment by Mlocik97** [comment]
>  It was fairly useful to know which websites this extention actually work for.

I don't think this information should be stores in "permissions list". It can be writen somewhere else to understand.

> Also now the script actually runs on every website you visit, and as the code is poorly optimized (checks every target url for every known website with O(n) complexity instead of map lookup with O(1) complexity), the extension became noticable performance downside.

I checked code, and agree, it's horrible... poorly optimized and with errors too. Anyway I don't think extension's code should be optimized by permissions. It's like putting rubbish under carpet. This should be created as different issue and code should be optimized so it doesn't affect performance of websites it doesn't apply to, and it should also improve performance of those that are in filtering list.

**Comment by ameshkov** [comment]
Regarding the permissions list, we'll take care of it: https://github.com/AdguardTeam/AdGuardExtra/issues/381

@HanabishiRecca 
> poorly optimized

Fair point, we'll update it: https://github.com/AdguardTeam/AdGuardExtra/issues/380

@Mlocik97 
> with errors too

If you spotted any error, please report it in a separate issue.
