### ISSUE TITLE
direct.yandex.ru

### ISSUE THREAD

**Issue by AiratHalitov** [AdguardTeam/AdGuardExtra#378]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: На странице настройки кампании в яндекс.директе расширение мешает предпросмотру объявлений. 
* Примеры ссылок: https://direct.yandex.ru/dna/banners-edit
* Или тут https://direct.yandex.ru/dna/grid/banners

* **Expected behaviour**: 

Отключаешь расширение и превью объявлений работает.
Можете ограничить это расширение на этом сайте?

***Steps to reproduce the problem***:

Открываете яндекс.директ, создаете кампанию, объявление и там справа будет предпросмотр. Там ничего не будет, когда расширение включено.

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                             | Value
---                                     | ---
Operating system:                       | Linux Mint 21
Browser:                                | Google Chrome 107.0.5304.110 
AdGuard version:                        | 1.0.474
Filters enabled:                        | сам AdGuard отключен на этом сайте
Userscript host (AdGuard/Tampermonkey): | AdGuard

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by stanislav-atr** [comment]
@AiratHalitov, добрый день, спасибо за обратную связь! `direct.yandex` будет исключен в бете расширения в течение нескольких часов, а в релизной версии - в течение нескольких дней.

**Comment by AiratHalitov** [comment]
@stanislav-atr 
Спасибо! А как бету поставить?

**Comment by stanislav-atr** [comment]
@AiratHalitov по ссылке из нашего [репозитория](https://github.com/AdguardTeam/AdGuardExtra#chrome-or-chromium-based-browser) или из [хром стора](https://chrome.google.com/webstore/detail/adguard-extra-beta/mglpocjcjbekdckiahfhagndealpkpbj?hl=en).
