### ISSUE TITLE
Permission to read and change all my data for ALL SITES - WHAT FOR?

### ISSUE THREAD

**Issue by jbionic2016** [AdguardTeam/AdGuardExtra#379]
Hi there,

I am using AdguardExtra as Chrome browser extension. It would occasionally pop up a notification when updating permissions for a specific website, but the latest has got me confused (see attached screenshot).

Why is it asking to read and change all my data on ALL WEBSITES?

Thanks.

https://i.ibb.co/5xV3m3s/222.jpg
[url=https://imgbb.com/][img]https://i.ibb.co/5xV3m3s/222.jpg[/img][/url]

**Comment by siddhpant** [comment]
See #376.

**Comment by ameshkov** [comment]
Having it limited to a handful websites was working just okay until it didn't :(

Every time we added a new website, there were tons of people who miss the notification from Chrome about it and end up with the extension being disabled.

Of course, this is not an ideal solution, but seems to be a lesser evil considering everything.
