### ISSUE TITLE
Optimize the rule selection in the extension

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardExtra#380]
Currently, we're using a legacy scheme that was okay when there were just a handful of websites. Now there're over 150 domains it works on and checking `isMatchingHostnames` for every domain takes considerable time.

**Comment by HanabishiRecca** [comment]
Some thoughts:

1. I don't really understand why this is a standalone extension. Main AdGuard extension has JS rules support and scriptlet injections. So this can effectively be made just as another additional filter. And url matching will be handled by it too. Not a real concern, just a thought.
2. For userscript version `@match`/`@include` headers can be utilized. So the script at least will not run on every website. And it does not have that extension permissions problem (Tampermonkey asks for every script update anyway).
3. Will be good to have a repository with the actual source code where community can contribute to.

**Comment by ameshkov** [comment]
1. We're in process of deprecating JS rules and allowing them in the User filter only. And scriptlets are kind of "declarative" approach which is not always enough. That's why Extra was created in the first place, to have a userscript where we can apply complicated imperative logic against ads that cannot be handled differently.
2. Yeah, this is also a fair point and it should be done that way..
3. Well, that's a good thing to discuss. The idea was to make it a little bit harder for adtech to adapt to Extra. Maybe even obfuscate the code. On the other hand, obfuscated code is not allowed in the extension stores so in the end we have a userscript and an extension with the code anyone can inspect, and a repo with no code at the same time.
