### ISSUE TITLE
docs.yandex.ru/docs

### ISSUE THREAD

**Issue by AiratHalitov** [AdguardTeam/AdGuardExtra#385]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: Не дает открывать документы на странице https://docs.yandex.ru/docs?type=docx (просто идет загрузка и ничего не происходит)

***System configuration***

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                             | Value
---                                     | ---
Operating system:                       | Linux Mint 21
Browser:                                | Google Chrome 107.0.5304.110
AdGuard version:                        | 1.0.476
Userscript host (AdGuard/Tampermonkey): | AdGuard

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by stanislav-atr** [comment]
@AiratHalitov, добрый день! Не получилось вопроизвести, пришлите, пожалуйста, скриншоты консоли до и после клика на документ. 

Чтобы открыть консоль: F12 или
Правый клик на странице > Просмотреть код > Вкладка Console в открывшемся окне

**Comment by AiratHalitov** [comment]
![image](https://user-images.githubusercontent.com/4050715/204899717-d632b10b-6262-4f94-ac27-c5a8e059016c.png)

Почему-то тут включено на всех сайтах, хотя раньше был список сайтов. 
![image](https://user-images.githubusercontent.com/4050715/204899804-8f486e9d-b651-4c6f-bfb9-a9948b73e0a3.png)

**Comment by Alex-302** [comment]
@AiratHalitov Переделали, потому что при каждом изменении расширение отключалось браузером.

**Comment by stanislav-atr** [comment]
@AiratHalitov похоже на #384, скорее всего будет исправлено в сегодняшнем обновлении для беты.
