### ISSUE TITLE
Problem with ads on Twitch

### ISSUE THREAD

**Issue by Martin679** [AdguardTeam/AdGuardExtra#397]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: With Adguard Extra, the ads don't appear on Twitch.tv, but for about 10 seconds a screen appears that says: Preparing your stream.
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/120264361/209011909-54c18d47-5afd-46fc-a325-794df87d3b67.png)

</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

The twitch stream should be displayed as normal.

<br/>

***Steps to reproduce the problem***: access a Twitch live with Adguard Extra.

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:** None

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                             | Value
---                                     | ---
Operating system:                       | Windows 10
Operating system version (Android/iOS)  | -
Browser:                                | Google Chrome
AdGuard version:                        | (Adguard Extra): 1.0.485
Filters enabled:                        | None
Userscript host (AdGuard/Tampermonkey): | AdGuard

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by gaveer** [comment]
i can confirm same issue

**Comment by CryptoKey98** [comment]
Same issue.

**Comment by CrazyWolf13** [comment]
I can confirm 

Twitch Banner keeps flickering:

"Watch as i attempts to hide" or something like that

**Comment by muhasturk** [comment]
This problem is more common in broadcasters with more viewers like iitztimmy

**Comment by stanislav-atr** [comment]
Moving this into #383
