### ISSUE TITLE
dropgalaxy.com

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardExtra#403]
@adguard-bot commented on [Wed Dec 21 2022](https://github.com/AdguardTeam/AdguardFilters/issues/137961)

### Issue URL (Anti Adblock Script)
 [https://dropgalaxy.com/6ktnd4e5vi7h](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fdropgalaxy.com%2F6ktnd4e5vi7h)
### Comment
Username: @XBadFellaX
> Same behaviour on android as well.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/9uP6NUR.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.12+nightly+4
Browser: | Chrome
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Self-destructing third-party cookies (180)
DNS filtering: | server: `quic://dns.adguard-dns.com`<br>filters: `https://filters.adtidy.org/windows/filters/15.txt`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard URL Tracking, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>Adblock Warning Removal List, <br/>AdGuard Annoyances<br/><br/><b>Other:</b><br/>AdGuard Experimental
Custom filters: | https://abp.oisd.nl/
Userscripts: | https://userscripts.adtidy.org/beta/assistant/4.3/assistant.user.js,<br>https://userscripts.adtidy.org/beta/adguard-extra/1.0/adguard-extra.user.js,<br>https://userscripts.adtidy.org/beta/popup-blocker/2.5/popupblocker.user.js
Referrer: | [https://dropgalaxy.com/6ktnd4e5vi7h](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fdropgalaxy.com%2F6ktnd4e5vi7h)

---

@adguard-bot commented on [Thu Dec 22 2022](https://github.com/AdguardTeam/AdguardFilters/issues/137961#issuecomment-1363085541)

### Issue URL (Anti Adblock Script)
 [https://dropgalaxy.com/m6xdcqlhgofx](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fdropgalaxy.com%2Fm6xdcqlhgofx)
### Comment
Username: @manirhossen
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/pNAC1tg.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.11.3
Browser: | Chrome
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing first-party cookies (4320), <br>Self-destructing third-party cookies (180), <br>Block Push API, <br>Block Location API
DNS filtering: | server: `quic://dns.adguard-dns.com`<br>filters: `User+rules`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>EasyPrivacy, <br/>AdGuard Tracking Protection, <br/>AdGuard URL Tracking<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>Fanboy's Annoyances, <br/>Adblock Warning Removal List, <br/>I don't care about cookies, <br/>AdGuard Annoyances, <br/>AdGuard Cookie Notices, <br/>AdGuard Popups, <br/>AdGuard Mobile App Banners, <br/>AdGuard Other Annoyances, <br/>AdGuard Widgets<br/><br/><b>Other:</b><br/>Filter unblocking search ads and self-promotion, <br/>AdGuard Experimental
Userscripts: | https://userscripts.adtidy.org/release/assistant/4.3/assistant.user.js,<br>https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js,<br>https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js,<br>J:\Java%20Script\RARBG%20Advanced%20Filters.user.js,<br>https://openuserjs.org/install/Bloggerpemula/Bypass_All_Shortlinks_Manual_Captcha.user.js,<br>https://greasyfork.org/scripts/431691-bypass-all-shortlinks/code/Bypass%20All%20Shortlinks.user.js
Referrer: | [https://dropgalaxy.com/m6xdcqlhgofx](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fdropgalaxy.com%2Fm6xdcqlhgofx)

---

@Alex-302 commented on [Fri Dec 23 2022](https://github.com/AdguardTeam/AdguardFilters/issues/137961#issuecomment-1363947110)

@AdamWr @piquark6046 Could you please help with it?

---

@piquark6046 commented on [Fri Dec 23 2022](https://github.com/AdguardTeam/AdguardFilters/issues/137961#issuecomment-1363953928)

It seems that the a visitor will be redirected to https://dropgalaxy.com if devtool is opened.

---

@AdamWr commented on [Fri Dec 23 2022](https://github.com/AdguardTeam/AdguardFilters/issues/137961#issuecomment-1363957494)

I cannot reproduce anti-adblock on my side.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/209344351-f71aa4cb-9404-405b-8ac9-13c068d789b2.png)

</details>

So, I guess it's caused by DNS filtering or might depends on location.

---

@piquark6046 commented on [Fri Dec 23 2022](https://github.com/AdguardTeam/AdguardFilters/issues/137961#issuecomment-1363959024)

On my side, I can reproduce it with the following configuration:
 - AdGuard Browser Extension 4.1.53 on Google Chrome
 - AdGuard Base, AG TPF, AG URL Tracking, AG Annoyances

I used https://github.com/AdguardTeam/AdguardFilters/issues/137961#issuecomment-1363085541.

---

@XBadFellaX commented on [Fri Dec 23 2022](https://github.com/AdguardTeam/AdguardFilters/issues/137961#issuecomment-1364053233)

> 

I am in Canada, if that helps. Using Adguard DNS with QUIC. Also using OISD basic alongside Adguard on android and OISD full on windows alongside adguard, I have tried disabling OISD on both android and windows and no success. So could be Adguard DNS, not sure. I searched reddit for this detection as well and there were some people who were experiencing this and some weren't so as you said could be region based. Is there a way to fix though? Like a custom filter entry we can input in user filters? I see that ublock reddit guys had a thread about it they came up with something, I tried those but didn't work for me. Thanks for looking into this, the places I download stuff from all use drop galaxy and I really need this to work, I am willing to provide any info needed. 

---

@piquark6046 commented on [Tue Dec 27 2022](https://github.com/AdguardTeam/AdguardFilters/issues/137961#issuecomment-1365809647)

~~To disable the redirection with a scriptlet rule, please use `dropgalaxy.com#%#//scriptlet("set-constant", "console.clear", "undefined")`~~

Blocking https://fastly.jsdelivr.net/npm/disable-devtool/disable-devtool.min.js can resolve the aggressive anti-devtool script.

---

@XBadFellaX commented on [Sun Jan 01 2023](https://github.com/AdguardTeam/AdguardFilters/issues/137961#issuecomment-1368532511)

> ~To disable the redirection with a scriptlet rule, please use `dropgalaxy.com#%#//scriptlet("set-constant", "console.clear", "undefined")`~
> 
> Blocking https://fastly.jsdelivr.net/npm/disable-devtool/disable-devtool.min.js can resolve the aggressive anti-devtool script.

Can you tell me how to block it in adguard? I added the above link to custom filters under filters in adguard but dropgalaxy is still detecting it... Can you help? 

---

@adguard-bot commented on [Tue Jan 03 2023](https://github.com/AdguardTeam/AdguardFilters/issues/137961#issuecomment-1369310049)

### Issue URL (Anti Adblock Script)
 [https://dropgalaxy.com/madiaghivg1t](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fdropgalaxy.com%2Fmadiaghivg1t)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/WqUQ33V.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v4.1.53
Browser: | Firefox
Stealth mode: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances, <br/>AdGuard Popups<br/><br/><b>Other:</b><br/>Filter unblocking search ads and self-promotion<br/><br/><details><summary><b>Language-specific:</b></summary>AdGuard Turkish, <br/>AdGuard French, <br/>AdGuard Russian, <br/>AdGuard Chinese, <br/>AdGuard German, <br/>AdGuard Japanese, <br/>AdGuard Dutch, <br/>AdGuard Spanish/Portuguese, <br/>ABPindo, <br/>Bulgarian list, <br/>EasyList China, <br/>EasyList Czech and Slovak, <br/>EasyList Hebrew, <br/>EasyList Italy, <br/>Liste AR, <br/>AdBlockID, <br/>EasyList Thailand, <br/>ABPVN List, <br/>Official Polish filters for AdBlock, uBlock Origin & AdGuard, <br/>List-KR, <br/>Polish Anti Adblock Filters, <br/>Dandelion Sprout's Nordic Filters</details>

---

@Alex-302 commented on [Wed Jan 04 2023](https://github.com/AdguardTeam/AdguardFilters/issues/137961#issuecomment-1370917992)

@AdamWr Could you please assist?

---

@AdamWr commented on [Wed Jan 04 2023](https://github.com/AdguardTeam/AdguardFilters/issues/137961#issuecomment-1370923341)

It looks like that it depends on location - https://github.com/AdguardTeam/AdguardFilters/issues/137961#issuecomment-1363957494 and I still cannot reproduce it (until I use VPN).
As I recall this website is often changing anti-adblock script (https://github.com/AdguardTeam/AdguardFilters/search?q=dropgalaxy.com&type=issues) and it's probably checked on server side. Maybe it would be better to move it to AdGuard Extra repository?

---

@adguard-bot commented on [Thu Jan 05 2023](https://github.com/AdguardTeam/AdguardFilters/issues/137961#issuecomment-1371659814)

### Issue URL (Ads)
 [https://dropgalaxy.com/yoa0rljhdsms](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fdropgalaxy.com%2Fyoa0rljhdsms)
### Comment
Username: @gototheskinny
> Malicious fake download button. Probably a malware

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/eiDvWfj.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard/AdGuard Pro for iOS v4.4.5
Browser: | Safari
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads, <br/>EasyList<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection, <br/>EasyPrivacy<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances, <br/>AdGuard Other Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard German, <br/>AdGuard Turkish

**Comment by stanislav-atr** [comment]
i wasn't able to reproduce this, @zloyden take a look, please

**Comment by XBadFellaX** [comment]
Hello, Any updates on this by chance?

**Comment by XBadFellaX** [comment]
@zloyden

**Comment by XBadFellaX** [comment]
Hello, Please any update on this? It's been a while now.

**Comment by XBadFellaX** [comment]
Any updates @stanislav-atr ?

**Comment by stanislav-atr** [comment]
@XBadFellaX, hello! SADLY, I am still unable to reproduce anti-adblock warnings. I see that you have a lot of filtering lists enabled. Have you tried disabling these one by one to try and narrow things down a bit?

**Comment by XBadFellaX** [comment]
Thank you for your response, I will do some testing today by turning off lists one by one and get back to you.

**Comment by BlazeFTL** [comment]
@XBadFellaX Could You Try This ?
<Details>

```
! MegaFuck DropGalaxy
@@*$script,domain=dropgalaxy.com
@@||dropgalaxy.com/cdn-cgi/rum?$xhr,1p
@@||challenges.cloudflare.com^$domain=dropgalaxy.com
||cloudfront.net^$script,domain=dropgalaxy.com,important
*$script,redirect-rule=noopjs,important,domain=dropgalaxy.com
*$frame,denyallow=cloudflare.com,domain=dropgalaxy.com,important
*$image,redirect-rule=32x32.png:5,domain=dragontea.ink|dropgalaxy.com
!*$frame,redirect=noopframe,important,domain=dragontea.ink|dropgalaxy.com
*$xhr,redirect-rule=noop.txt,important,domain=dragontea.ink|dropgalaxy.com
dropgalaxy.com#@#iframe
dropgalaxy.com#@#[id^="div-gpt-ad-"]
dropgalaxy.com##[id*="google_ads_iframe"]:remove()
dropgalaxy.com##[id*=a-ad]:remove()
dropgalaxy.com##.downloadPage.page.pt-5.container > center:remove()
dropgalaxy.com###vi-smartbanner:remove()
dropgalaxy.com##div[id*="gpt-ad"]:remove()
dropgalaxy.com#@#[id^="div-gpt-ad-"], #vi-smartbanner, div[id][tr-id]:style(pointer-events: none !important; filter: opacity(0) !important;)
dropgalaxy.com##[id^="TR-"]:remove()
dropgalaxy.com##[id^="lk"]:remove()
dropgalaxy.com##div.adsbyvli:remove()
dropgalaxy.com###apkad2:remove()
dropgalaxy.com##.btn-danger.btn-lg.btn-block.btn:remove()
dropgalaxy.com##.mb-1.pr-5.btn-block.btn-danger.btn:remove()
@@||adoto.net^$script,domain=dropgalaxy.com
@@||doubleclick.net^$script,domain=dropgalaxy.com
dropgalaxy.com#@#iframe[data-aa]
dropgalaxy.com#@%#//scriptlet("abort-current-inline-script", "globalThis", "break;case")
dropgalaxy.com#@#div[id^="div-gpt-ad"]
```

</Details>

**Comment by stanislav-atr** [comment]
@XBadFellaX, hi, any luck turning filters off?

**Comment by XBadFellaX** [comment]
Hi @stanislav-atr, so I did some extensive testing and it seems like the culprit is the combination of Adguard Base Filter and Adguard Annoyances Filter.

As soon as I turn both of these on or either one dropgalaxy starts detecting Adguard.

Let me know if you need more info.

Thanks

**Comment by zloyden** [comment]
@stanislav-atr @jellizaveta https://github.com/AdguardTeam/AdguardFilters/issues/171489.

**Comment by abidjauhar17** [comment]
@stanislav-atr @jellizaveta any update?

**Comment by jellizaveta** [comment]
https://github.com/AdguardTeam/AdGuardExtra/issues/508
https://github.com/AdguardTeam/AdGuardExtra/issues/506

**Comment by jellizaveta** [comment]
Hello. I would like to kindly inform that this website has been updated for the beta version of the Extra extension and userscript.

**Comment by abidjauhar17** [comment]
> Hello. I would like to kindly inform that this website has been updated for the beta version of the Extra extension and userscript.

How do I check the latest updates on the Extra extension?
because it doesn't solve the problem
![image](https://github.com/AdguardTeam/AdGuardExtra/assets/37255346/6343da1e-ea1a-4793-b049-8f674b6c62ae)

**Comment by abidjauhar17** [comment]
@jellizaveta how?
its still detected, even with new devuploads website template
![image](https://github.com/AdguardTeam/AdGuardExtra/assets/37255346/05a60593-1ff8-4850-aa97-ab703aeae734)

**Comment by jellizaveta** [comment]
@abidjauhar17 My post was about the beta version and the previous template. It looks like the page code has been changed, and now the anti-adblock is repeating. I'll try to fix it soon.

**Comment by jellizaveta** [comment]
@abidjauhar17 Hello. Beta version has been updated, please check the site with it.

**Comment by abidjauhar17** [comment]
@jellizaveta  I've updated the beta version, but it's still not resolved
![image](https://github.com/AdguardTeam/AdGuardExtra/assets/37255346/8648fe21-8589-412a-82aa-8699f811f5b9)

**Comment by jellizaveta** [comment]
I can't reproduce on my end anymore. What link are you using?

<details><summary>Screenshot:</summary>

<img width="1471" alt="Screenshot 2024-05-17 at 2 47 27 PM" src="https://github.com/AdguardTeam/AdGuardExtra/assets/91964807/94bfa048-4f56-4af8-a103-2edaa8c26be5">

</details><br/>

**Comment by jellizaveta** [comment]
For all domains, it works as expected on my end. Please try clearing your cookies, restarting your browser and checking the page again. If it doesn't work — please send a link to check.

<details><summary>Screenshot:</summary>

<img width="1132" alt="Screenshot 2024-05-17 at 3 07 15 PM" src="https://github.com/AdguardTeam/AdGuardExtra/assets/91964807/6b52d033-af7e-4bda-b1a7-eb591b5bb634">
<img width="1087" alt="Screenshot 2024-05-17 at 3 08 14 PM" src="https://github.com/AdguardTeam/AdGuardExtra/assets/91964807/e3018cd7-9c17-4422-bfbc-8cb7feacf410">
<img width="982" alt="Screenshot 2024-05-17 at 3 08 52 PM" src="https://github.com/AdguardTeam/AdGuardExtra/assets/91964807/42a29f2f-b8dc-4679-951a-eb987bfdde79">

</details><br/>

**Comment by abidjauhar17** [comment]
@jellizaveta still not working, I use opera browser
can you try it too

<details><summary></summary>
<p>

![image](https://github.com/AdguardTeam/AdGuardExtra/assets/37255346/baed4422-90fc-4f62-a11c-ac06554308e8)


</p>
</details>

**Comment by piquark6046** [comment]
Did you disable Opera browser's built-in adblocker?

**Comment by abidjauhar17** [comment]
> Did you disable Opera browser's built-in adblocker?

yeah that's for sure. I only use Adguard as an adblocker
I have never used Opera's built-in adblocker since I found out there was Adguard

**Comment by abidjauhar17** [comment]
@jellizaveta is there another solution?

**Comment by jellizaveta** [comment]
@abidjauhar17 Hi. I checked with Indonesian IP address, but unfortunately I didn't get the anti-adblock repeated. I use this link to check: `https://devuploads.com/2x5b24fz04fh`
Could you please share your link to check, on all my past links it is not repeated?
Maybe it really is blocked due to location. Could you also check in a different browser, like chrome?

**Comment by abidjauhar17** [comment]
@jellizaveta I tried with this link
https://devuploads.com/rousat38fiqd

**Comment by abidjauhar17** [comment]
> @abidjauhar17 Hi. I checked with Indonesian IP address, but unfortunately I didn't get the anti-adblock repeated. I use this link to check: `https://devuploads.com/2x5b24fz04fh` Could you please share your link to check, on all my past links it is not repeated? Maybe it really is blocked due to location. Could you also check in a different browser, like chrome?

Recently I tried again with the VPN active, but the anti-adblock appeared again

**Comment by BlazeFTL** [comment]
> anti-adblock appeared again

You were asked to test on chrome browser?
Did you do that ?

**Comment by abidjauhar17** [comment]
> > anti-adblock appeared again
> 
> You were asked to test on chrome browser? Did you do that ?

i only use opera on my PC
I'm not used to working with chrome
so I didn't install it

**Comment by aayushbhatia06** [comment]
Still does not work
