### ISSUE TITLE
m.youtube.com (video ads)

### ISSUE THREAD

**Issue by Morpheus2077** [AdguardTeam/AdGuardExtra#409]
### Issue

Stopped blocking ads on videos

### Comment

> I'm using the [userscript](https://github.com/AdguardTeam/BlockYouTubeAdsShortcut/blob/master/dist/block-youtube-ads.user.js) from AdguardTeam/BlockYouTubeAdsShortcut, it's working fine but Extra has stopped

### Screenshot

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/57775700/215901126-285e86e7-05ab-49f8-9cdc-8711825aaccb.png)</details>

### System configuration

Information                             | Value
---                                     | ---
Operating system:                       | Android
Operating system version (Android/iOS)  | 12
Browser:                                | [Via](https://github.com/tuyafeng/Via)
AdGuard Extra version:                  | 1.0.497
Filters:                    | AdGuard Base<br/> AdGuard Mobile Ads<br/> AdGuard Tracking Protection<br/> AdGuard Social Media<br/> AdGuard Annoyances<br/><sub>All optimized version</sub>
Userscript host (AdGuard/Tampermonkey): | Native

**Comment by stanislav-atr** [comment]
@Morpheus2077, hi! Have you tried using only one of these?

**Comment by Morpheus2077** [comment]
> @Morpheus2077, hi! Have you tried using only one of these?

Yes, the version below 1.0.497 was working fine, there I found this one for iPhone/iPad...

**Comment by Morpheus2077** [comment]
Version 1.0.511 working...
