### ISSUE TITLE
lenta.ru

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdGuardExtra#41]
https://github.com/AdguardTeam/AdguardFilters/issues/42967#issuecomment-550974865
В сафари с расширением есть директ. @tvinzz попробуй этот скриптлет у себя `lenta.ru#%#//scriptlet('abort-on-property-read', 'Object.prototype.banner')`
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/68373489-1afeac80-0154-11ea-878c-1457d83314c6.png)
</details><br/>

**Comment by ameshkov** [comment]
Сафари может просто не успевать скриптлет вовремя применить, есть там такая проблема. Покажите Митяю @Mizzick

**Comment by tvinzz** [comment]
Скриптлет срабатывает. Добавляю.

**Comment by zloyden** [comment]
@tvinzz директ прорвался https://github.com/AdguardTeam/AdguardFilters/issues/42967#issuecomment-564600401, надо это правило сделать для всех платформ, попробуй у себя `lenta.ru#%#//scriptlet('abort-on-property-read', 'Object.prototype.banner')`

**Comment by Alex-302** [comment]
Check with extension with disabled Annoyances filter:
AdguardTeam/AdguardFilters#42967
