### ISSUE TITLE
yandex.ru/images

### ISSUE THREAD

**Issue by Fantom1010** [AdguardTeam/AdGuardExtra#421]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/34547864/226647160-4f39cff5-3e38-465b-95ed-ae72649335f4.png)

</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

https://yandex.ru/images/search?text=adguard%20vpn&from=tabbar

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                             | Value
---                                     | ---
Operating system:                       | ?
Operating system version (Android/iOS)  | ?
Browser:    Yandex 23.1.5.708                           | ?
AdGuard version:              Adguard 4.1.53          | ?
Filters enabled:                        | ?
Userscript host (AdGuard/Tampermonkey): Extra 1.0.505| ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by MaximusPanin** [comment]
This is some new advertising bullshit. In Yandex, TV also began to appear from above.

![2023-3-23 13-24-2](https://user-images.githubusercontent.com/24373505/227189390-d9d58fdc-8668-495b-a644-7c16f6456b02.png)
