### ISSUE TITLE
maps.yandex.ru

### ISSUE THREAD

**Issue by Fantom1010** [AdguardTeam/AdGuardExtra#424]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/34547864/227329401-17d625a4-6eb0-4834-aa37-48495b2039b8.png)

</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                             | Value
---                                     | ---
Operating system:           Windows            | ?
Operating system version (Android/iOS)  | ?
Browser:            Yandex 23.1.5                    | ?
AdGuard version:               Adguard 4.1.53         | ?
Filters enabled:                        | ?
Userscript host (AdGuard/Tampermonkey): |Extra 1.0.506

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by stanislav-atr** [comment]
@Fantom1010, добрый день! Не воспроизводится этот баннер, какие фильтры включены в AdGuard? Включен ли vpn?
