### ISSUE TITLE
https://dzen.ru

### ISSUE THREAD

**Issue by Fantom1010** [AdguardTeam/AdGuardExtra#427]
https://dzen.ru/a/ZCXY8k2Lwi5O_HYT
![image](https://user-images.githubusercontent.com/34547864/229042996-2cb493fe-e478-448e-9e05-d144abb07072.png)
Используются расширения Adguard антибаннер 4.1.53 и Adguard Extra  1.0.511 в Яндекс браузере. Фильтры базовый и русский. Adguard DoH в настройках браузера.

_Originally posted by @Fantom1010 in https://github.com/AdguardTeam/AdGuardExtra/issues/419#issuecomment-1491394110_

**Comment by stanislav-atr** [comment]
@Fantom1010, добрый день! Какие фильтры включены? Экстра расширение или юзерскрипт?

**Comment by stanislav-atr** [comment]
Так и не повторился баннер, @zloyden посмотри, пожалуйста:
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/68852737/232026705-e4848455-bad1-4109-971c-b7f48690bc09.png)
</details><br/>

**Comment by zloyden** [comment]
У меня отображается похожий баннер, но он блокируется успешно AdGuard Extra.
Для яндекс браузера лучше использовать программу, поскольку известно, что он блокирует доступ к своим сервисам расширениям.
