### ISSUE TITLE
Great facebook.com but Not working m.facebook.com 

### ISSUE THREAD

**Issue by bzdzz** [AdguardTeam/AdGuardExtra#428]
Simple: on android Chrome Kiwi browser extention with desktop mode facebook.com blocks ads but not working to block ads when in non-desktop setting to m.facebook.com

Suggested fix: enable for m.facebook.com the mobile version or else *.facebook.com for other versions

**Comment by stanislav-atr** [comment]
@bzdzz, hi and thank you for feedback. I've added `m.facebook.com` to hosts. This change is already available in beta v1.0.512 for you to check this out.

**Comment by bzdzz** [comment]
Not fixed on beta v1.0.512, perhaps the host push is separate and not live for m.facebook.com -- please double check!  Thank you.
