### ISSUE TITLE
Yandex Weather: placeholder is doubled

### ISSUE THREAD

**Issue by Sergey-Lyapin** [AdguardTeam/AdGuardExtra#441]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard Extra version is up-to-date;

### What product do you use?

AdGuard Extra with other script manager

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Where is the problem encountered?

https://yandex.ru/pogoda/month?lat=55.755863&lon=37.6177&via=hnav

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

The placeholder is doubled when Extra is on.

<details><summary>Screenshot N:</summary>

![Pogo](https://github.com/AdguardTeam/AdGuardExtra/assets/18536328/9dae1988-fedf-4a7b-920e-c959e3438332)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by stanislav-atr** [comment]
Not reproduced, @zloyden take a look, please

**Comment by zloyden** [comment]
Also not reproduced it on my end. Checked it with AdGuard Extra 1.0.527 and the config above.
<details><summary>Screenshot:</summary>

![image](https://github.com/AdguardTeam/AdGuardExtra/assets/33488229/5d90c3ac-9052-46e6-a119-d3cf5c7181a2)

</details><br/>
@Sergey-Lyapin could you please write steps to reproduce this in detail?

**Comment by Sergey-Lyapin** [comment]
@zloyden
Open the link in a new incognito tab and log in.

**Comment by zloyden** [comment]
@stanislav-atr if you [do that](https://github.com/AdguardTeam/AdGuardExtra/issues/441#issuecomment-1554327859), you can reproduce it.

**Comment by stanislav-atr** [comment]
This is still not reproducible for me 

<details><summary>Screenshot:</summary>

![image](https://github.com/AdguardTeam/AdGuardExtra/assets/68852737/a65b01da-8ef6-43d6-92c3-ee590a46eadf)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
I can't reproduce this issue neither anymore.
