### ISSUE TITLE
Flash banners block visibility test fails after last update

### ISSUE THREAD

**Issue by arturstat** [AdguardTeam/AdGuardExtra#442]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard Extra version is up-to-date;

### What product do you use?

AdGuard for Android, AdGuard Extra Extension

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome, Microsoft Edge

### Where is the problem encountered?

https://adblock-tester.com/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Chinese filter, AdGuard Dutch filter, AdGuard French filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter, Filter unblocking search ads and self-promotion

### Add your comment and screenshots

Flash banners block visibility test fails on https://adblock-tester.com/
Used to get 100 points out of 100. After last update I get 96 points out of 100.

### Privacy

- [X] I agree to follow this condition

**Comment by stanislav-atr** [comment]
@arturstat, hi! Could you please try reproducing the issue with AdGuard Extra turned off? I'm seeing the same results regardless of whether it's enabled or disabled.

**Comment by arturstat** [comment]
Yes I am having the same issue with adguard extra turned off. The issue must be related to something with the adguard extension or its filters.

**Comment by arturstat** [comment]
Can you move this issue to the AdguardBrowserExtension?
https://github.com/AdguardTeam/AdguardBrowserExtension/issues

**Comment by arturstat** [comment]
Actually, the issue lies not in adguardextra, but in adguard itself. After further investigation, I believe I found how to reproduce the issue. In the browser extension, go to "Additional settings", then enable "Use optimized filters". When I enable this setting, the Flash banners block visibilty test fails. Please try. Thanks a lot!

**Comment by stanislav-atr** [comment]
@arturstat Filters are being optimized by disabling less frequently used filtering rules. This will inevitably impact the tester's score.

**Comment by arturstat** [comment]
Thanks. It is intentional then. One just has to disable "Use optimized filters" under "Additional settings".

**Comment by arturstat** [comment]
I decided to try adguard for android again. I don't have this issue anymore using the Edge browser extension. But I still get this under android. I don't know of any android option which can fix this.

**Comment by arturstat** [comment]
The android app is using mobile optimized filters by default. I see this is intentional, therefore it is a non issue. Please disregard my previous comments. Thank you.
