### ISSUE TITLE
https://www.twitch.tv/eray

### ISSUE THREAD

**Issue by Atalayozyldrm** [AdguardTeam/AdGuardExtra#453]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard Extra version is up-to-date;

### What product do you use?

Adguard for Windows

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Where is the problem encountered?

https://www.twitch.tv/eray

### What filters do you have enabled?

AdGuard Turkish filter

### Add your comment and screenshots

1. <comment>
Adguard extra plugin twitch.com misses ads, doesn't block
2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by stanislav-atr** [comment]
Moving this into #383

**Comment by Atalayozyldrm** [comment]
same problem
