### ISSUE TITLE
pussyspace.com

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdGuardExtra#454]
https://github.com/AdguardTeam/AdguardFilters/issues/156405

**Comment by zloyden** [comment]
@stanislav-atr ads appear again https://github.com/AdguardTeam/AdguardFilters/issues/157350#issuecomment-1654568618.
In case you can't reproduce it, @kodiakhub can.

**Comment by stanislav-atr** [comment]
Website blocks visitors on open devtools now.
