### ISSUE TITLE
Add an option to exclude any or more of the websites in the AdGuard Extra List

### ISSUE THREAD

**Issue by kodiakhub** [AdguardTeam/AdGuardExtra#455]
### Prerequisites

- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

For example for Twitch website, even if AdGuard Extra blocks Twitch ads, the rest leftovers (The `Preparing your stream` and the `Commercial Break` screens) are annoying, to get through this especially for mid-rolls we have need to reset the player (with FrankerFaceZ extension) or refresh the page or it goes buffering forever. 

So, we use more effective solutions for Twitch. But we want to keep AdGuard Extra open for Facebook, Youtube and other websites available. Because currently using AdGuard Extra at the same time with other Twitch solutions breaks the functionality of other solutions. Thanks in advance. 👍 

### Proposed solution

**In the title.**

**Comment by Iowerth** [comment]
I need this option too, because my scenario is - block ads on only sites I choose myself.

**Comment by Alex-302** [comment]
It can be done in extension settings of Chrome
<details>
<summary>Details</summary>

![image](https://github.com/AdguardTeam/AdGuardExtra/assets/8361299/a81be132-4a69-42e3-9dc0-2aad02387ed1)


</details>

**Comment by Iowerth** [comment]
@Alex-302 I'm using Firefox, there is no such option.

**Comment by Alex-302** [comment]
In the app or tampermonkey you can exclude or include domains using editor.

Remove
```
// @include *
```
and add lines like this for required domains.
```
// @include *example.com*
```
