### ISSUE TITLE
spotify.com/open.spotify.com

### ISSUE THREAD

**Issue by Pierre2004** [AdguardTeam/AdGuardExtra#456]
### Prerequisites

- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

When you want to listen to music for free, there are ads.

### Proposed solution

Block and ignore ads

**Comment by maximtop** [comment]
This issue can be solved by rules, could you please report details here 
https://reports.adguard.com/en/new_issue.html
