### ISSUE TITLE
client.falixnodes.net

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardExtra#457]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard Extra version is up-to-date;

### What product do you use?

Adguard for Windows, AdGuard Extra Extension

### What type of problem have you encountered?

AdGuard Extra gets detected on a website

### Which browser(s) do you use?

Chrome

### Where is the problem encountered?

https://client.falixnodes.net

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

Original issue https://github.com/AdguardTeam/AdguardFilters/issues/157465

Account is required.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

![image](https://github.com/AdguardTeam/AdGuardExtra/assets/8361299/f8622da1-5021-4502-bbad-694b8ccb5cb3)

  ![Screenshot 1](https://cdn.adguard.info/sitereports/pqi744lhrr4wccgkowgs8s88088wkokfaskmyox6c0.png?nc=1)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://cdn.adguard.info/sitereports/1b57h3agjyqssggw4w4g04okw44kwg60q68aiae6ko.png?nc=1)
</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Roki100** [comment]
It detected my privacy badger, seems like allowing this domain solves the issue:
![image](https://github.com/AdguardTeam/AdGuardExtra/assets/35699619/54e311a3-1f80-4064-85d4-914a63779d8a)

**Comment by stanislav-atr** [comment]
Resolved with filters.
