### ISSUE TITLE
Youtube upcoming adblock strikes

### ISSUE THREAD

**Issue by CrazyWolf13** [AdguardTeam/AdGuardExtra#458]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard Extra version is up-to-date;

### What product do you use?

AdGuard for Android, AdGuard Extra Extension, AdGuard Extra with other script manager

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox, Chrome, Opera

### Where is the problem encountered?

https://www.youtube.com

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard German filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard DNS filter, EasyList, EasyList Germany

### Add your comment and screenshots

Will we get Youtube support and some sort of anti-strike system, because youtube is testing anti adblockers which strike you and on three your account is banned from youtube.

### Privacy

- [X] I agree to follow this condition

**Comment by Dark3n89** [comment]
> > Where the fuck did you find that info out?
> > Don't be stupid, they will not ban you from YouTube from using a fucking adblocker.
> > I reckon they'd open the door for some class-action lawsuits if they did something as stupid as that.
> 
> Some simple web search would have proofen you wrong.
> 
> https://adguard.com/en/blog/ad-blockers-youtube-ban.html

Youtube aka google only try fear with their API, dont update your browser and you can chill lol :D Chromium is dead.

**Comment by CrazyWolf13** [comment]
> > > Where the fuck did you find that info out?
> > > Don't be stupid, they will not ban you from YouTube from using a fucking adblocker.
> > > I reckon they'd open the door for some class-action lawsuits if they did something as stupid as that.
> > 
> > Some simple web search would have proofen you wrong.
> > 
> > https://adguard.com/en/blog/ad-blockers-youtube-ban.html
> 
> Youtube aka google only try fear with their API, dont update your browser and you can chill lol :D Chromium is dead.
> New scam methods block web_requests, thats all :D

I don't see any connection to chromium or their api. I suggest glasses and a quick break to read the article again. 😉

**Comment by Dark3n89** [comment]
> > > > Where the fuck did you find that info out?
> > > > Don't be stupid, they will not ban you from YouTube from using a fucking adblocker.
> > > > I reckon they'd open the door for some class-action lawsuits if they did something as stupid as that.
> > > 
> > > 
> > > Some simple web search would have proofen you wrong.
> > > https://adguard.com/en/blog/ad-blockers-youtube-ban.html
> > 
> > 
> > Youtube aka google only try fear with their API, dont update your browser and you can chill lol :D Chromium is dead.
> > New scam methods block web_requests, thats all :D
> 
> I don't see any connection to chromium or their api. I suggest glasses and a quick break to read the article again. 😉

Yes, you can't see anything because you're not a developer and you don't understand how it works and what I'm saying, so I won't explain anything to you. It's just that chromium blocks the web_request api, if you don't know what it is and what it's for, it's useless for you to comment on anything.

**Comment by Lather0519** [comment]
I saw it today, It make a little note windows saids "seems you enable a adblocker balabala, pls disable and use YouTube Premium to disable ad"
![1](https://github.com/AdguardTeam/AdGuardExtra/assets/32637838/b47659c8-da32-497d-ae05-ccf417382fe4)
![2](https://github.com/AdguardTeam/AdGuardExtra/assets/32637838/dfc33788-2806-4c77-a8e8-dd543ce92b9d)

**Comment by CrazyWolf13** [comment]
![image](https://github.com/AdguardTeam/AdGuardExtra/assets/96661824/f6f3de3f-2b54-4535-952f-9114039acedd)
Youtube finally rolled out to a big part of the world, @LukeSaward1 @Dark3n89 I'm waiting for an explanation to your comments above.

**Comment by CrazyWolf13** [comment]
@maximtop  FYI after clicking allow ads there was a small iframe like 10x10cm rendered on top of the video to some google domain, I guess to test for adblocker?

**Comment by Dark3n89** [comment]
> ![image](https://user-images.githubusercontent.com/96661824/274664980-f6f3de3f-2b54-4535-952f-9114039acedd.png) Youtube finally rolled out to a big part of the world, @LukeSaward1 @Dark3n89 I'm waiting for an explanation to your comments above.

I repeat again what I said, you must not have the update enabled, all browsers work on the basis of chromium. Google disabled access to web_request and now it is very easy to defend against ad blockers.

A very easy way is to install the standalone version of google chrome, everything works perfectly, only google is not integrated inside, you will have to log in manually everywhere, automatic login will not work.


I have an online and an offline version of the old chrome with my own blockers that I'm working on + extensions: ghostery (with settings inside), old version of adguard.

My primary script block all advertising web_requests, even before loading.

![image](https://github.com/AdguardTeam/AdGuardExtra/assets/48175529/9c26d78d-f60a-4fad-9d5e-dc33226f945c)

**Comment by CrazyWolf13** [comment]
> > ![image](https://user-images.githubusercontent.com/96661824/274664980-f6f3de3f-2b54-4535-952f-9114039acedd.png) Youtube finally rolled out to a big part of the world, @LukeSaward1 @Dark3n89 I'm waiting for an explanation to your comments above.
> 
> I repeat again what I said, you must not have the update enabled, all browsers work on the basis of chromium. Google disabled access to web_request and now it is very easy to defend against ad blockers.
> 
> A very easy way is to install the standalone version of google chrome, everything works perfectly, only google is not integrated inside, you will have to log in manually everywhere, automatic login will not work.
> 
> I have an online and an offline version of the old chrome with my own blockers that I'm working on + extensions: ghostery (with settings inside), old version of adguard.
> 
> My primary script block all advertising web_requests, even before loading.
> 
> ![image](https://user-images.githubusercontent.com/48175529/274824579-9c26d78d-f60a-4fad-9d5e-dc33226f945c.png)

Seems pretty neat, is there a way to implement this to opera gx?

**Comment by CrazyWolf13** [comment]
exact url which youtube seems to test if there are no adblockers is
"fundingchoices.google.com"
![image](https://github.com/AdguardTeam/AdGuardExtra/assets/96661824/22be939d-9c60-4ae9-b303-8256e751d05b)
![image](https://github.com/AdguardTeam/AdGuardExtra/assets/96661824/90e4715a-0332-4792-960e-225c96db3b1d)
![image](https://github.com/AdguardTeam/AdGuardExtra/assets/96661824/ea3ff913-b188-4c14-a192-6753471ccad4)
![image](https://github.com/AdguardTeam/AdGuardExtra/assets/96661824/4227d4a1-844d-4e5d-bb47-7592c6d6dbcd)

Hope this is helpful for anyone.

**Comment by Dark3n89** [comment]
really no this link :)  
![image](https://github.com/AdguardTeam/AdGuardExtra/assets/48175529/36eccb13-1d83-4f65-a6a4-422650202c93)

Here is lot of testing and non testing items, here is my list of clear items 
![image](https://github.com/AdguardTeam/AdGuardExtra/assets/48175529/1b0d4e4c-54d9-43de-a376-a01cb6dd6e18)

**Comment by CrazyWolf13** [comment]
> really no this link :) ![image](https://user-images.githubusercontent.com/48175529/274872864-36eccb13-1d83-4f65-a6a4-422650202c93.png)
> 
> Here is lot of testing and non testing items, here is my list of clear items ![image](https://user-images.githubusercontent.com/48175529/274873248-1b0d4e4c-54d9-43de-a376-a01cb6dd6e18.png)

Looks great, can this be merged into AdblockExtra when complete?

**Comment by Yuki2718** [comment]
Auto-clicking of ads should now be removed as yt detects this.

**Comment by Dark3n89** [comment]
> Auto-clicking of the skip button should now be removed as yt detects this.

If you see any ADS  all is wrong lol, star from begin :D

**Comment by Yuki2718** [comment]
I am a filter maintainer of AdGurad filters who address all these youtube staff. I know the current filters get rid of ads well; nevertheless, auto-click which was originally implmented as fallback should be deactivated as now it causes detection.

**Comment by ameshkov** [comment]
@Yuki2718 what about a different approach? See this one: https://github.com/rkk3/ad-accelerator

**Comment by CrazyWolf13** [comment]
> I am a filter maintainer of AdGuard filters who address all these youtube staff. I know the current filters get rid of ads well; nevertheless, auto-click which was originally implmented as fallback should be deactivated as now it causes detection.

Okay great.
Yeah the current one seems to work quite well, if adguard is disabled and adguard extra is enabled. Except for some seonds blackscreen on videos. Probably because of instant skip?

**Comment by Yuki2718** [comment]
> what about a different approach? See this one: https://github.com/rkk3/ad-accelerator

This method of skipping by x10 playback rate is currently not detected (while the skipping by FadBlock/ABP is detected if `yt.config_.EXPERIMENT_FLAGS.ab_pl_man` is `true`).

**Comment by zzebrum** [comment]
It seems a bit outdated now. If you are experiencing new problems with ads on YouTube, please either post new issues in this repo or report them to [AdGuard Filters](https://github.com/AdguardTeam/AdguardFilters).
