### ISSUE TITLE
Adguard Extra prevents Twitch streams from loading

### ISSUE THREAD

**Issue by Runkel79** [AdguardTeam/AdGuardExtra#465]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard Extra version is up-to-date;

### What product do you use?

Adguard for Windows

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Where is the problem encountered?

https://www.twitch.tv/

### What filters do you have enabled?

AdGuard Base filter, AdGuard German filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Popups filter, EasyList, EasyPrivacy, Adblock Warning Removal List

### Add your comment and screenshots

1. <comment>
https://www.twitch.tv stream do not load.

After turning off all my browser extensions one by one, I found that Adguard Extra is the culprit. When I turn it off, the streams load normally. 

According to Chrome Web Store the latest update of Adguard Extra was today, maybe there's a small bug in the latest update preventing twitch Streams to load? Or Twitch changed something again.

2. Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdGuardExtra/assets/22620131/02a15b3e-e78e-4616-8570-b7785e590bf1)

</details>

<details><summary>Screenshot N:</summary>

![image](https://github.com/AdguardTeam/AdGuardExtra/assets/22620131/db2f1441-86fb-4fa3-b4a1-dc8dcc0fa312)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by goproslowyo** [comment]
👀 yeap, same as all the comments in #383.

**Comment by dragothica** [comment]
I also have this issue. It started yesterday. I'm using Firefox with AdGuard Extra (Userscript, no Beta). I'm also using uBlockOrigin and disabling either uBlockOrigin or AdGuard Extra allows the Twitch Player to load, but if both blockers are loaded, the stream won't load. Previously I could have both blockers enabled and Twitch was working just fine.

**Comment by stanislav-atr** [comment]
@goproslowyo @dragothica 
Beta version has been tweaked to prevent running Extra if other scripts interfere for cases where Extra is running with desktop AG or uBlock. Looking forward to your feedback.

**Comment by goproslowyo** [comment]
Hey @stanislav-atr I can confirm that it's fixed now on the AGE Beta. I disabled beta, re-enabled stable, and confirmed it was broken again as a sanity test as well.

Thanks for both your work and the quick fix!

**Comment by stanislav-atr** [comment]
@goproslowyo we will be moving this fix to release version then, thank you for you feedback.
