### ISSUE TITLE
dzen.ru/video

### ISSUE THREAD

**Issue by Fantom1010** [AdguardTeam/AdGuardExtra#466]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard Extra version is up-to-date;

### What product do you use?

AdGuard Extra Extension

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Yandex Browser

### Where is the problem encountered?

https://dzen.ru/video/watch/64c0acfb69d16c6703b4f23c

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter

### Add your comment and screenshots

1. <Реклама в плеере и в превью и в полноэкранном.>

2. Screenshots
![image](https://github.com/AdguardTeam/AdGuardExtra/assets/34547864/d4e9dc2d-51b7-4836-b3f0-e479f67c685e)

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Рекламы тоже не наблюдаю у себя.

**Comment by stanislav-atr** [comment]
@Fantom1010 используется ли vpn или другой блокировщик рекламы?

**Comment by stanislav-atr** [comment]
@Fantom1010 все так же не воспроизводится. Попробуйте установить расширение Adguard и экстру на чистую установку хрома. Воспроизводится только с аккаунтом, или в инкогнита без логина тоже?

**Comment by jellizaveta** [comment]
Проверила в режиме инкогнито - реклама не повторилась.

**Comment by zloyden** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/168381#issuecomment-1869542113.
