### ISSUE TITLE
championat.com

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdGuardExtra#467]
Broken comments -> https://github.com/AdguardTeam/AdguardFilters/issues/162302.

**Comment by stanislav-atr** [comment]
@zloyden i can reproduce this without AdGuard Extra

**Comment by zloyden** [comment]
Is this a site bug or what? It's kinda a strange one, because in FF + AdGuard Extra Beta / Release 1.0.545 via AdGuard for Windows I always get this when opening an article with comments. For instance, [this one](https://www.championat.com/tennis/news-5252318-stala-izvestna-pervaya-chetvyorka-tennisistok-kvalificirovavshihsya-na-itogovyj-turnir-wta.html).

<details><summary>AdGuard Extra enabled:</summary>

![image](https://github.com/AdguardTeam/AdGuardExtra/assets/33488229/b0d0885a-9396-4054-ae56-66ac6034729a)

</details><br/>

<details><summary>AdGuard Extra disabled:</summary>

![image](https://github.com/AdguardTeam/AdGuardExtra/assets/33488229/d1745ddb-7b44-4d4b-89ad-c278414f5e67)

</details><br/>
