### ISSUE TITLE
doesn't work on youtube anymore

### ISSUE THREAD

**Issue by ayoubelyazizi** [AdguardTeam/AdGuardExtra#477]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard Extra version is up-to-date;

### What product do you use?

AdGuard Extra Extension

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Where is the problem encountered?

youtube.com

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

1. <comment>

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by stanislav-atr** [comment]
@ayoubelyazizi hi! Extra script for youtube was triggering new youtube anti-adblock system and was removed. Right now AdGuard Base filter is working fine, please, ensure that Adguard browser extension is working and AdGuard Base filter is enabled.
