### ISSUE TITLE
ya.ru

### ISSUE THREAD

**Issue by Fantom1010** [AdguardTeam/AdGuardExtra#481]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard Extra version is up-to-date;

### What product do you use?

AdGuard Extra Extension

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Yandex Browser

### Where is the problem encountered?

https://ya.ru

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

1. <comment>

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@Fantom1010 Сохранённая страница нужна. У меня боковой баннер никогда не повторялся, даже без блокировщика.
