### ISSUE TITLE
Adguard still does not block ads on Twitch

### ISSUE THREAD

**Issue by Brando813** [AdguardTeam/AdGuardExtra#487]
Hello, this issue has still not been resolved since I opened it a few weeks ago.  Updating filters does not solve it and ads play on both the Twitch site and app with Adguard enabled.

_Originally posted by @Brando813 in https://github.com/AdguardTeam/AdGuardExtra/issues/475#issuecomment-1854587356_

**Comment by Brando813** [comment]
![Screenshot_20231227_165357_Twitch](https://github.com/AdguardTeam/AdGuardExtra/assets/151312462/24c6c425-33a3-42a2-ba4d-e5eb5ac5ff34)
![Screenshot_20231227_165409_Twitch](https://github.com/AdguardTeam/AdGuardExtra/assets/151312462/c7070b24-fa49-430a-85fb-cfedb5474c53)
![Screenshot_20231227_165415_Twitch](https://github.com/AdguardTeam/AdGuardExtra/assets/151312462/91d2f84b-c9af-4bfa-af3d-81e7c225271d)
Everytime you join a channel on the Twitch app or while on Twitch.tv, you see ads playing.  Adguard used to block this but it seems Amazon has got around this now.

**Comment by goproslowyo** [comment]
Confirmed, AGE no longer blocking Twitch ads the last week or so.

**Comment by Samuxle** [comment]
I hope that very soon you will be able to solve the problem of the advertisements that start anyway
