### ISSUE TITLE
Facebook showing ads with AdGuard Extra + AdGuard AdBlocker + AdBlock Page Firefox 121.0.1

### ISSUE THREAD

**Issue by michaelboatright** [AdguardTeam/AdGuardExtra#490]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard Extra version is up-to-date;

### What product do you use?

Adguard for Mac

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox

### Where is the problem encountered?

https://www.facebook.com

### What filters do you have enabled?

AdGuard Base filter, AdGuard Chinese filter, AdGuard Dutch filter, AdGuard French filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

1. <comment>

2. Screenshots
<details><summary>Screenshot 1:<code>https://www.facebook.com/?sk=h_chr</code></summary>

<img width="1735" alt="image" src="https://github.com/AdguardTeam/AdGuardExtra/assets/156264995/320c1879-8cf9-4bf7-9613-85b51636c8a3">

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Cannot reproduce this issue on my end. The page at the link opens in full.
