### ISSUE TITLE
Facebook still sneaking ads in as posts - looks like it detects AdGuard and takes overt action

### ISSUE THREAD

**Issue by michaelboatright** [AdguardTeam/AdGuardExtra#492]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard Extra version is up-to-date;

### What product do you use?

Adguard for Mac

### What type of problem have you encountered?

Missed ads or ad leftovers, AdGuard Extra gets detected on a website

### Which browser(s) do you use?

Firefox

### Where is the problem encountered?

https://www.facebook.com

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

1. <comment>
I know that bug team has had troubles recreating, but from the Firefox debugger, it's pretty clear that Facebook is detecting ad blocking and taking overt action to disguise an ad. I don't know enough about FB coding to understand what they are doing, but it's clear it is detecting AdBlocking, with or with ABP on, that is, ONLY with AdGuard and AdGuardExtra on, neither of which are catching the posted ad. Adding 2 screen shots with Firefox Debugger on, one with ABP+AdGuard+AdGuardExtra and one with ABP turned off for FB. Firefox 121.0.1; MacOS 12.7.2 Monterey; ABP 3.22.1, AdGuard Browser extension: Version 4.2.241 TSWebExtension v1.0.5 TSUrlFilter v2.2.8 Scriptlets v1.9.101 ExtendedCss v2.0.56 (All Default filters turned on) AdGuardExtra 1.0.571
</comment>
2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot 1 w/ AdBlockPage ON, AdGuard ON AdGuardExtra ON:</summary>
![image](https://github.com/AdguardTeam/AdGuardExtra/assets/156264995/27b358f1-beda-4d76-8d08-3e1b8b643944)
<summary>Screenshot 2w/ AdBlockPage OFF, AdGuard ON AdGuardExtra ON:</summary>
![image](https://github.com/AdguardTeam/AdGuardExtra/assets/156264995/7f7b18d7-21d5-4c55-8ea5-dcc196c0d952)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
@michaelboatright Hi. Unfortunately, I cannot reproduce this issue on my end. Could you please send saved page on filters@adguard.com with issue number in subject line?

**Comment by michaelboatright** [comment]
I sent it over an hour ago. Also, please ensure you are using this FB url (unfiltered news feed): https://www.facebook.com/?filter=all&sk=h_chr

**Comment by michaelboatright** [comment]
Resent file with subject line: Issue #492

**Comment by michaelboatright** [comment]
mx.google.com rejected your message to the following email addresses:

[filters@adguard.com (filters@adguard.com)](mailto:filters@adguard.com)
Your message wasn't delivered because the recipient's email provider rejected it.
I saved the page as you requested. HTML + content, and zipped it so it could be sent, rejected:
mx.google.com gave this error:
This message was blocked because its content presents a potential security issue. To review our message content and attachment content guidelines, go to https://support.google.com/mail/?p=BlockedMessage y20-20020a05622a121400b0042a1c8ffe11si1688342qtx.35 - gsmtp

**Comment by jellizaveta** [comment]
@michaelboatright Could you try a different email client?
