### ISSUE TITLE
yandex.com

### ISSUE THREAD

**Issue by jellizaveta** [AdguardTeam/AdGuardExtra#496]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard Extra version is up-to-date;

### [NSFW] Screenshots
<details>
  <summary>Screenshot 1</summary>

  [Screenshot 1](https://cdn.adguard.info/sitereports/rrex0vyeny8w44o0sgs44ws84sog8o8d4vict1l5fc.png?nc=1)
</details>

### System configuration

Information | Value
--- | ---
AdGuard product: | AdGuard Browser Extension v4.3.13
System version: | Windows 10
Browser: | Chrome
Stealth mode: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances, <br/>Adblock Warning Removal List<br/><br/><b>Language-specific:</b><br/>AdGuard Russian
Other extensions used: | Kaspersky Endpoint Security 11, Tampermonkey (Adguard Extra)

### Privacy

- [X] I agree to follow this condition

**Comment by stanislav-atr** [comment]
this is not reproducible on my side anymore, @jellizaveta can you confirm this?
