### ISSUE TITLE
check-host.net: ads

### ISSUE THREAD

**Issue by rodrigosambadesaa** [AdguardTeam/AdGuardExtra#497]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard Extra version is up-to-date;

### What product do you use?

AdGuard Extra Extension

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Where is the problem encountered?

https://check-host.net/

### What filters do you have enabled?

AdGuard Base filter, ---Third-party filters---

### Add your comment and screenshots

1. <comment> Ads are shown on the site

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by stanislav-atr** [comment]
@rodrigosambadesaa, hi! Ads on check-host.net are being currently blocked with AdGuard Base filter of browser extension. Could you please update your filters and/or fix the screenshots?

**Comment by rodrigosambadesaa** [comment]
Hi,

Adguard is not my main ad blocking extension.

It was my error.

Best wishes,

Rodrigo
