### ISSUE TITLE
Reporting an Issue with Extra Adblock on Twitch TV

### ISSUE THREAD

**Issue by juniorninjutso** [AdguardTeam/AdGuardExtra#499]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard Extra version is up-to-date;

### What product do you use?

AdGuard Extra Extension, AdGuard Extra with other script manager

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Where is the problem encountered?

https://www.twitch.tv/

### What filters do you have enabled?

AdGuard Spanish/Portuguese filter

### Add your comment and screenshots

I would like to report a problem with the extra adblock on Twitch TV. When the extension is activated with the Tampermoinkey script, the stream starts to lag.

### Privacy

- [X] I agree to follow this condition

**Comment by Slipi089** [comment]
I have the same problem with the browser extension
