### ISSUE TITLE
Issue with Extra Adblock Firefox on Twitch TV

### ISSUE THREAD

**Issue by mitchpitchfork** [AdguardTeam/AdGuardExtra#502]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard Extra version is up-to-date;

### What product do you use?

AdGuard Extra Extension

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Where is the problem encountered?

https://www.twitch.tv/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard Annoyances filter, EasyList, EasyPrivacy, Peter Lowe's Blocklist, Online Malicious URL Blocklist

### Add your comment and screenshots

The Twitch player will load roughly 30 seconds of the stream, and stop. Loading will resume after reloading the player/page, but only for another 30 seconds. All ads are blocked, only the infinite buffering is the issue.

### Privacy

- [X] I agree to follow this condition

**Comment by githubuser013** [comment]
Me too, i have the same issue here.
I notice that the firefox version of extra is 1.0.582 but the chrome version and the app is 1.0.586 so maybe this is the issue.

**Comment by githubuser013** [comment]
now version 1.0.588 is out for both the app and chrome why its not out yet for firefox? there is no waiting time approval like store checking the add-ons right!?

**Comment by TsukiZero** [comment]
Userscript, both beta and stable, are useless on TwitchTV

**Comment by stevenya97** [comment]
issue mentioned here [#243](https://github.com/pixeltris/TwitchAdSolutions/issues/243#issuecomment-2079710828)

> AdGuard Extra Twitch specific code I think is maintained by @stanislav-atr. I'm not 100% sure where the code actually resides in terms of open source stuff but you can probably report issues here https://github.com/AdguardTeam/AdGuardExtra. Looking at the userscript it's impacted by the above issue and needs fixing

**Comment by jellizaveta** [comment]
Moving this into https://github.com/AdguardTeam/AdGuardExtra/issues/383
