### ISSUE TITLE
check-host.net

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdGuardExtra#504]
https://check-host.net/
https://github.com/AdguardTeam/AdguardFilters/issues/165624#issuecomment-2031724332
<details><summary>Screenshot:</summary>

![image](https://github.com/AdguardTeam/AdGuardExtra/assets/33488229/25a54605-b194-405e-bf77-ba70b27dc68b)

</details><br/>
To reproduce it, just open the site in Chrome or other browser with AdGuard Extra enabled.

**Comment by rodrigosambadesaa** [comment]
I don't want to rush the assigned person, and I also don't believe that only one person should work on a task like this, especially considering that the owner and developers of this website have been resisting us for so long and continuously refuse to see their ads blocked. In uBlock Origin, tasks are not assigned to anyone in particular; instead, several people can contribute their ideas and help each other with commits. Without intending to offend, you all are much slower than the volunteers of uBlock Origin.
