### ISSUE TITLE
jytechs.in

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdGuardExtra#506]
https://github.com/AdguardTeam/AdguardFilters/issues/176916. It seems that it's detected. Open [this link](https://devuploads.com/2x5b24fz04fh) with a EU IP.

**Comment by jellizaveta** [comment]
Can't reproduce antiadblock on android in sumsung browser with EU IP. @piquark6046 could you please check?

**Comment by piquark6046** [comment]
Same. Cannot reproduce with Proton VPN DE#240.

**Comment by jellizaveta** [comment]
@piquark6046 Thanks for checking

**Comment by jellizaveta** [comment]
@zloyden How to reproduce?

**Comment by piquark6046** [comment]
Please try https://github.com/AdguardTeam/AdguardFilters/issues/177311 case and connect to Proton VPN KR#24.

**Comment by Samuxle** [comment]
I get ads even having extra adguard active

**Comment by jellizaveta** [comment]
Move to https://github.com/AdguardTeam/AdGuardExtra/issues/403
