### ISSUE TITLE
devuploads.com

### ISSUE THREAD

**Issue by abidjauhar17** [AdguardTeam/AdGuardExtra#508]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard Extra version is up-to-date;

### What product do you use?

AdGuard Extra Extension

### What type of problem have you encountered?

AdGuard Extra gets detected on a website

### Which browser(s) do you use?

Opera

### Where is the problem encountered?

https://djxmaza.in/using-a-google-dedicated-server/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Annoyances filter, EasyPrivacy, AdBlockID

### Add your comment and screenshots

1. AG Extra still cannot resolve devuploads domains that detect adblockers
https://devuploads.com/rousat38fiqd

<details><summary>Screenshots</summary>
<p>

![image](https://github.com/AdguardTeam/AdGuardExtra/assets/37255346/8420ce2b-21ab-4c14-85cf-cf685e3a57d3)

</p>
</details> 

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Move to https://github.com/AdguardTeam/AdGuardExtra/issues/403
