### ISSUE TITLE
4pda.to - breaks the news content on the main page

### ISSUE THREAD

**Issue by avsprv** [AdguardTeam/AdGuardExtra#511]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard Extra version is up-to-date;

### What product do you use?

AdGuard Extra Extension

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome, Yandex Browser

### Where is the problem encountered?

https://4pda.to/

</details>

</details>

### Privacy

- [x] I agree to follow this condition

**Comment by stanislav-atr** [comment]
@avsprv, hi! This is not reproduced on my side anymore, can you confirm this?

**Comment by avsprv** [comment]
> @avsprv, hi! This is not reproduced on my side anymore, can you confirm this?

I confirm, the problem seems to have already been solved.

**Comment by avsprv** [comment]
> @avsprv, hi! This is not reproduced on my side anymore, can you confirm this?

I confirm, the problem seems to have already been solved.
