### ISSUE TITLE
qwant search

### ISSUE THREAD

**Issue by fortXIV** [AdguardTeam/AdGuardExtra#515]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard Extra version is up-to-date;

### What product do you use?

AdGuard Extra Extension

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other (specify in comment below)

### Where is the problem encountered?

qwant.com (when searching)

### What filters do you have enabled?

EasyList Cookie List

### Add your comment and screenshots

1. <comment>
When I try to search something using qwant, the first search works perfectly fine. But the second one never works. Im using the latest version of brave on mac and aggressive blocking ads option, hagezi pro list (https://github.com/hagezi/dns-blocklists). Note that this behaviour also happens on my windows laptop with the same configuration. It worked just fine before I installed adguard extra (about an hour ago)
2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by fortXIV** [comment]
![image](https://github.com/AdguardTeam/AdGuardExtra/assets/97703963/91b81c2f-3ea2-4d3a-819a-bab85cb713a9)

**Comment by jellizaveta** [comment]
@fortXIV Hello. Do you have any search results for this query with AdGuard Extra Extension turned off?

**Comment by fortXIV** [comment]
> @fortXIV Hello. Do you have any search results for this query with AdGuard Extra Extension turned off?

yes ill send you a screenshot in a second

**Comment by fortXIV** [comment]
<img width="1440" alt="image" src="https://github.com/AdguardTeam/AdGuardExtra/assets/97703963/18a79dc2-7693-4cb5-bb99-ddc10106655c">

**Comment by fortXIV** [comment]
okay im not quite sure now since it happens even with incognito mode. Used brave since yesterday and today on this machine with tons of searches without any issues, but the second i downloaded adguard it started happening...

**Comment by jellizaveta** [comment]
AdGuard Extra only works on a [limited list of sites](https://github.com/AdguardTeam/AdGuardExtra/blob/master/dist/hostnames.json). It doesn't do anything on sites that aren't on the list. AdGuard Extra doesn't have any rules for `qwant.com`. My second query search doesn't work for me either, if I write words not very similar to the actual query. Regardless of whether the extension is enabled or not.

**Comment by fortXIV** [comment]
> AdGuard Extra only works on a [limited list of sites](https://github.com/AdguardTeam/AdGuardExtra/blob/master/dist/hostnames.json). It doesn't do anything on sites that aren't on the list. AdGuard Extra doesn't have any rules for `qwant.com`. My second query search doesn't work for me either, if I write words not very similar to the actual query. Regardless of whether the extension is enabled or not.

Yeah I know I checked that link as well before I made the bug report. The weird thing is that when I completetly removed the extension qwant works perfectly again. Im not quite sure where the issue is, but I believe it is something with adguard extra. Maybe they block something vital for qwant indirectly?

**Comment by jellizaveta** [comment]
> Maybe they block something vital for qwant indirectly?

shouldn't, the extension does not trigger on the page

Do you have any errors in the console?

**Comment by jellizaveta** [comment]
@zloyden hello. could you please also check?

**Comment by zloyden** [comment]
@jellizaveta not reproduced on my end. As I recall, AdGuard Extra does not apply to the site.
