### ISSUE TITLE
Add support of IE 11

### ISSUE THREAD

**Issue by maximtop** [AdguardTeam/AdGuardExtra#53]
I'm not sure if the library should support IE11, but there is an error in the console of IE11 when extra is enabled in AdGuard for Windows

https://github.com/AdguardTeam/AdguardAssistant/issues/317#issuecomment-563940918

**Comment by tvinzz** [comment]
https://github.com/AdguardTeam/AdguardAssistant/issues/317#issuecomment-564502254
