### ISSUE TITLE
Yandex SmartCaptcha is broken on iOS

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardExtra#531]
### Prerequisites

- [X] Filters were updated before reproducing an issue
- [X] AdGuard Extra version is up-to-date
- [X] I checked to make sure that this issue has not already been filed

### What product do you use?

AdGuard for iOS, AdGuard Extra with other script manager

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Safari

### Where is the problem encountered?

https://captcha-api.yandex.ru/demo

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter

### Issue Details

Steps to reproduce:
1. Install [Userscripts](https://apps.apple.com/app/userscripts/id1463298887)
2. Enable Userscripts extension in Safari settings
3. Go to https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js
4. Open Userscripts Extension and click `Tap to install`
5. Go to https://captcha-api.yandex.ru/demo
6. Click on `I'm not a robot` checkbox

### Expected Behavior

When you click on `I'm not a robot`, you can pass the captcha

### Actual Behavior

When you click on `I'm not a robot`, nothing happens. Captcha is always highlighted in red

### Screenshots

<details><summary>Screenshot 1</summary>

![IMG_5770](https://github.com/user-attachments/assets/8989a9ee-ee01-453d-acc2-e7955819cef4)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
I can't reproduce.
@jellizaveta Please take a look.

**Comment by jellizaveta** [comment]
Userscript was updated. Please, reinstall the script, clear your browser cache and check the page again.
