### ISSUE TITLE
Incorrect blocking on `e.mail.ru`

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardExtra#537]
### Prerequisites

- [X] Filters were updated before reproducing an issue
- [X] AdGuard Extra version is up-to-date
- [X] I checked to make sure that this issue has not already been filed

### What product do you use?

Adguard for Mac

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Where is the problem encountered?

https://e.mail.ru/inbox/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter

### Issue Details

Steps to reproduce:
1. Открыть https://e.mail.ru/inbox/
2. Промотать вниз писем 20-25
3. Промотать обратно в самый вверх

### Expected Behavior

Все письма видны

### Actual Behavior

Самое первое письмо видно на треть, а также после пятого письма пустое место, и в самом низу списка тоже пустое место

### Screenshots

<details><summary>Screenshot 1</summary>

![image](https://github.com/user-attachments/assets/f36cf7c8-80bd-45cd-be60-b197858dcaf8)

</details>

### Additional Information

Воспроизводиться один раз из четырёх-пяти.

Достаточно только отключить AdGuard Extra, и проблема исчезает

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
@rakleed Спасибо, исправленный код уже в beta версии.
