### ISSUE TITLE
Update the userscript installation information.

### ISSUE THREAD

**Issue by kodiakhub** [AdguardTeam/AdGuardExtra#540]
### Prerequisites

- [X] Filters were updated before reproducing an issue
- [X] AdGuard Extra version is up-to-date
- [X] I checked to make sure that this issue has not already been filed

### What product do you use?

AdGuard Extra with other script manager

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Where is the problem encountered?

https://github.com/AdguardTeam/AdGuardExtra?tab=readme-ov-file#userscript

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

Steps to reproduce:
1. Install Tampermonkey 5.3.0
2. Open Settings, switch mode to "Advanced"
3. Scroll settings page down and find "Inject Mode" there
4. Injection mode is no longer exists.

### Expected Behavior

The Userscript installation information is up-to-date.

### Actual Behavior

The Userscript installation information is out-of-date.

### Screenshots

<details><summary>Screenshot 1</summary>

![image](https://github.com/user-attachments/assets/74b55a66-805a-4117-b593-37eaeaf35264)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Thank you, fixed
