### ISSUE TITLE
twitch ads freezing video

### ISSUE THREAD

**Issue by pierrepgithub** [AdguardTeam/AdGuardExtra#544]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

I am on Ubuntu Linux, using the latest version of Firefox along with the AdGuard and AdGuard Extra browser extensions.

When a twitch ad is played, the video freezes. I can still hear the audio and the chat works fine but the video is frozen until the ads are done.

Is this intentional or is there an issue?

**Comment by jellizaveta** [comment]
Unfortunately, I have not been able to reproduce on my end. @AdamWr , could you please take a look?

**Comment by AdamWr** [comment]
I'm not able to reproduce this issue (when ad is playing I see the notice about blocking ads and video plays correctly).

**Comment by jellizaveta** [comment]
@AdamWr Thanks for checking!

@pierrepgithub Hi there!
I'm really sorry, but we haven't been able to reproduce this issue. Could you possibly send us a link to the stream where this happens?
I just wanted to check one more thing: does it happen in all videos on Twitch, or just some? And which country's IP should I use to test it?

**Comment by pierrepgithub** [comment]
> @AdamWr Thanks for checking!
> 
> @pierrepgithub Hi there! I'm really sorry, but we haven't been able to reproduce this issue. Could you possibly send us a link to the stream where this happens? I just wanted to check one more thing: does it happen in all videos on Twitch, or just some? And which country's IP should I use to test it?

https://www.twitch.tv/echo_esports

@jellizaveta I am watching from the US. Yes it seems to happen to all streams. It says 'Blocking ADs' on the top left corner of the video player, the audio continues but the video is frozen.

**Comment by jellizaveta** [comment]
@pierrepgithub I've noticed a slight playback lag, with occasional video buffering. There is no lag between video and sound, and the picture does not freeze during adverts. Could you please confirm whether there is an issue if you disable AdGuard? Are you watching with or without login?

**Comment by pierrepgithub** [comment]
@jellizaveta i am watching logged in

it seems to be a hit or miss. sometimes it freezes the video, some times the ad is blocked just fine, and sometimes i get the ad. So I dunno.
