### ISSUE TITLE
[twitch] The video download was cancelled. Please try again. (Error #1000)

### ISSUE THREAD

**Issue by ltzmax** [AdguardTeam/AdGuardExtra#546]
### Prerequisites

- [X] Filters were updated before reproducing an issue
- [X] AdGuard Extra version is up-to-date
- [X] I checked to make sure that this issue has not already been filed

### What product do you use?

AdGuard Extra Extension

### What type of problem have you encountered?

AdGuard Extra gets detected on a website

### Which browser(s) do you use?

Firefox

### Where is the problem encountered?

https://twitch.tv

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

Steps to reproduce:
1. launch twitch
2. go to any channel
3. watch for a bit.

### Actual Behavior

Videos gets thrown into `The video download was cancelled. Please try again. (Error #1000)`.

### Screenshots

![wca3b1](https://github.com/user-attachments/assets/0a148e43-7e5c-4bd9-9e94-5465f231f110)

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
@ltzmax Hello. I cannot reproduce this behaviour of the streamer. Do you have any other extensions enabled? 
@BlazDT @AdamWr Could you please also check?

**Comment by BlazDT** [comment]
Watched https://www.twitch.tv/tolkin for about 10 minutes on Android, no issue.

Is the Extension or userscript used?

**Comment by ltzmax** [comment]
> @ltzmax Hello. I cannot reproduce this behaviour of the streamer. Do you have any other extensions enabled? @BlazDT @AdamWr Could you please also check?

Yeah, i forgot to close this issue, it was another addon i had installed that caused the issue and not this one!
