### ISSUE TITLE
wiki.yjsnpi.nu

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdGuardExtra#551]
### Prerequisites

- [X] Filters were updated before reproducing an issue
- [X] AdGuard Extra version is up-to-date
- [X] I checked to make sure that this issue has not already been filed

### What product do you use?

AdGuard Extra Extension

### What type of problem have you encountered?

AdGuard Extra gets detected on a website

### Which browser(s) do you use?

Chrome

### Where is the problem encountered?

https://wiki.yjsnpi.nu/wiki/%E3%83%A1%E3%82%A4%E3%83%B3%E3%83%9A%E3%83%BC%E3%82%B8

### What filters do you have enabled?

AdGuard Base filter, AdGuard Japanese filter

### Issue Details

Steps to reproduce:
1. Visit the site. The anti-adb may not trigger on the top page, in that case move to articles
2. Wait a second, or scroll
3. All the contents will be removed

### Expected Behavior

Contents should be available, and comments at the bottom should be viewable and interactive

### Actual Behavior

Explained

### Screenshots

Omitted

### Additional Information

https://github.com/AdguardTeam/AdguardFilters/issues/190943

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Hello. The solution for this site has been added to the userscript version
