### ISSUE TITLE
Ошибка на сайте Пикабу

### ISSUE THREAD

**Issue by Evgeniy-PNG** [AdguardTeam/AdGuardExtra#553]
### Prerequisites

- [X] Filters were updated before reproducing an issue
- [X] AdGuard Extra version is up-to-date
- [X] I checked to make sure that this issue has not already been filed

### What product do you use?

AdGuard Extra Extension

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox, Chrome, Microsoft Edge, Opera, Yandex Browser

### Where is the problem encountered?

https://pikabu.ru/

### What filters do you have enabled?

AdGuard Russian filter

### Issue Details

Steps to reproduce:
При прокрутке ленты постов сайта Пикабу, лента зависает и не добавляет посты.  Помогает обновить только обновление страницы. Сам сайт Пикабу нельзя добавить в исключение AdGuardExtra. Поправьте этот маленький баг.

### Actual Behavior

При прокрутке ленты постов сайта Пикабу, лента зависает и не добавляет посты.  Помогает обновить только обновление страницы. Сам сайт Пикабу нельзя добавить в исключение AdGuardExtra. Поправьте этот маленький баг. Либо вообще можно исключить сайт Пикабу из этого списка, т.к. с рекламой на его сайте легко справляется любое расширение.
Спасибо!

### Screenshots

<details><summary>Screenshot 1</summary>

</details>
![Пикабу](https://github.com/user-attachments/assets/bd72a316-cd0e-49c0-90bc-774bfd74a688)

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Спасибо за обращение! Исправлено в новой версии

**Comment by Evgeniy-PNG** [comment]
Да, спасибо!
Все работает!
