### ISSUE TITLE
.js injection using pake doesn't work on SoundCloud

### ISSUE THREAD

**Issue by KuVa187** [AdguardTeam/AdGuardExtra#555]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

Hi, I want to create a separate app for SoundCloud using [Pake](https://github.com/tw93/Pake), but the ads are really annoying. Thats why I looked for a solution and stumbled across AdGuard. You can inject .js files using the --inject "path/to/.js/file" option. So I did that with both the AdGuardExtra release and beta script but i still have ads. Maybe I did something wrong? What do I need to do to fix this? Btw. is there also a normal AdGuard script?

Here the pake command if you want to test it yourself:

pake https://soundcloud.com/discover --hide-title-bar --fullscreen --name SoundCloud --icon "path\to\SoundCloud.ico" --inject "path\to\DarkCloud-master\css_dark.css" --inject "path\to\AdGuard User Script\script.js"

**Comment by KuVa187** [comment]
And I tried it with AdGuard Assistant aswell (whatever that is) "path\to\AdguardAssistant-4.3.70\AdguardAssistant-4.3.70\node_modules\@adguard\assistant\dist\assistant.js" and get ads aswell

**Comment by KuVa187** [comment]
so what solution would you recommend? is there a .js script to block soundcloud ads?

**Comment by slavaleleka** [comment]
@KuVa187 
It is unclear why AdGuard Extra or AdGuard Assistant were chosen to block ads on SoundCloud.

[AdGuard Assistant](https://github.com/AdguardTeam/AdguardAssistant) is not designed for this task (please take some time to review its documentation and how it functions with a userscript manager).

As for AdGuard Extra, there is [a limited list of supported websites](https://github.com/AdguardTeam/AdGuardExtra/blob/master/dist/hostnames.json), and SoundCloud is not included, as there has been no need for it.

**Comment by KuVa187** [comment]
Well what do i need to do to make it work?

**Comment by slavaleleka** [comment]
I'm not sure anything can be done in this case. You should consider creating you own userscript for SoundCloud
