### ISSUE TITLE
Incorrect blocking on `e.mail.ru`

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardExtra#556]
### Prerequisites

- [X] Filters were updated before reproducing an issue
- [X] AdGuard Extra version is up-to-date
- [X] I checked to make sure that this issue has not already been filed

### What product do you use?

Adguard for Mac

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Where is the problem encountered?

https://e.mail.ru/inbox/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter

### Issue Details

Steps to reproduce:
1. Открыть https://e.mail.ru/inbox/
2. Промотать вниз писем 20-25
3. Промотать обратно в самый вверх

### Expected Behavior

Все письма видны

### Actual Behavior

В самом низу списка письма перекрывает белый фон

### Screenshots

<details><summary>Screenshot 1</summary>

![image](https://github.com/user-attachments/assets/3466bf25-4831-44c4-bbdc-2695d2f222ec)

</details>

### Additional Information

Сохранённую страницу отправил на filters@adguard.com

Очень похоже на проблему из https://github.com/AdguardTeam/AdGuardExtra/issues/537

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Здравствуйте. К сожалению, я не могу воспроизвести у себя эту проблему. Подскажите, пожалуйста, какие у вас настройки почты?
