### ISSUE TITLE
Пропуск рекламы в браузере Opera

### ISSUE THREAD

**Issue by Evgeniy-PNG** [AdguardTeam/AdGuardExtra#557]
### Prerequisites

- [X] Filters were updated before reproducing an issue
- [X] AdGuard Extra version is up-to-date
- [X] I checked to make sure that this issue has not already been filed

### What product do you use?

AdGuard Extra Extension

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Opera

### Where is the problem encountered?

https://yandex.ru/maps/213/moscow/?ll=37.617700%2C55.755863&z=10

### What filters do you have enabled?

AdGuard Russian filter

### Issue Details

Steps to reproduce: Показывается реклама в браузере Opera на трех страницах.
1. Яндекс карты
2. Яндекс погода
3. Поиск яндекса, контекстная реклама и банерная
4.
5.

### Expected Behavior

Такая проблема только в браузере Opera. Во всех остальных, все хорошо

### Actual Behavior

Показывается реклама в браузере Opera на трех страницах.
1. Яндекс карты
2. Яндекс погода
3. Поиск яндекса, контекстная реклама и банерная

### Screenshots

<details><summary>

![карты](https://github.com/user-attachments/assets/5956d628-ac32-4638-8146-7a37405d284e)

</summary>

</details>

<details>
<summary>Details</summary>

![погода](https://github.com/user-attachments/assets/dc773998-1a37-4a97-ad69-9004c9b0507c)

</details>

<details>
<summary>Details</summary>

![поиск 1](https://github.com/user-attachments/assets/7c8b8dc8-b191-4d86-a7b6-ebee05ce3d26)

</details>

<details>
<summary>Details</summary>

![поиск 2](https://github.com/user-attachments/assets/373ab220-7d84-454e-b6b7-1b021ddb8911)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@Evgeniy-PNG Есть предположение. Сделайте скриншот из настроек расширения (блокировщик и Экстра) по аналогии с этим:

<details>
<summary>Шаг 1</summary>

![image](https://github.com/user-attachments/assets/14e7ce0f-9ff7-4af3-8632-fdf5897c2139)


</details>

<details>
<summary>Шаг 2</summary>

![image](https://github.com/user-attachments/assets/ea996454-7518-49c7-a21a-564d71bda14d)


</details>

**Comment by Evgeniy-PNG** [comment]
Добрый день!
Вот, сейчас Вы подсказали, были отключены "Разрешить доступ к файловым ссылкам и Разрешить доступ к результатам на странице поиска". Как только включил, все заработало. Спасибо, будем знать теперь.

**Comment by Alex-302** [comment]
Отлично. `Разрешить доступ к результатам на странице поиска` - решение проблемы.
