### ISSUE TITLE
AdGuard Extra fails to run

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardExtra#56]
https://github.com/AdguardTeam/AdguardFilters/issues/45772#issuecomment-566055581
Original issue with details:

![image](https://user-images.githubusercontent.com/8361299/71479361-bb8c5700-27fc-11ea-8f3e-31643d6b3603.png)

@Strannikus

**Comment by ameshkov** [comment]
It's already fixed in the latest beta
