### ISSUE TITLE
vidstream.online

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdGuardExtra#6]
On this website https://vidstream.online/f/SzPIoqSMGK blocking popups using rule like that:
`vidstream.online#%#//scriptlet("prevent-window-open")`
or
`vidstream.online#%#(function() { var w_open = window.open, regex = /cv\.php/; window.open = function(a, b) { if (typeof a !== 'string' || !regex.test(a)) { w_open(a, b); } }; })();`
causes adblock detection after clicking on "Download" button.

With AdGuard Popup Blocker, popup is blocked, but "Download" button also doesn't work.

### Expected behavior
Popups on website should be blocked and "Download" button should works.

**Comment by tvinzz** [comment]
`vidstream.online` looks dead

**Comment by AdamWr** [comment]
It seems that they have new domain, now it's `vidstream.to`.
Link:
https://vidstream.to/f/izez8dzLNU

Related issues:
https://github.com/AdguardTeam/AdguardFilters/issues/40013
https://github.com/AdguardTeam/AdguardFilters/issues/37004#issuecomment-513921990

**Comment by tvinzz** [comment]
domain changed to http://vidstream.to/

**Comment by mimo2004moh** [comment]
@AdamWr  new issue after update adguard filters 
the popups blocked and the anti-adblock appear
![Capture](https://user-images.githubusercontent.com/53051408/65822536-5c8f6400-e246-11e9-8d99-aa366d455673.PNG)
shoud i open a new issues
