### ISSUE TITLE
disk.yandex.ru

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/AdGuardExtra#7]
@adguard-bot commented on [Tue Jul 16 2019](https://github.com/AdguardTeam/AdguardFilters/issues/36908)

### Issue URL (Ads)
[https://disk.yandex.ru/client/disk](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fdisk.yandex.ru%2Fclient%2Fdisk)
### Comment
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/ou2vxkd.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Ext
AdGuard version: | 3.1.3
Browser: | YaBrowser
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Block WebRTC, Hide your Referrer from third-parties
Filters: | AdGuard Russian,<br>AdGuard Annoyances,<br>AdGuard Base,<br>AdGuard Tracking Protection,<br>AdGuard Social Media

---

@Alex-302 commented on [Fri Jul 19 2019](https://github.com/AdguardTeam/AdguardFilters/issues/36908#issuecomment-513220457)

Не повторяется. @slavaleleka проверь у себя.
Вероятно, блокировке мешает сам Яндекс Браузер.

---

@slavaleleka commented on [Fri Jul 19 2019](https://github.com/AdguardTeam/AdguardFilters/issues/36908#issuecomment-513233958)

все именно так, проблема в Яндекс-Браузере. например, в Хроме всё чисто

**Comment by tvinzz** [comment]
There is no adv in yandex browser for the moment.
