### ISSUE TITLE
docviewer.yandex.ru

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdGuardExtra#72]
https://github.com/AdguardTeam/AdguardFilters/issues/50431#issuecomment-591682828
I was able to reproduce it. There is no steps, it just exists.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/75421861-46e4ae80-594c-11ea-9a80-adf8849a7419.png)

</details><br/>

**Comment by ameshkov** [comment]
@zloyden try fixing it yourself
