### ISSUE TITLE
Exception on yandex.ru/news 

### ISSUE THREAD

**Issue by Bubliks** [AdguardTeam/AdGuardExtra#79]
***Description***:
Ошибка: Exception thrown and not caught
Возникает в процессе использования Adguard userscript через Tampermonkey на yandex.ru/news

* **Current behaviour**: 
Ошибка описанная в Description возникает в скрипте, который прилинкован у вас в Readme, у меня всегда воспроизводится в Edge17
Stacktrace:
```
_nonIterableSpread
_toConsumableArray
removeNewsAds
```
и
```
_nonIterableSpread 
_toConsumableArray
hideYaDirectAds
```
Вероятно, такая ошибка возникает в результате того, что после того как вы кидаете исключение в скрипте плагин Tampermonkey его не отлавливает. 

Ошибка в userscript:
![image](https://user-images.githubusercontent.com/23708469/81403574-63674900-913c-11ea-980b-8875e4a87794.png)

Сам Adguard userscript:
![image](https://user-images.githubusercontent.com/23708469/81403720-b4773d00-913c-11ea-8b3c-a0ba507ff14d.png)

* **Expected behaviour**: 
Ошибки нет

***Steps to reproduce the problem***:
Шаги описанные в "How to install AdGuard Extra" через Tampermonkey

***System configuration***
Win10, Edge17

**Filters:**
Ad Blocking,  Adguard Russian filter

Information                             | Value
---                                     | ---
Operating system:                       | Win10
Browser:                                | Microsoft Edge 16/17/18
AdGuard version:                        | 3.3.8
Filters enabled:                        | Ad Blocking,  Adguard Russian filter
Userscript host (AdGuard/Tampermonkey): | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js

**Comment by vozersky** [comment]
@Bubliks не могу воспроизвести, у вас все еще получается?

**Comment by zzebrum** [comment]
reopen if needed
