### ISSUE TITLE
lenta.ru - broken images

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardExtra#8]
URL:
https://lenta.ru/articles/2019/07/20/alfa/
Screenshot:
<details>

![image](https://user-images.githubusercontent.com/8361299/61590685-99473b00-abc5-11e9-94f2-3a986724d189.png)

</details>

AdGuard 7.1.2866
AdGuard Extra Beta 1.0.16

**Comment by ameshkov** [comment]
Fixed in AdGuard Extra 1.0.17
