### ISSUE TITLE
Yandex.Weather

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdGuardExtra#89]
https://github.com/AdguardTeam/AdguardFilters/issues/57759#issuecomment-653879985

**Comment by Alex-302** [comment]
https://yandex.ru/pogoda/145?via=srp
AdGuard extension + AG Extra 1.0.127 + Annoyances Filter
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/87290938-4fa6dd00-c507-11ea-9a38-cb800a011fb2.png)

</details>
