### ISSUE TITLE
Adguard, Adguard Extra, and Adguard Popup Blocker still does not block some popups

### ISSUE THREAD

**Issue by adgkart** [AdguardTeam/AdGuardExtra#92]
@EntropyOrSloth commented on [Thu Jul 16 2020](https://github.com/AdguardTeam/AdguardForMac/issues/717)

### Steps to reproduce

1. Install/enable Adguard Extra and Adguard Popup Blocker and install Adguard add-on for Chrome
2. Run Chrome
3. Go to https://thepiratebay0.org/
4. Go to https://thepiratebay0.org/browse

### Expected behavior

I should be able to go to those two pages without popups or new windows.

### Actual behavior

Instead, although there is nothing in the whitelist, this page opens: https://www.get-express-vpn.net/offer/torrent-vpn-2?m=&s=1680%2C1050%2C1%2C1680%2C1050%2C0&v=

The page that opens is this one:

<details><summary>Screenshot:</summary>

<img width="1334" alt="Screenshot 2020-07-15 22 34 36" src="https://user-images.githubusercontent.com/68338672/87620076-9f45fe00-c6eb-11ea-8a28-156d1791279e.png">

</details>

In addition, there are other visible, half-successful attempts to open new windows and visit different websites. For example, see the small white window to the lower right of the screen in the following screenshot. This opened by itself immediately upon visiting one of the pages above.

<details><summary>Screenshot:</summary>

<img width="1680" alt="Screenshot 2020-07-15 22 11 50" src="https://user-images.githubusercontent.com/68338672/87619342-0367c280-c6ea-11ea-93c5-d42565cbae4c.png">

</details>

### Customer ID  2800525

I have submitted a bug report from the app. Ticket # 2800525

### Your environment

* Environment name and version: (e.g. Chrome 59):

MacOS X Catalina 10.15.6
Chrome Version 83.0.4103.116 (Official Build) (64-bit)

* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)

CleanMyMac

---

@EntropyOrSloth commented on [Thu Jul 16 2020](https://github.com/AdguardTeam/AdguardForMac/issues/717#issuecomment-659507205)

It appears that the application which is launched, and is not prevented from running by AdGuard, is some sort of cryptominer app. it runs and alternates popping up in the lower right corner and the upper left corners of the screen and alternates between these two locations about 10 times per second.

<img width="1680" alt="Screenshot 2020-07-16 11 53 48" src="https://user-images.githubusercontent.com/68338672/87693888-7d845f80-c75b-11ea-9dad-2c4fd04f8827.png">

<img width="1680" alt="Screenshot 2020-07-16 11 53 50" src="https://user-images.githubusercontent.com/68338672/87693918-89702180-c75b-11ea-9fab-4c09f78fe8e0.png">

---

@adgkart commented on [Fri Jul 17 2020](https://github.com/AdguardTeam/AdguardForMac/issues/717#issuecomment-660040753)

Hi! I noticed on your screenshots that you have a lot of apps active. Some of them may have conflicts with AdGuard (ex.: Adblock Plus, BitDefender, etc.) Could you please close/remove all these apps and check once again?

---

@EntropyOrSloth commented on [Fri Jul 17 2020](https://github.com/AdguardTeam/AdguardForMac/issues/717#issuecomment-660100383)

> Hi! I noticed on your screenshots that you have a lot of apps active. Some of them may have conflicts with AdGuard (ex.: Adblock Plus, BitDefender, etc.) Could you please close/remove all these apps and check once again?

Thank you adgkart. I have uninstalled Adblock Plus and Bitdefender Trafficlight. I also turned off Bitdefender Shield (although did not uninstall it). I then exited Chrome and restarted it.

I went to: https://thepiratebay0.org/
And then to: https://thepiratebay0.org/browse

The same thing happens: _(Note that first the ad pops up in a new tab of Chrome, then the white boxes appear in the upper left and lower right of the screen, flashing and alternating about 10 times per second, and then a new window in Chrome pops up with what appears to be the same ad.)_

<img width="1680" alt="Screen Shot 2020-07-17 at 9 07 45 AM" src="https://user-images.githubusercontent.com/68338672/87789668-67cf7280-c80d-11ea-839b-2f20205dd73c.png">
<img width="1680" alt="Screen Shot 2020-07-17 at 9 08 35 AM" src="https://user-images.githubusercontent.com/68338672/87789682-6e5dea00-c80d-11ea-81a3-457be92ad05b.png">
<img width="1680" alt="Screen Shot 2020-07-17 at 9 08 37 AM" src="https://user-images.githubusercontent.com/68338672/87789696-728a0780-c80d-11ea-899a-cc9cc616806f.png">
<img width="1680" alt="Screen Shot 2020-07-17 at 9 09 06 AM" src="https://user-images.githubusercontent.com/68338672/87789713-77e75200-c80d-11ea-9c61-6ae6603b8ee3.png">

---

@EntropyOrSloth commented on [Fri Jul 17 2020](https://github.com/AdguardTeam/AdguardForMac/issues/717#issuecomment-660116695)

> > Hi! I noticed on your screenshots that you have a lot of apps active. Some of them may have conflicts with AdGuard (ex.: Adblock Plus, BitDefender, etc.) Could you please close/remove all these apps and check once again?
> Thank you adgkart. I have uninstalled Adblock Plus and Bitdefender Trafficlight. I also turned off Bitdefender Shield (although did not uninstall it). I then exited Chrome and restarted it.
> 
> I went to: https://thepiratebay0.org/
> And then to: https://thepiratebay0.org/browse
> 
> The same thing happens: _(Note that first the ad pops up in a new tab of Chrome, then the white boxes appear in the upper left and lower right of the screen, flashing and alternating about 10 times per second, and then a new window in Chrome pops up with what appears to be the same ad.)_

I have made a video of the strange popups that Adguard is letting through, including the flashing popups that appear on the upper left and lower right corners. [This is the URL link for the Youtube video of this happening.](https://youtu.be/5hHq3LDckw4)

In case the Youtube video is gone, uncompress and view the file below. It's a lower resolution version of the same.

[Demonstration of Strange Popups that Adguard Lets Through.mp4.zip](https://github.com/AdguardTeam/AdguardForMac/files/4938100/Demonstration.of.Strange.Popups.that.Adguard.Lets.Through.mp4.zip)

---

@akmLaVx commented on [Sat Jul 18 2020](https://github.com/AdguardTeam/AdguardForMac/issues/717#issuecomment-660455242)

All additional information available in support ticket 2800525

**Comment by zloyden** [comment]
Hi, sorry for the later response. It was fixed a long time ago via filters.
Please check the site with AdGuard for Chrome and without similar extensions like `Adblock Plus`.
