### ISSUE TITLE
Tampermonkey does not work Inject Mode

### ISSUE THREAD

**Issue by webmastak** [AdguardTeam/AdGuardExtra#96]
The top and bottom blocks are not blocked on the main page of the site [yandex.ru](https://yandex.ru) 
**Inject Mode** selected.
**AdGuard** blocks only if you refresh the page.

![02](https://i.imgur.com/sDBjPdx.png)
![01](https://i.imgur.com/oEql6Hf.png)

Everything works as it should in the **Vivaldi** browser!

**Comment by zloyden** [comment]
Hello! Hm, those elements have already blocked in Annoyances filter. I can't reproduce it on Chrome Canary.
@ameshkov should we duplicate it on Extra?

**Comment by webmastak** [comment]
> @ameshkov should we duplicate it on Extra?
It would be nice.

Works in **AdGuard** if you refresh the page!!!!

**Comment by ameshkov** [comment]
Tbh, I don't think we should.

The purpose of AG Extra is blocking ads that cannot be blocked by regular filter lists.

**Comment by webmastak** [comment]
**AdGuard** blocks only if you refresh the page!!!!!!!!!

**Comment by zloyden** [comment]
@webmastak I don't think that's the problem of filters, but please make a report via this [link](https://agrd.io/report).
It will give us more information than we have now.
